### ISSUE TITLE
FR: Exportado de metadatos

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#100]
Hola:
¿Sería posible un exportado de metadatos? Tenemos cada vez más elp's ya catalogados y nos sería muy útil poder exportar metadatos para importarlos en otros elp's.

Saludos

**Comment by jm-andonegi** [comment]
Sólo un comentario: no olvidar llevar lo que se haga a una opción de comando de exedo. Así se puede automatizar la labor.

**Comment by jm-andonegi** [comment]
Ahora se puede hacer esto:

    Rellenar la ficha de metadatos de un paquete (un modelo)
    Exportar como SCORM
    Descomprimir el paquete
    Abrir el paquete al que se quiere importar los metadatos.
    Importar el archivo de metadatos (imslmr.xml)

Evidentemente, poder exportar directamente los metadatos ahorra tiempo.

**Comment by ignaciogros** [comment]
Not in eXe 2.6+.
