### ISSUE TITLE
FR: nuevo árbol curricular

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#101]
Hola:

Estamos ya con la LOMCE pero no existe un nuevo árbol curricular.  Se que esto implicaría cambios también en Agrega.

¿Hay alguna noticia?

Gracias

**Comment by miguelpereiraite** [comment]
Buenos días.
Para diciembre, está previsto que en Procomún se implemente un nuevo modelo de etiquetado curricular de los recursos que lo desvincule (dentro de lo posible) de los cambios legislativos.

A partir de ahí, tendremos que analizar cómo incorporar ese nuevo modelo a eXe. Dejo abierto este tema para ir incorporando documentación.

**Comment by ignaciogros** [comment]
This won't be in eXe 2.6. We'll reopen the issue when having more information.
