### ISSUE TITLE
Problem with versions and dependencies

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#104]
My solution to issue #99 was not correct. It creates a new issue.
eXe now needs python-cssmin. The point is 

1) in Debian Testing, adding a dependency to 'cssmin' brings python3-cssmin. That's why I added by hand also a dependence to python-cssmin.

2) in Ubuntu 16.04, there's no package python-cssmin, so only cssmin is necessary.

We would also have to test Debian Stable and Ubuntu 14.04 at least.

Solutions?
If I remove python-cssmin, eXe is not installable in Debian Testing. If I don't remove it, it's not installable in Ubuntu 16.04.

This evening I will add an optional 'cssmin | python-cssmin'. If that does not work, we would have to create two different packages.

Can anyone help me with the tests?

**Comment by jrfern** [comment]
"python-cssmin | cssmin" in debian/control. This needs testing in different versions of Debian and Ubuntu.

Please test (build the package with python make.py in install/debian/ubuntu)

**Comment by jrfern** [comment]
Sorry, I misspelt 'dependency'

**Comment by ignaciogros** [comment]
Juan:

Creo que esto quedó resuelto. Por favor, confirmad si es así. ¿Cerráis? Gracias...

**Comment by jrfern** [comment]
Yo también creo que está resuelto, a falta de comprobación/confirmación por parte de @JuanCasanovaSdweb .

Gracias

**Comment by JuanCasanovaSdweb** [comment]
En principio esto resuelve el problema de la dependencia de cssmin. Cierro la incidencia.
