### ISSUE TITLE
legal.html and debian/copyright  are outdated

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#106]
Por favor, los que hayáis añadido bibliotecas o las hayáis actualizado, registrad los cambios en legal.html y en debian/copyright.

**Comment by ignaciogros** [comment]
Muchas gracias por el aviso.

Me quito de la lista de "Assignees". Lo que he añadido está reflejado en este cambio: c4bf4727b0f7f594a9db70604ee0715ce38e6bab

**Comment by ignaciogros** [comment]
Juan:

¿Habéis añadido todo? Si es así, ¿podéis cerrar la incidencia? Gracias...

**Comment by JuanCasanovaSdweb** [comment]
Nosotros no hemos incluido ninguna librería que vaya empaquetada con eXe.

No veo ningún sitio en esos dos archivos donde estén listadas las librerías Python que se descargan con eXe, así que entiendo que no quedaría nada por actualizar. ¿Me equivoco?

**Comment by ignaciogros** [comment]
En legal.html, etc. se listan las librerías y aportaciones de terceros junto a sus licencias, pero no veo referencias a código Python.  Añado TinyMCE 4, que se había quedado fuera: 90ac1f9c8e56511759fd53b4d4707e718ba319ad.

Si no habéis añadido nada, cierro la incidencia, dando por hecho que se hasta ahora se estaba reconociendo el trabajo de terceros adecuadamente.

@pedropena:

Tú tendrás claro cómo debe hacerse. Avísanos si crees que faltan reconocimientos relacionado con Python, por favor.
