### ISSUE TITLE
section=python or section=education?

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#107]
In debian/control we assign eXe to section python; this is wrong, as it is not a library but an application. My proposal is to change it to section education. 

Anyone sees a problem with the change?

**Comment by miguelpereiraite** [comment]
I think it's ok. 
Any other opinions?

**Comment by ignaciogros** [comment]
Thanks, @jrfern. I agree with you.

**Comment by jrfern** [comment]
Fixed. Closing issue.
