### ISSUE TITLE
Enlaces a la forja en la portada

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#108]
Hola, acabo de darme cuenta de que en la portada , en el README , aparecen varios enlaces a  la forja. 

Saludos

**Comment by jrfern** [comment]
Corregido (espero). Por favor chequead.

**Comment by Rafav** [comment]
Yo los he visto bien. Otra sugerencia, para Fedora ¿poner también el enlace a http://exelearning.net/descargas/?

**Comment by ignaciogros** [comment]
Incluyo lo de Fedora y corrijo un par de erratas: c274a833b41f342716d8f954b983661306a0bbe5

Gracias a a los dos.
