### ISSUE TITLE
Imagen que sirva de portada para epub y miniatura en Agrega

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#110]
Hola:

¿Habéis previsto la posibilidad de usar alguna imagen como portada para el epub?

Y lo mismo para Agrega. En este caso  bastaría con que la imagen se llame vistaPreviaAgrega y (según Agrega ) "Imagen del ODE (jpg, png, tiff, gif, bmp...)"

Saludos

**Comment by ignaciogros** [comment]
@antton's idea (see #166, which is closed):

> It would be nice to have an interactive panel before saving the elp as epub asking for a Title and picture for the cover, or even a general option for this part, otherwise It would take the first image that the elp has, letting the exportation a bit strange.

**Comment by JuanCasanovaSdweb** [comment]
After talking internally, we have decided to also add a back cover to this FR.
Should be easy once we finish the front cover part.
