### ISSUE TITLE
Hide/show nodes/devices

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#116]
Sometimes you don't want to show all the content because it's too complex or because it is not finished. It would be nice to have this option to hide some parts of the content without deleting them.

**Comment by ignaciogros** [comment]
Do you mean choosing if an iDevice should be collapsed by default? That would be another iDevice preference. I hope that those preferences can be created soon.

Thanks.

Provisional solution: http://exelearning.net/forums/topic/iniciar-un-idevice-con-toggle-cerrado/#post-18554

**Comment by ignaciogros** [comment]
The idea was hiding a nodes, not collapsing iDevices. See http://exelearning.net/forums/topic/esconder-un-nodo-en-desarrollo-al-exportar/

Both things could be done. One in with Node Preferences, another with iDevice Preferences.

**Comment by jm-andonegi** [comment]
I was thinking in this request: [http://exelearning.net/forums/topic/esconder-un-nodo-en-desarrollo-al-exportar/](http://exelearning.net/forums/topic/esconder-un-nodo-en-desarrollo-al-exportar/)
I think there was a similar FR in the old Forge. Of course, this can be a priority or not.

**Comment by ignaciogros** [comment]
The idea is to renew all the code (there's no date yet), and this should be part of that new version.
