### ISSUE TITLE
Problem with user iDevice in the user's ~/.exe/idevices

### ISSUE THREAD

**Issue by rfrobenius** [exelearning/iteexe#117]
I was having problems with an iDevice I created in Python using the Example Idevice as a template. The iDevice would not show up in the menu after placing the iDevice file and the block file into the /idevices directory.
I discovered that if I edited line 132 of idevicepane.py from:
`prototypesToRender.append((prototype, _('My iDevices'), visible))`
to:
`prototypesToRender.append((prototype, x_('My iDevices'), visible)) `----added an 'x'
my idevice will appear in the menu properly.
I also found that I have to delete the idevice py file from the idevices directory, but leave the block py file there for everything to work on subsequent launches.

**Comment by ignaciogros** [comment]
Thanks, @rfrobenius.

We will update the documentation.
