### ISSUE TITLE
Problems with links to HTML files

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#118]
Add a link to an HTML file called index.html and then export or preview.

eXe's index.html file is replaced by the attachment. That will also happen when adding links to any HTML file with the same name as one generated by eXe.

Should they be renamed? In that case, the user should be warned.

This will be solved when eXe allows folders.

See the attached file and http://exelearning.net/forums/topic/problemas-con-el-index/

**Comment by JuanCasanovaSdweb** [comment]
Maybe we should postpone this a little bit and try to allow folders in eXe exports (may be going too far?).
Either way, we are going to need new translated strings, so I'm removing the 2.1.1 milestone and adding the FR label.

**Comment by ignaciogros** [comment]
I agree: We should "try to allow folders in eXe exports" as soon as possible.

**Comment by ignaciogros** [comment]
Another test:

Insert 2 identical images with different names. eXe will remove one of them.

**A user reports:**

> Es decir, tengo un elp con dos imágenes que son iguales pero con diferente nombre y cada una de ellas se apunta desde diferentes puntos del elp. Lo que hace eXe es detectar que son la misma imagen y para optimizar recursos elimina una de ellas pero el enlace desde se apuntaba a la imagen eliminada no se sustituye por la imagen que ha quedado, tampoco da aviso de que ha sido eliminado y corres el riesgo de no darte cuenta y perder esa información.

**Comment by ignaciogros** [comment]
There will be a file manager in the future. For the moment, eXe will do this: #396
