### ISSUE TITLE
eXe portable no arranca en Debian

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#119]
"Mi problema es que no puedo hacer funcionar la edición portable en mi Debian Jessie".

Más información en http://exelearning.net/forums/topic/exelearning-portable-2-1-no-arranca-en-debian/

**Comment by jrfern** [comment]
En el foro no se ha recibido en un mes más información sobre este problema, que además se refiere a la 2.1, no a la 2.1.1. Testear las versiones portable debe formar parte de las tareas del equipo de pruebas, y por tanto no sería necesario mantener el issue abierto. ¿qué opináis?

**Comment by JuanCasanovaSdweb** [comment]
Cierro la incidencia ya que no se ha podido reproducir y no se ha obtenido más información por parte del usuario.
