### ISSUE TITLE
Ustad Mobile export not maintained

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#120]
I know this has been discussed, but I don't see an issue to follow the topic. Mike left the project long ago, and he was the creator and maintainer of this export. Should we just remove this export, which none of us uses or controls? Isn't correct modern HTML5  enough for mobiles?

By the way, removing this part of the code has some implications in the documentation. For instance, the README says: "Content generated using eXeLearning can be exported as (...) on mobile devices". This is not the new HTML5 export, but Ustad.

A decision should be taken.

**Comment by ignaciogros** [comment]
@mikedawson:

Is eXeLearning's Ustad Mobile export working properly, or are you using your own version/distribution?

If eXe's current export is failing, I think that we should remove it. It it works... Is it updated? 

@jrfern: 

eXe's default website export works well in modern devices. Ustad Mobile is useful to work offline with old phones. Is that right, Mike? In my opinion, if that export works, is still useful and it's updated (I think that only @mikedawson can keep it updated), it should be part of eXe. It not, we should remove it.

Thanks!

**Comment by mikedawson** [comment]
Hi,

Actually we have since updated both the feature phone and Android versions of our app to read EPUB files directly which is far more inter-operable.  This export functionality is not used: if it helps I can make a pull request that will cleanly remove it.

-Mike

**Comment by ignaciogros** [comment]
Hi, @mikedawson.

> if it helps I can make a pull request that will cleanly remove it.

Yes, please!

Thank you.

**Comment by ignaciogros** [comment]
@JuanCasanovaSdweb,

I just removed the 'Ustad Mobile' export from the toolbar. Please check the commit (35f35220d0aa544115e64648dc00b205dd03c666) and tell me if you find any problem. If removing that export from the Python code is easy and there's no risk in doing so, maybe we could do it now and close this issue. Could check that, please?

**Comment by ignaciogros** [comment]
No changes in eXe 2.6+ That export option won't be in the new eXeLearning.
