### ISSUE TITLE
OSx 10.10.5: eXe is not working

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#129]
A user writes: 

"Tengo OSx 10.10.5 y me dice que no funciona en esta versión, que tengo que actualizar el sistema a 10.12."

It works with 10.12.2.

**Comment by JuanCasanovaSdweb** [comment]
It seems that "py2app" applications made with MacOS X 10.12 Sierra are not compatible with previous versions. 
We have updated the Dropbox package with one made in MacOS X 10.10 Yosemite which seem to work fine in both systems.
We will do some research on this to see if we are able to generate packages in Sierra.

**Comment by miguelpereiraite** [comment]
Sería interesante, cuando esta incidencia esté corregida, comunicárselo a Aníbal de la Torre (que fue quien la comunicó) para que haga pruebas de nuevo.

**Comment by anibaldelatorre** [comment]
Buenas tardes
Gracias por vuestra ayuda, pero aproveché el tema y actualicé a 10.12.2 mi OSx, no podía vivir sin mi eXe :)
Salud!

**Comment by JuanCasanovaSdweb** [comment]
We found a workaround for this (generate the package on 10.10).
We will be looking more into this, but we don't have to do it right now.

**Comment by JuanCasanovaSdweb** [comment]
This is more an FR than an issue now!

**Comment by ignaciogros** [comment]
eXe is currently working on the latest MacOS versions. I think that we can close this, at least for the moment. It's been open for more than 3 years, and we had no comments about this lately.
