### ISSUE TITLE
Image Gallery iDevice

### ISSUE THREAD

**Issue by videophonegeek** [exelearning/iteexe#13]
The galleryIdevice does not allow select multiple file selections:
1. Click Add image button
2. Title on FilePicker says "Select one of more images"
3. Try to select multiple images.  Name: field only shows last one clicked in the select.

askUserForImage(multiple, fn, filter) in authoring.js is called with multiple==TRUE and there mode = parent.eXe.view.filepicker.FilePicker.modeOpenMultiple; where type is set in the parameters.

**Comment by ignaciogros** [comment]
FR.

**Comment by ignaciogros** [comment]
Cambio asignación. Está pendiente desde hace tiempo. Creo que Pedro lo tiene controlado.

**Comment by ing-arriola** [comment]
Saludos estimados

El año pasado empece a trabajar con eXeLearning pero veo que efectivamente tiene problemas con el tema de ingresar varias imagenes, lo cual me ha parecido que puede mejorarse a fin de crear en forma mas facil los SCORM.

Justamente el dia que comento esto he observado que el detalle en mencion aun perstiste, lo cual me lleva a preguntarme: ¿Hay planes actualmente para resolver esto?

**Comment by ignaciogros** [comment]
Hola @ing-arriola:

> ¿Hay planes actualmente para resolver esto?

Sí. Está en la hoja de ruta de este año, pero aún no sabemos exactamente cuándo estará.

**Comment by ignaciogros** [comment]
Not in eXe 2.6+. I'll be possible in the new eXeLearning.
