### ISSUE TITLE
TinyMCE/Mac: Paste image problem

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#130]
A user writes:

"Al probar lo de copiar y pegar una imagen desde el portapapeles, no me funciona, esto es lo que se pega:"

![mac_d_and_d](https://cloud.githubusercontent.com/assets/2928868/22060242/4acdfd18-dd70-11e6-88ab-4b2f1f3af677.gif)

He is using Mac OS Sierra 10.12.2.

**Comment by SantiagoGonzalezSdweb** [comment]
He intentado replicar el error y no lo consigo, necesitaría más datos:  navegador y su versión, de donde copia la imagen y formato de esta.

**Comment by anibaldelatorre** [comment]
Buenas tardes
Ahora sí me funciona bien, no sé si fue a raíz de la actualización de mi sistema OSx.
Luego no puedo aportaros más información para reproducir el problema que tenía. Sí recuerdo que pasaba tanto al intentar pegar una imagen desde el portapapeles como al arrastrarla desde una carpeta del sistema.
Gracias y salud!

**Comment by SantiagoGonzalezSdweb** [comment]
Hola, seguimos haciendo pruebas y no conseguimos repilcar el error, sabrías en que navegador te daba este error? gracias

**Comment by anibaldelatorre** [comment]
Buenas
Me dio en OSx 10.10 con Chrome 56.0
Salud!

**Comment by ignaciogros** [comment]
¡Gracias por el aviso y las pruebas, Aníbal!

De momento marco como no reproducible. Reabrimos si vuelve a surgir.
