### ISSUE TITLE
FR: Usability problem when trying to edit a Style

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#139]
Some users think that the Style Editor is not working because of the warning message: "The current Style is not compatible with the Style Designer".

Only the Styles created with the Editor can be edited. eXe's Styles are not editable. 

We should change that message in the next version. It's in /jsui/scripts/app/controller/Toolbar.js

@jrfern?

**Comment by jrfern** [comment]
Agreed. How about "Sorry, only styles created with the Editor can be edited. eXe's Styles are not editable"

Could anyone create milestone 2.1.2 and close 2.1, please? I don't think I can do it myself.

**Comment by jrfern** [comment]
@ignaciogros , @miguelpereiraite , do you agree with my proposal from February 3rd?

**Comment by ignaciogros** [comment]
I agree, @jrfern. Thank you!

**Comment by jrfern** [comment]
Fixed applied. Closing the issue.
