### ISSUE TITLE
FR: Hangman game available letters

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#140]
The Hangman game's default letters are: abcdefghijklmnñopqrstuvwxyz

ñ should not be there. It should be only in the Spanish version.

abcdefghijklmnopqrstuvwxyz should be translated as any other string, adapted to each language. It should include vocals with accent in Spanish, por example:

aábcdeéfghiíjklmnñoópqrstuúvwxyz

**Comment by jrfern** [comment]
My analysis:
1) exe/webui/scripts/exe_games/exe_games.js is not internationalized. Please i18n'ize it.

2) exe/webui/scripts/tinymce_3.5.11/jscripts/tiny_mce/plugins/exegames/langs/en.js
Acknowledged. To be done.

3) exe/webui/scripts/tinymce_4/js/tinymce/plugins/exegames_hangman/plugin.min.js
Acknowledged. To be done.

I dont' think it's a FR, but a bug - one must be able to write in one's own language with all the words and characters in your language. But as this modifies strings, the fix will be applied after we publish 2.1.1.

**Comment by ignaciogros** [comment]
Thanks, Juan Rafael.

264297c1fd622306187a63e469739810a64e0304 removes _("abcdefghijklmnñopqrstuvwxyz") from the code.

That part was a bug. The FR consists on adding common characters in each translation: aábcdeéfghiíjklmnñoópqrstuúvwxyz in Spanish, for example.

Some users, like P. Nimo, requested that.

The bug is fixed.

**Comment by ignaciogros** [comment]
English is the default language (see 4a3d18cab56c0eb02737a6ac11bd9e939db62d4f), but the strings will be in the selected language. 

Maybe in the future we'll have to add áéíóú to the Spanish translation.

Closed for the moment.

Thanks, @jrfern!
