### ISSUE TITLE
FR: Insert pagination

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#142]
It would be interesting to add an option to export so that page number and total pages could be shown. May be it could be some kind of JavaScript variable so that it could be also used in a progress bar or something similar.

The feature has been requested [in this forum message](http://exelearning.net/forums/topic/progreso-en-actividad-scorm/).

**Comment by ignaciogros** [comment]
Good idea. Thanks!

**Comment by JuanCasanovaSdweb** [comment]
Only the first has been done. The JS part is still pending.

**Comment by ignaciogros** [comment]
No JavaScript, just HTML and CSS.

Notice that the Tknika Style does not show the pagination.
