### ISSUE TITLE
FR: Inline math formulas

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#152]
Allow inline formulas (created with the 'Paste mathematical markup' TinyMCE plugin.

See http://exelearning.net/forums/topic/escribir-ecuaciones-en-linea/

**Comment by ingodahn** [comment]
Please, give this a high priority. As there seem to be problems with editing the HTML code too (when I type < a list of tags is displayed but no selction takes effect and I cannot continue editing manually) I can currently enter a formula x^2+px+q inline only as image.
Alternatively please provide a possibility to copy MathML (as produced e.g. by MathType) into the page.

**Comment by ignaciogros** [comment]
Hi, @ingodahn.

> when I type < a list of tags is displayed but no selection takes effect and I cannot continue editing manually

Please try the simple HTML editor (Tools - Edit source code).

> Alternatively please provide a possibility to paste MathML (as produced e.g. by MathType) into the page.

You can paste MathML code in the new plugin, but you'll have to uncheck the "Include alternative image" option. The formulas won't be inline.

To add inline formulas use the "Paste HTML fragment" option. The problem is that you'll need the browser to support MathML, unless you paste this code (or a similar one) in Properties - Footer (see the attachment):

```
<script type="text/javascript">
	$(function(){
		if ($(".exe-math").length==0 && $("math").length>0) $exe.loadScript($exe.math.engine);
	});
</script>
```
That will load MathJax. 

We'll try to make that easier.

[inline_math_formula.zip](https://github.com/exelearning/iteexe/files/878220/inline_math_formula.zip)

**Comment by ingodahn** [comment]
Yeap, works fine! It would be convenient for us if we could put the script call into a file in the style. In fact we use already our own style with added javascript support for going to next/previous page using a gesture on touch devices, though the style editor doesn't like it.

**Comment by ingodahn** [comment]
Please, have a look at https://netmath.vcrp.de/downloads/Skripte/Schell/Mathe1/00-Hilfsmittel/
The page looked fine in the editor, but not after export to a web site. I get 
Uncaught TypeError: Cannot read property 'engine' of undefined
The export from your sample file worked fine, so it may be a problem with our theme, but I have no clue (a documentation of the style editor might be helpful).

**Comment by ignaciogros** [comment]
Hi @ingodahn.

It's just because you're using eXe 2.1.1 instead of 2.1.2. 

Just replace `$exe.math.engine` with `"https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"`.

I hope it works.

**This is how the Style Designer works:** 

It creates a copy of "base" in a different folder. The name of the new Style is in its config.xml file. 

A compatible Style starts with this line:

`/* eXeLearning Style Designer Compatible Style */`

And after this line you'll find what you can edit using the editor:

`/* eXeLearning Style Designer */`

The Style Designer gets the previous values looking for comments (/*aColor*/ to get the value for the aColor field, for example).

I hope we can document all that properly soon.

Thanks for the suggestion.

**Comment by ingodahn** [comment]
Hi,
I confirm it works with 2.1.2.
As for the style editor (though I am not sure whether this is the right place to discuss), it doesn't let me edit any of the existing styles and if I create a new style it shows me a sample script page but doesn't tell me where it creates the copy and under which name. Is there a way to edit a copy of an existing style with a new name?

**Comment by ignaciogros** [comment]
Hi, @ingodahn. Please use the [forums](http://exelearning.net/forums/) for that. Only those Styles based in Base are editable. You can also use the Editor's "Save as" button (edit a compatible Style and then save a copy with a different name).

**Comment by ignaciogros** [comment]
Inline formulas example: http://exelearning.net/forums/topic/escribir-ecuaciones-en-linea/#post-28543

It's better to write the formula or use the 'Paste HTML fragment' options instead of the 'Paste math code' plugin. **We'll improve the documentation.**

**Milestone:** 2.1.4 (because some new strings will be required).

**Comment by ignaciogros** [comment]
In the future we'll revise the way eXe allows math formulas, because many users are just using LaTeX + MathJax instead of the TinyMCE plugin. eXe 2.6+ will still have the current options.

Related tutorial (in Spanish): https://latex.bilateria.org/
