### ISSUE TITLE
Identical images with different names

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#155]
Insert 2 identical images with different names. eXe will remove one of them.

**A user reports:**

> Es decir, tengo un elp con dos imágenes que son iguales pero con diferente nombre y cada una de ellas se apunta desde diferentes puntos del elp. Lo que hace eXe es detectar que son la misma imagen y para optimizar recursos elimina una de ellas pero el enlace desde se apuntaba a la imagen eliminada no se sustituye por la imagen que ha quedado, tampoco da aviso de que ha sido eliminado y corres el riesgo de no darte cuenta y perder esa información.

**Comment by antton** [comment]
I think that the issue #118 is talking about the same problem.

**Comment by ignaciogros** [comment]
You're right. I close this one. Thanks!
