### ISSUE TITLE
Javascript not working in ePub format

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#158]
Morning, 

In our ULHI eXeLearning version when we export into epub format everything is working except the character codification that I don't know why yet is not taking the UTF8 standard but the javascript is working properly otherwise in the official eXeLearning version the characters are ok but we can't make it work the javascript, non even any idevice that would need it, so I think there is a bug on the export funtionality.

**Comment by ignaciogros** [comment]
You're right. That's important. Thanks a lot, @antton.

**Comment by ignaciogros** [comment]
@JuanCasanovaSdweb:

Could you check epub3subexport.py and epub3export.py?

Thanks.

**Comment by antton** [comment]
Also in our version the input box activities doesn't work.

But I think after fixing the problem we could check again with all of different  idevices.

Thanks

**Comment by ignaciogros** [comment]
That's right. Most iDevices are not working. Thanks, Antton.

**Comment by JuanCasanovaSdweb** [comment]
1dedf298c90369d6b9551058b256dfbdc94757b2 should fix this.

I'm closing this, if there is any problem with an iDevice, please, open a new issue.
