### ISSUE TITLE
tablas

### ISSUE THREAD

**Issue by sandrainchauste** [exelearning/iteexe#159]
Tengo el problema de que no puedo copiar tablas o Imágenes en un texto libre.  Antes podía hacerlo pero ahora no copia los bordes de la tabla.  Cuando quiero usar los botones de copiado me dice que el browser no puede soportar esta acción, pero estoy usando crome.  Gracias!

**Comment by ignaciogros** [comment]
Hola @sandrainchauste:

No consigo reproducir el fallo. He copiado y pegado una tabla en G. Chrome, y he comprobado que el comportamiento es igual en el nuevo editor (TinyMCE 4) que en el anterior (3.5.11).

Si te sigue fallando, ¿puedes darnos más detalles (versión, sistema operativo, pasos a seguir...)?

Muchas gracias.

**Comment by sandrainchauste** [comment]
Hola

Muchas gracias por contestar y por tener disponible una herramienta tan
útil.

Sigo teniendo el problema.  Anteriormente cuando copiaba una tabla de word,
simplemente hacía control C y luego control P en el texto libre de
exelearning y se copiaba la tabla.  Ahora cuando hago eso se copia la tabla
pero me muestra los bordes de la tabla en línea punteada en el editor,
cuando lo muestro en su forma final, no sale ninguna de las rayas de la
tabla.  Te envío un módulo que hice con tablas, y el segundo en el que
trabajo, que ya no contiene tablas pues no las puedo poner.
La versiòn que uso es 2.1.1 que es la que se puede descargar.  Uso windows
7.



2017-03-12 14:26 GMT-04:00 Ignacio Gros <notifications@github.com>:

**Comment by sandrainchauste** [comment]
Una pregunta más, no se si han pensado incluir entre las herramientas
interactivas la posibilidad de arrastrar palabras para llenar espacios o
para formar oraciones, como en duolingo.

Muchas gracias!

2017-03-13 11:46 GMT-04:00 Sandra Inchauste <sandrainchauste@gmail.com>:

**Comment by ignaciogros** [comment]
Hola Sandra:

> Te envío un módulo que hice con tablas, y el segundo en el que trabajo, que ya no contiene tablas pues no las puedo poner

No veo el módulo. ¿Lo puedes adjuntar?

> Una pregunta más, no se si han pensado incluir entre las herramientas interactivas la posibilidad de arrastrar palabras para llenar espacios o para formar oraciones, como en duolingo.

Se incorporará al menos un iDevice para ordenar frases (una lista desordenada). Lo de arrastrar palabras no, aunque creo que es lo mismo que la "Pregunta de selección múltiple", pero permitiendo pinchar y arrastrar en lugar de seleccionar de una lista de opciones. eXe cuida el nivel de accesibilidad de sus actividades, y ese es el motivo por el que a veces no se presentan de una forma tan llamativa. No conocía Duolingo. Lo probamos por si tiene ideas para incorporar más adelante. 

¡Gracias!

**Comment by ignaciogros** [comment]
Cerramos la petición por no poder reproducir el fallo y no contar con información adicional.
