### ISSUE TITLE
Failed to load jquery.min.map

### ISSUE THREAD

**Issue by videophonegeek** [exelearning/iteexe#16]
This error occurs in most browsers.  Edit the exe.jquery.js to remove the reference if it cannot be provided.
/*! jQuery v1.9.1 | (c) 2005, 2012 jQuery Foundation, Inc. | jquery.org/license
//@ sourceMappingURL=jquery.min.map

**Comment by ignaciogros** [comment]
Thanks, videophonegeek.

master's exe_jquery.js does not include sourceMappingURL because that file won't be exported. Otherwise It'll be triggering a 404 error.
