### ISSUE TITLE
Version control Feature Request

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#164]
Hello, 

As I see that the most important file on exe is the contentv3.xml it would be nice if we could create a version files and then decide which version of the elp we would like to open.

When we have a lot of .elp content files sometimes we need to control the version of the content using different software, that's why I think it would be nice to see an integrated version control feature ;)

**Comment by ignaciogros** [comment]
Hi, @antton.

@JuanCasanovaSdweb (Sdweb) will work on the autosave, which is related to the versions.

A question: What about the attachments? The XML file includes the names/paths, but not the files themselves. Should each version have its files in a folder (that could make the packages too heavy)? Any ideas?

Thanks.

**Comment by antton** [comment]
You are right!! I forgot about the attachments :D 

So it would be nice an option to in git. Every save could be a commit on a project and then we can decide which one we would like to use.

Any other crazy idea ;)

**Comment by ignaciogros** [comment]
eXe's code will probably be renewed soon. All this should be part of that new version.
