### ISSUE TITLE
Epub cover and title (Feature Request)

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#166]
Hi, 

It would be nice to have an interactive panel before saving the elp as epub asking for a Title and picture for the cover, or even a general option for this part, otherwise It would take the first image that the elp has, letting the exportation a bit strange.

Thanks!

**Comment by antton** [comment]
I think my petition is similar to #110

;)

**Comment by ignaciogros** [comment]
Yes, but your idea is good (asking before saving)! I include it in #110. Thanks!
