### ISSUE TITLE
Editor version preferences lost

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#168]
Hello, 

Everytime I save my elp project with tinymce3, when I reopen the elp the editor version is changed onto default tinymce4. 

I think it's a bug, otherwise I don't understand where I need to change it, but IMHO it should be a preference of the .elp (I think that is as I said, even if I don't get it working properly)

Cheers!

**Comment by antton** [comment]
I don't know why but when I change more options than the editor it start working properly.

Anyway I will continue checking it.

And I close the issue.

Thanks!

**Comment by ignaciogros** [comment]
Thanks, @antton.

Changing only the editor version works for me. Please give us more details if it keeps failing.
