### ISSUE TITLE
ie6 and ie7 hack causes warnings in all other browsers

### ISSUE THREAD

**Issue by videophonegeek** [exelearning/iteexe#17]
base.css
62: .js #main .iDevice_hint_title{font-size:1em;margin-top:0;font-weight:normal;margin-top:1em}/* IE6, IE7 */

68: .iDevice_answer{overflow:hidden;*margin:1.5em 0}/* IE6, IE7 */

content.css
81: .iDevice_content{*zoom:1}/* IE6/7: Trigger hasLayout and contain floats */

Is this necessary anymore?

**Comment by ignaciogros** [comment]
Hi.

Thanks for your comment. It's not "necessary", but it's not a problem for the modern browsers, and as long as some users are still using those really old browsers... We'll revise that in the future anyway.

Please tell us if you find more problems.

**Comment by ignaciogros** [comment]
We'll revise that in the future, when there's no need to keep that compatibility anymore.

Thanks, videophonegeek.
