### ISSUE TITLE
Borrado de vídeo embebido de youtube

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#170]
Inserto un vídeo mediante url de youtube. Le asigno licencia CC by.
Guardo
Edito el contenido, selecciono el vídeo, clic en botón insertar medio embebido, cambio la licencia y aceptar. Desaparece el vídeo (hay que hacer dos veces en aceptar para que desaparezca la ventana.

**Comment by ignaciogros** [comment]
Fallaba antes, pero creo que en la 2.1.2 está resuelto. He probado con Firefox y Chrome.

Adjunto vídeo. **¿Sigo bien los pasos?** 

Gracias.

[bug_170_test.zip](https://github.com/exelearning/iteexe/files/890680/bug_170_test.zip)

**Comment by ignaciogros** [comment]
Creo que está resuelto. He probado con Firefox y Chrome. Cierro.
