### ISSUE TITLE
No funciona la alineación de un iframe

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#177]
Introduzco un vídeo de you tube, con la plantilla base, selecciono y marco centrar.
No hace nada

**Comment by ignaciogros** [comment]
Marco como FR porque es el comportamiento que tiene TinyMCE. Podemos hacer se se centre cuando no hay nada más en el contenedor (en el párrafo), pero tal vez sea mejor esperar a que TinyMCE lo gestione. ¿Qué te parece, Antonio?

De momento, la solución es la que había hasta ahora: centrar el párrafo en el que se encuentra el IFRAME.

**Comment by ignaciogros** [comment]
Acabo de actualizar a la 4.6.1, donde sigue fallando.

Abro incidencia en TinyMCE: https://github.com/tinymce/tinymce/issues/3665 

Mantengo esta petición abierta para comprobarlo tras la próxima actualización.

**Comment by ignaciogros** [comment]
Cierro la petición. Podemos usar las opciones de alineación del editor. En cualquier caso, no se modifica el comportamiento de alineación por defecto de TinyMCE. Tal vez la próxima versión tenga el comportamiento esperado.
