### ISSUE TITLE
Problema con la descarga de la 2.1.2 portable para Linux

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#179]
No se si es algo puntual pero hoy la descarga me baja un archivo de 40 KB.

El enlace manda a http://cedec.educalab.es/es/docman/doc_download/211-gnulinux-212-portable

Gracias

**Comment by ignaciogros** [comment]
¡Gracias, una vez más, por los avisos, @Rafav!

**Comment by Rafav** [comment]
De nada, pero el enlace sigue apuntando al mismo sitio ;)

**Comment by miguelpereiraite** [comment]
Buenos días. 
Creo que ya está correcto. Disculpas. Habíamos subido el archivo pero creo que no lo habíamos superpuesto al anterior. 
Y gracias, claro. Y disculpas, claro.

**Comment by Rafav** [comment]
Gracias.
