### ISSUE TITLE
Se desaparecen las imagenes de Exelerning

### ISSUE THREAD

**Issue by alexredondosk8** [exelearning/iteexe#180]
Buen día, estoy trabajando dentro de un div.exe-fx exe-paginated, y cuando edito las imagenes desaparecen, alguien sabe la razon ?
![captura1](https://cloud.githubusercontent.com/assets/20307190/25188508/eb68d30c-24eb-11e7-8955-f809aab35eac.PNG)

**Comment by ignaciogros** [comment]
Hola @alexredondosk8:

He probado en Windows + Chrome (creo que es lo que estás usando, ¿no?) y ha funcionado bien. Por favor, ¿puedes decirnos qué pasos seguir?

Muchas gracias.

**Comment by ignaciogros** [comment]
Sigo sin poder reproducir el fallo. Cierro, al menos de momento.
