### ISSUE TITLE
Problemas al incluir archivos con caracteres especiales

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#182]
Hola:

Cuando se quiere insertar un archivo con caracteres como Ω o ɸ estos se guardan sin nombre. Al guardar el elp veremos que tenemos archivos llamados ".jpg" ,".jpg.1"....

El problema viene cuando lo queremos subir a Agrega (y creo que pasará lo mismo en Procomún) A la hora de proponerlo da error de validación:  Error en la estructura del fichero imsmanifest

¿Se podría alertar al usuario?

Saludos

**Comment by JuanCasanovaSdweb** [comment]
Hola @Rafav,

No somos capaces de replicar este comportamiento, al añadir los archivos al ELP, se sustituyen estos caracteres, pero no se eliminan.

¿Qué SO/navegador estás utilizando?

¿Podrías enviarnos un ejemplo de ELP con este problema?

**Comment by Rafav** [comment]
Hola:

Lo he creado con la portable-intef-exe-2.1.2 en Ubuntu 16.04

El ejemplo está en: https://www.dropbox.com/s/ysqtwrn3zi7hgl6/omega.elp?dl=0
