### ISSUE TITLE
FR: Simplify eXe

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#183]
1. Create different views (Simple (default)/Advanced).
2. Make an easy to read help or assistant.
3. Validate before exporting to show warnings like: "Your project has no title. Do you wan to add it now?".
4. Create a template system so the user can open an existing template ("Project Based Learning", etc.) or create a new one using "Save as template" or a similar option.

We'll use the "simple" branch for development.

**Comment by ignaciogros** [comment]
**Step 1/4:**

Commits 8b74627bb47b17ab080175a5ea64b8d776c76f73 and 591dc0dbfcb4d8c838976bcc699ab7da23eb51a4

You can also test it replacing a few files in your own eXe (2.1.2). See the attachment:

[exelearning_2-1-2_simple.zip](https://github.com/exelearning/iteexe/files/963683/exelearning_2-1-2_simple.zip)

**Comment by ignaciogros** [comment]
**Step 2/4:**

Commits 16897e8f5feb03c0cf1946bd2d3ef97a77ddbb6e and ac10a2a0af019a660d35c7c09b69c6f7e7b8f85b

You can also test it replacing a few files and adding the **tools/assistant** folder in your own eXe (2.1.2). See the attachment:

[exelearning_2-1-2_simple_2.zip](https://github.com/exelearning/iteexe/files/970052/exelearning_2-1-2_simple_2.zip)

It'll be in Spanish only until the final contents are ready.

**Comment by ignaciogros** [comment]
The contents are ready, but in Spanish. 

**2 attachments:** The files to test the assistant in eXe 2.1.2 and the texts in Spanish. 

**To do** (apart from steps 3 and 4):

1. Translate those texts into English. 
2. Use eXe's i18n mechanism so they can be translated to other languages. 

The Spanish version will have the attached texts (they've been reviewed by the CeDeC).

[exelearning_2-1-2_simple_3.zip](https://github.com/exelearning/iteexe/files/995800/exelearning_2-1-2_simple_3.zip)
[assistant_es.txt](https://github.com/exelearning/iteexe/files/995801/assistant_es.txt)

**Comment by jrfern** [comment]
Mailed the translation into English to @ignaciogros on May 27th.

**Comment by ignaciogros** [comment]
Thanks a lot, Juan Rafael!

**Comment by ignaciogros** [comment]
Assigned to @JuanCasanovaSdweb (steps 3 and 4).

Please tell me if I can help with those steps.

**Comment by ignaciogros** [comment]
eXe's current version already has that.
