### ISSUE TITLE
selecting image on Chrome 58 bug (won't select image) on Tinymce

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#185]
Hi,

We are having this strange problem with last chrome version.

As I see there is already a bugfix here: https://github.com/tinymce/tinymce/commit/d6cbf39cd8572c90cef839a8fe4260b23b5fb639

Could you update the tinymce 3 version to fix it?

I didn't try on tinymce 4 if the problem persist or is the same.

Cheers!

**Comment by ignaciogros** [comment]
Thanks, @antton.

**Comment by ignaciogros** [comment]
Will fix that and other problems, like [this one](https://github.com/tinymce/tinymce/issues/3620), upgrading TinyMCE to the latest version (currently 4.6).

**Comment by ignaciogros** [comment]
Hi, @antton.

We just upgraded from 4.3.13 to 4.6.1. Could you test check if that works in https://www.tinymce.com/?

If it does, this issue can be closed.

Thanks!

**Comment by antton** [comment]
Hi @ignaciogros 

As the changelog of tinymce project mentions the bug has been fixed with the 4.6 version so we can close this issue.

Thanks!!
