### ISSUE TITLE
Apertura doble clic archivo exe incorrecta

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#19]
[pruebas.zip](https://github.com/exelearning/iteexe/files/160960/pruebas.zip)
Creo un archivo de muestra desde la 2.1 instalada en w7
Extraigo el nodo llamado b al escritorio.
Hago doble clic sobre b.elp y obtengo la respuesta de error 404 no such error resource b. Try again clic exe...

**Comment by pedropena** [comment]
I can't reproduce the problem. When double clicking b.elp, the package is opened without problem.

Which version of windows and browser are you using?

**Comment by antoniomonjef** [comment]
w7 & chrome
I'll make a screencast
regards

**Comment by antoniomonjef** [comment]
https://www.youtube.com/watch?v=_i34ogerQ3s
Una vez abierto a.elp, se intenta lanzar b.elp y da el error

**Comment by pedropena** [comment]
Ok. Es con eXe abierto en a.elp.

**Comment by antoniomonjef** [comment]
Me he dado cuenta que cuando está abierto un elp, al hacer docle clic en otro diferente también me da error en la apertura del segundo...
