### ISSUE TITLE
MathJax CDN shut down

### ISSUE THREAD

**Issue by JuanCasanovaSdweb** [exelearning/iteexe#191]
By [this announcement](https://www.mathjax.org/cdn-shutting-down/), it seem like MathJax own CDN is shutting down (in fact, it has already been shut down).

It keeps working fine because the have a redirection in the old CDN but we should update eXe to use one of the other free CDNs.

The only reference to the CDN I can find is this: https://github.com/exelearning/iteexe/blob/d1952420b8a23e3acea6fbac1d9072ffdb1acf47/exe/webui/scripts/common.js#L209

I will change this in a bit, but maybe I'm forgetting something else?

**Comment by ignaciogros** [comment]
Hi, Juan.

I didn't know that. Thanks!

Why did you reopen?

**Comment by JuanCasanovaSdweb** [comment]
Ups, I didn't want to ;)
