### ISSUE TITLE
The Preferences window might need some visual improvements

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#196]
Just checked the preferences window in Spanish and English, after the addition of the new option "Always force editable exports..." (by the way, what's the justification for this option?). I'm afraid in both instances the alignment and spacing could be improved. CSS work, @ignaciogros ?

I tried to enclose two .png screenshots, but I couldn't.

**Comment by ignaciogros** [comment]
Thanks, @jrfern.

Some users asked for that. Having that enabled is specially useful if you create many contents. You might loose the elp, and recovering the content is easier that way.
