### ISSUE TITLE
No se selecciona una imagen

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#197]
Se inserta una imagen y después de guardada al intentar seleccionarla, esta no se selecciona
Ubuntu 14.04, Chrome Versión 58.0.3029.110 (64-bit)

**Comment by ignaciogros** [comment]
Gracias, Antonio.

Era un problema de TinyMCE. Creo que queda resuelto tras su actualización. Por si quieres probarlo: https://github.com/exelearning/iteexe/issues/153#issuecomment-304255745
