### ISSUE TITLE
eXe no longer loads on my MacBook 

### ISSUE THREAD

**Issue by RobPrimhak** [exelearning/iteexe#200]
Using a MacBook air with Sierra 10.12.5.
I developed a tutorial package on eXe which worked fine.  Recently tried to open it for editing and it did not load.  Opening the eXe app generates an icon in the dock, but no program in the browser.  I tried removing and reinstalling eXe without benefit.   Any suggestions please?

**Comment by JuanCasanovaSdweb** [comment]
Hi @RobPrimhak 

We have recently made a patch to solve this issue (which is due to a bug in Sierra), but this version hasn't been released yet.

You can try to open eXe and then go this URL on your browser: http://localhost:51235/

Let me know if that works.

**Comment by RobPrimhak** [comment]
Thanks for quick reply.  No- that just gave me the attached window:

If a patch is on its way, then I am less panicky about it!  We are using eXe to train paediatricians to construct effective exam questions, and still fine-tuning the package after launch.

Thanks again.   Could you let me know when the next version is released?


Rob Primhak


> On 22 Jun 2017, at 11:07, Juan Casanova <notifications@github.com> wrote:
> 
Hi @RobPrimhak <https://github.com/robprimhak>
We have recently made a patch to solve this issue (which is due to a bug in Sierra), but this version hasn't been released yet.

You can try to open eXe and then go this URL on your browser: http://localhost:51235/ <http://localhost:51235/>
Let me know if that works

**Comment by JuanCasanovaSdweb** [comment]
I can't see any attachment.

Anyway, if you don't mind waiting the new version should be released in no time.

You can watch this repository to receive a notification when a new release is launched.

**Comment by RobPrimhak** [comment]
OK- thanks very much

Rob Primhak
45 Whiteley Wood Road
Sheffield
S11 7FF
UK
07885 888714
