### ISSUE TITLE
Problem with Wiki idevice

### ISSUE THREAD

**Issue by ingodahn** [exelearning/iteexe#202]
I try to receive the German Wiki page https://de.wikipedia.org/wiki/Ungleichung_vom_arithmetischen_und_geometrischen_Mittel in a wikipedia idevide. Clicking on "Load" either leads to infinite loading or produces the attached error.
![wikierror](https://user-images.githubusercontent.com/3258024/27831468-23439b8e-60cb-11e7-8e06-27287b44b5a5.png)

**Comment by jrfern** [comment]
I confirm there's something wrong. Using the development version it takes a long time (two or three minutes) to load/copy the wikipedia page, but the images are lost (I get the alt-texts). Ignacio, could you take a look, please?

![captura de pantalla de 2017-07-06 19-25-43](https://user-images.githubusercontent.com/3305693/27924446-9bba738c-6281-11e7-9c83-bd5c68d72c66.png)

![captura de pantalla de 2017-07-06 19-26-25](https://user-images.githubusercontent.com/3305693/27924452-a16d4ad4-6281-11e7-9d17-fe531901b583.png)

**Comment by JuanCasanovaSdweb** [comment]
@ingodahn's error has been prevented.

@jrfern: We can do nothing about slowness, it is due to the amount of images in this wikipedia page (every math formula is a svg image), but we did fix the issue with the images not loading.
