### ISSUE TITLE
Export - Web Site - Zip File is not working

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#204]
Install the attached Style and try this: Export - Web Site - Zip File 

It will export eXe's default Style instead of SICE SNAP.

[SICE-SNAP.zip](https://github.com/exelearning/iteexe/files/1135887/SICE-SNAP.zip)

See http://exelearning.net/forums/topic/no-exporta-el-tema-elegido/ if you need more information.

**Comment by JuanCasanovaSdweb** [comment]
This is actually a CSS problem.

"nav.css" is overwriting the styles defined in "content.css".

We could make "content.css" have more weight than "nav.css" (which may make sense), but that doesn't solve the problem, as there are some properties not defined in "content.css" (for example the #nodeTitle element is absolutely positioned which makes it appear over the background).

I'm assigning this to you @ignaciogros. Let me know if you need something!

**Comment by ignaciogros** [comment]
I didn't see that. It's not a bug then. Thanks, Juan!
