### ISSUE TITLE
Wrong language selection (when choosing Chinese)

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#205]
Reported by Franklin Weng:

Click on the 'Properties' tab. Choose 'Chinese' and 'Save'.

The button of the page is in Simplified Chinese even if you select zh_TW.

See the attachments: [language_selection_problem.zip](https://github.com/exelearning/iteexe/files/1141773/language_selection_problem.zip)

Could you check that?

Thanks.

**Comment by jrfern** [comment]
My first thoughts.

1.) First of all, I think a previous step should be taken. I've always though that all the compressed js code should come along uncompressed versions of the files, so that we humans could read them. There's an increasing number of files that can't be read or analyzed, and I would like to check that both versions of Chinese are supported throughout.

2.) A further problem is that we need linguistic help, we can't tell if the interface is in Traditional or Simplified Chinese.

 I'll keep out studying the problem.

**Comment by jrfern** [comment]
3.) I see the languages supported in tinymce3 in tinymce_3.5.11_settings.js. No Chinese version was supported in eXe so far. Where is the language configuration in tinymce4? Do anyone know how to add Traditional Chinese support? Does the system work just as is?

**Comment by ignaciogros** [comment]
Hi, @jrfern.

I can only answer these questions (I hope that @JuanCasanovaSdweb will check the others):

> 1.) First of all, I think a previous step should be taken. I've always though that all the compressed js code should come along uncompressed versions of the files, so that we humans could read them. There's an increasing number of files that can't be read or analyzed, and I would like to check that both versions of Chinese are supported throughout.

eXe's files are not minified. TinyMCE plugins are, but that is not a problem, because their strings are in /scripts/tinymce_4/js/tinymce/langs/all.js.

TinyMCE 3's i18n files are minified (/scripts/tinymce_3.5.11/jscripts/tiny_mce/langs/en.js, etc.).

Which files would you like to make easier to read?

"tinyMCE_languages" is only for the "Insert Predefined Template Content" option in TinyMCE (so the name of the templates can be translated, which is not really important, as they are called '2 cols - 50% 50%' and things like that). The translation mechanism will work in the rest of the cases, so no revision of the JS files should be necessary. 

Please tell me if any string is not translated (I'll need the string in English, the selected language and where to see the untranslated string in eXe).

> 3.) I see the languages supported in tinymce3 in tinymce_3.5.11_settings.js. No Chinese version was supported in eXe so far. Where is the language configuration in tinymce4? Does anyone know how to add Traditional Chinese support? Does the system work just as is?

tinymce_4_settings.js, line 32, sets the language ("all"). The "all.js" files have the strings for all the languages (they use the _ function). Most plugins (all but one: ABC Music Notation) use the _ function in their "plugin.min.js" file instead of having the strings in an external file ("all.js"). That makes development and maintenance easier. 

The Traditional Chinese translation should work just adding the new language to eXe and translating the strings.

**Comment by jrfern** [comment]
> The Traditional Chinese translation should work just adding the new language to eXe and translating the strings.

It is included as zh_TW and it's translated. The bug report is that you can't really choose zh_TW, all you get is zh_CN (Simplified Chinese), at least for the interface, that's what we're talking about.

> eXe's files are not minified

mediaelement/exe_media.js is minified. Inside it I find «zh:"Chinese","zh-cn":"Chinese Simplified","zh-tw":"Chinese Traditional"» but I can't read the logic, it has nothing to do with the translation strings.

> tinymce_4_settings.js, line 32, sets the language ("all").

That's perfect. 

We need answers for the other questions.

**Comment by ignaciogros** [comment]
Thanks, @jrfern!

@JuanCasanovaSdweb?

**Comment by JuanCasanovaSdweb** [comment]
Ok I think I'm lost. You are talking about translations but for what I can understand from the attachments, isn't the problem that you cannot select _Traditional chinese_ on the package properties page?

In eXe preferences page it is already possible to select either of that languages, isn't it? (My chinese is very limited, so i can't tell if there is any problem with any of them ;)).

About this:
> 5.) In wikipediablock.py we don't have the option for Traditional Chinese

There are a lot of languages that are missing from that iDevice, I guess it's so the select list won't be that big. It's very easy to add a new language here, but should we add all the languages available on eXe (Maybe it will be better to open a new issue with this).

**Comment by ignaciogros** [comment]
Hi, @JuanCasanovaSdweb.

> There are a lot of languages that are missing from that iDevice [Wikipedia], I guess it's so the select list won't be that big. It's very easy to add a new language here, but should we add all the languages available on eXe (Maybe it will be better to open a new issue with this).

I think that a new ticket will be better. The iDevice should display all the available languages using dynamic list. 

**About this issue:**

See zh_TW.js and zh_CN.js. The original string is in English, so you can check which language is selected. This is what @jrfern says:

> The bug report is that you can't really choose zh_TW, all you get is zh_CN (Simplified Chinese), at least for the interface, that's what we're talking about.

**Comment by jrfern** [comment]
Gracias por las respuestas. No sé si tiene sentido romper en distintos tickets lo que tiene una unidad evidente y múltiples interrelaciones. De lo que estamos hablando es de que, aunque el usuario elija Chino tradicional en Preferencias, lo que ve es Chino simplificado. Y eso ocurre o puede ocurrir en varios sitios (interfaz, editor, wikipedia...) que los que no conocemos chino no somos capaces de identificar fácilmente.

Sobre el iDevice wikipedia: deberíamos ofrecer las lenguas que "soportamos", aquellas 12-15 para las que tenemos una traducción más o menos completa y actualizada. Incluso como preferencias, queda muy pretencioso ofrecer muchas para que luego la interfaz salga en inglés.

Y volviendo al tema, tenemos traducción actualizada para chino tradicional, y no para simplificado, por lo que entiendo la queja de los traductores chinos.

Nadie ha respondido al punto 4.

**Comment by ignaciogros** [comment]
Gracias, @jrfern 

> 4.) In jsui/langs.js (used by the Authoring page) we only have "Chinese". We should have "Chinese (simplified)" and "Traditional Chinese (Taiwan)", I think, as zh_CN and zh_TW. I can patch the file myself, but I don't know the consequences.

He's right. We should have all those files. I think that having them translated should solve the problem. I don't know why are there missing. @JuanCasanovaSdweb?

> Sobre el iDevice wikipedia: deberíamos ofrecer las lenguas que "soportamos", aquellas 12-15 para las que tenemos una traducción más o menos completa y actualizada.

I think that the Wikipedia iDevice should offer any language available in Wikipedia (https://en.wikipedia.org/wiki/List_of_Wikipedias).

Updating that list is easy. Maintaining it may be not.  Could we update that list without new strings, @JuanCasanovaSdweb? How about a new ticket for this?

Thanks!

**Comment by jrfern** [comment]
After spending some time reading the wikipedia explanations (mainly https://meta.wikimedia.org/wiki/Automatic_conversion_between_simplified_and_traditional_Chinese), I have come to the conclusion that the wikipedia problem is a non-issue: there's only a ZH page, and the writing system is chosen programmatically. So point 5) can be considered solved.

Point 4) remains open.

**Comment by fweng322** [comment]
Hi,

Wikipedia auto conversion should only be applied when either one missing.  For example, if a page only contains Simplified Chinese, then when user clicks Traditional Chinese tab it will be auto converted word by word.

For the bug I reported (for a user) is when creating a new page in eXe.  When it was just created everything is still okay and the label on the button is correct.  However as long as we get into the properties we don't even need to do anything, and the page will be set to Chinese and becomes Simplified Chinese.  That's why I suspect if the properties of newly created page contains only "zh" not "zh_TW" as the eXeLearning UI setting.  If "zh" locale exists it will be used with higher priority and ignored zh_TW or zh_CN.  And almost all the software including browser will treat zh as zh_CN if no translations for zh exists.

I hope it can help you clarify more.  If any problem with Simplified and Traditional Chinese feel free to ask me.

**Comment by BorjaVarelaSdweb** [comment]
Hi,
> 4.) In jsui/langs.js (used by the Authoring page) we only have "Chinese". We should have "Chinese (simplified)" and "Traditional Chinese (Taiwan)", I think, as zh_CN and zh_TW. I can patch the file myself, but I don't know the consequences.

If you add in that file the two types of Chinese, Simplified Chinese and Traditional Chinese, would already appear in the package preferences to select.
> However as long as we get into the properties we don't even need to do anything, and the page will be set to Chinese and becomes Simplified Chinese. 

This error after having changed the file has not appeared to me.
If there are any more comments

**Comment by fweng322** [comment]
Please see the desktop recording video:

https://youtu.be/DfgHY9YuGFs

at 0:30 the "Next" button in the preview is still in Traditional Chinese.  At 0:50 you can see only one 中文
 (Chinese) can be selected.  Then after saving the properties (sorry I gave the wrong information) and preview again (1:30), it became Simplified Chinese.

If you still need any more clues please tell me.

**Comment by JuanCasanovaSdweb** [comment]
As it's possible to select both languages now in the package properties page, this should be fixed now.

@fweng322 Seems ok to me, but could you please confirm it?

Thanks!

**Comment by fweng322** [comment]
@JuanCasanovaSdweb  Anywhere to download the new beta version for me to test?  Or should I setup it from github?

**Comment by JuanCasanovaSdweb** [comment]
Right! Sorry!

You can download it directly from our GitHub release: https://github.com/exelearning/iteexe/releases/tag/2.1.3-beta2

**Comment by fweng322** [comment]
@JuanCasanovaSdweb 

https://imgur.com/XnFueNn : The original option is still there (might be "Chinese" only) and the behavior is not expected.

https://imgur.com/pRJiHFr : When selecting "Traditional Chinese" **it worked correctly**.

Thank you very much for your effort!

**Comment by JuanCasanovaSdweb** [comment]
Do you mean that by default, even with Traditional Chinese selected as eXe's main language, in this page "Chinese" is selected by default (instead of Traditional Chinese)?

Am I understanding that right?

**Comment by fweng322** [comment]
Right.  That's what I've seen.  I need to explicitly specify Traditional Chinese to make things right.  When creating a new page, the language attribute is still "中文" (Chinese) not "Traditional Chinese".
