### ISSUE TITLE
Feature request: Converting from old versions

### ISSUE THREAD

**Issue by ingodahn** [exelearning/iteexe#206]
Recently I had to modify an elp file produced in 2014, but the current exe refused to open it (wrong file format). I solved this case by rewriting the elp from scratch based on the yet existing html export.
However, for a sustainable use in the future, it would be very helpful if either

- future versions of exe are backwards compatible or
- there is an online conversion service to update the data format or
- there are guidelines how to manually update an elp package

**Comment by ignaciogros** [comment]
Could you attach the old elp, please? Old packages should be editable with the new versions.

Thanks, ingodahn.

**Comment by ingodahn** [comment]
Attached is the old elp - I had to zip it additionally, as GitHub doesn't support upload of elp files. eXe 2.1.2 says "Sorry, wrong file format"
[Formelsammlung.zip](https://github.com/exelearning/iteexe/files/1172365/Formelsammlung.zip)

**Comment by ignaciogros** [comment]
Thanks, @ingodahn.

@JuanCasanovaSdweb:

I can't open it with 'master' neither. Could you check that, please? Thanks...

**Comment by jrfern** [comment]
Master here too. Error message:

> IndexError:  list index out of range

The .elp contains three files: content.data, content.xsd and contentv2.xml.

**Comment by ignaciogros** [comment]
I think that this is a bug, not a FR. You can edit that elp if you change the name of the XML file from contentv2 to contentv3. All files created with eXe should be editable with a later version.
