### ISSUE TITLE
ISO format file and directory naming

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#208]
New advanced export preference: File and directory naming. 

A SELECT with two options (Default / ISO 9660: 8+3)?

File and directory naming convention: 8 characters, a period, and 3 more characters.

This was suggested by Ismail Ali Gago.

**Important:** 

- If the HTML files extension has to change to htm, all Styles should be reviewed, because the JS files (_style_js, etc.) use the ".html" to check if the menu is hidden when loading a new page (we add 'nav=false' to the links when hiding the menu).
- If it has to change, I think that we should keep ".html" as the default extension. Do you agree?

Please let me know I you want me to check the Styles.

**Comment by JuanCasanovaSdweb** [comment]
I have just pushed a commit with the first change (I will do another one with the resources' name cut later).

The styles' JS you mention seem pretty easy to fix. Just changing this line should be enough: https://github.com/exelearning/iteexe/blob/master/exe/webui/style/INTEF/my_js.js#L60

We can do it if you want no problem!

**Comment by ignaciogros** [comment]
Hi, @JuanCasanovaSdweb.

The JS files look for this string ".html?" in `window.location.href` to check if the menu is hidden or not. They should look for ".htm?" as well (both cases should work). That should be done in all the Styles with that functionality, including Base, which is used to create new Styles.

**Please do that if you can.** I won't have time to do that today, and we're supposed to start the tests as soon as possible.

Thank you.
