### ISSUE TITLE
version online de exelearning

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#21]
Buenas, 

No se como esta la versión de exelearning online actualmente o si existe alguna documentación para intentar instalarlo. El tema es el siguiente. Mirando en github ayer encontré que la universidad técnica de  munich tiene una versión antigua de exelearning portada a django via web.

Se puede testear en esta url: creyoco.com

A su vez se puede mirar el código en este repositorio https://github.com/TUM-MZ/creyoco

Simplemente para tomar ideas puede ser una opción interesante.

Saludos

**Comment by antoniomonjef** [comment]
Hola Antton:
Te he mandado un mail.
He entrado y hay cosas que me gustan mucho. Es muy interesante para tomar ideas de interfaz
Gracias

**Comment by ignaciogros** [comment]
Hola.

Cierro esta petición. La primera versión de eXe online estará disponible dentro de unos meses. Muchas gracias por compartirlo, @antton. Se pueden sacar muy buenas ideas de ahí.
