### ISSUE TITLE
Uninstaller problem

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#211]
uninstall.exe (in eXe 2.1.3) provokes a warning from Windows 7:

![uninstall_problem](https://user-images.githubusercontent.com/2928868/29913332-2931cefc-8e35-11e7-8abb-1c2850517b31.gif)

You can uninstall eXe anyway, but...

**Comment by JuanCasanovaSdweb** [comment]
Hi @ignaciogros,
What architecture do you use? We have been trying to replicate the fail by using a 32bits Windows but it didn't happen.

**Comment by ignaciogros** [comment]
Windows 7 Home Premium 64-bit SP 1.

Just in case it's got something to do with this: eXe's installed in a partition. It's not were Windows is.

**Comment by JuanCasanovaSdweb** [comment]
We have issues reproducing this, so I willl mark it as FR and we will try to find the problem before the next version.

**Comment by ignaciogros** [comment]
I had no problems uninstalling 2.1.3~beta2.
