### ISSUE TITLE
TinyMCE plugin Spanish translation

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#213]
'Footer caption' is translated as 'Pie de la imagen', but that string is used in the media plugin too (to add videos, audios...). We can keep 'Pie de la imagen' or change it to 'Pie', so it fits in all cases. It's not important...

Thanks.

**Comment by jrfern** [comment]
As a matter of fact I'm reading Damasio, the neurophysiologist, at the moment. He says that images can be visual, but also auditive, somatic, even verbal... but as we are not going to demand the users to read Damasio, I'll accept the ticket and the proposal to translate it as "Pie". Which is also an image ;-)
