### ISSUE TITLE
recuperar proyecto

### ISSUE THREAD

**Issue by Santidguez** [exelearning/iteexe#215]
Al intentar recuperar una carpeta autocomprimida (previamente comprimido) sale "formato de archivo incorrecto".

**Comment by ignaciogros** [comment]
¿Puedes adjuntar el zip y decirnos con qué versión de eXe la exportaste? Muchas gracias.

**Comment by Santidguez** [comment]
Hola:
No recuerdo la versión de exe porque hace tiempo que lo hice (2012 o 20139.
Os adjunto enlace a la carpeta zip
https://drive.google.com/open?id=0BwcrXKspnDTfYVpMb1VyaXFzNjQ
Muchas gracias

2017-09-08 13:50 GMT+02:00 Ignacio Gros <notifications@github.com>:

**Comment by Santidguez** [comment]
Hola:
No recuerdo la versión de exe porque hace tiempo que lo hice (2012 o 20139.
Os adjunto enlace a la carpeta zip
https://drive.google.com/open?id=0BwcrXKspnDTfYVpMb1VyaXFzNjQ
Muchas gracias
 Pdta:¿Podrian confirmarme que les ha llegado ese correo?

2017-09-08 13:50 GMT+02:00 Ignacio Gros <notifications@github.com>:

**Comment by ignaciogros** [comment]
Hola @Santidguez.

Siento haber tardado en contestar. No he podido recuperarlo para editarlo con eXe porque el exportado no es editable (no contiene estos ficheros: content.data, content.xsd, contentv3.xml). Para que sea editable tienes que tener marcada la casilla '¿Crear un exportado editable?' en Propiedades - Exportar.

Lo que sí he podido hacer es recuperar la página principal (index.html). Si descomprimes el zip verás que hay un fichero llamado index.html y otro llamado index(1).html. A este último debes llamarle index.html. Ese problema se debe, probablemente, a que has adjuntado un archivo llamado index.html. Es un problema conocido que se resolverá lo antes posible.

Cierro la incidencia por no ser un fallo de eXe. **Muchas gracias por el aviso.** Espero que puedas recuperar los contenidos de los ficheros HTML.

**Comment by Santidguez** [comment]
Muchas gracias
