### ISSUE TITLE
Untranslated strings in the Preferences panel

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#219]
Check this preference in Spanish: "Forzar exportaciones editables al cargar el paquete".

The options are in English. 

A checkbox will solve that too without new strings. Will that be better?

**Comment by jrfern** [comment]
There are no checkboxes in that tab, I'd prefer the options. Maybe "Enable" and "Disable" are already included in the translation memories, please internationalize the strings and we will see.

**Comment by ignaciogros** [comment]
Thanks, @jrfern. 

I used 'Yes' and 'No' so there are no new strings. Is that OK?

@JuanCasanovaSdweb: Please check if the strings do what they say and reopen if not. I don't know how that preference works. I sent you an email.

Thanks...
