### ISSUE TITLE
Preferences window. Some texts are cut.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#220]
Some texts are cut in the Preferences window (click on the 'Show information' button of ''Naming standard for exported content' is translated', for example).

We can just make the window bigger, refresh the layout when the text is shown or find a different way to display those messages.

By the way:

Should that preference be there or should it be in Properties - Export?

Thanks.

**Comment by ignaciogros** [comment]
**This might be important**, because the new preference is hidden until you click on any of the info buttons.

**Comment by jrfern** [comment]
As an Export option, it might go in Properties - Export.
