### ISSUE TITLE
2.1.3 does not work in Fedora

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#223]
Reported by a tester (test #2): 

Error while loading builtin filter module 'webassets.filter.rjsmin': cannot import name rjsmin '

**Comment by ignaciogros** [comment]
Read this before: http://exelearning.net/forums/topic/instrucciones-para-instalar-exelearning-en-fedora-25/

**Comment by JuanCasanovaSdweb** [comment]
I think we can close this now. The problems with Fedora 26 could not be replicated and the user has not yet responded.
We will open a new issue if there is new information.
