### ISSUE TITLE
Missing images in 2.1.3

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#224]
**This is important.**

Some users have reported that some images are missing when trying to edit an elp created with the previous version (2.1.2).

Please contact Cedec or the user that filled in test #6 if you can't reproduce that.

**Comment by Rafav** [comment]
Also with elps created with 2.0.4

**Comment by ignaciogros** [comment]
More testers have reported this problem. This issue is critical. eXe 2.1.3 can't be released until it's fixed.
