### ISSUE TITLE
Conexión con localhost no posible

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#23]
Sobre w7, firefox.
Se ejecuta exelearning y se deja el ordenador sin actividad. Salta la protección de pantalla y después el sistema (portátil) se queda como hibernado... para que se reestablezca se pulsa el botón on of y sale y enciende la pantalla. A partis de ese momento no logra conectarse con el servidor. Incluso si lanzamos otra instancia de exelearning (doble clic sobre el icono de escritorio) exe no llega a lanzarse.
Tengo que cerrar el navegador por completo (no sale la señal de js de abandonar pestaña) y es entonces cuando se lanza exe, perdiéndose los cambios si los hubiera del archivo con el que se estaba trabajando anteriormente

**Comment by antoniomonjef** [comment]
Observo que en w7 sobre ff45 las desconexiones se producen al cabo de un rato sin estar actuando con exelearning (sin necesidad de que salte el protector de pantalla)
¿Qué necesitarías para encontrar el error?

**Comment by pedropena** [comment]
¿Podrías probar a ver si ocurre también con Chrome?

**Comment by antoniomonjef** [comment]
1. He probado con chrome. El comportamiento es análogo en el caso de que el ordenador se quede sin actividad.
Pruebo en el segundo caso y notifico

**Comment by antoniomonjef** [comment]
2. Realizadas las pruebas en w7 con chrome (49.02), no se produce desconexión al saltar protector de pantalla. No he observado el mismo efecto que con FF

**Comment by ignaciogros** [comment]
Windows 7, con usuario administrador.

En Firefox ("C:\Program Files (x86)\Mozilla Firefox\firefox.exe") y Chrome ("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"):

- Abro eXe.
- Suspendo el equipo (Inicio - Apagar - Suspender).
- Reinicio y ya no conecta.

Con IE ("C:\Program Files\Internet Explorer\iexplore.exe") no sucede.
