### ISSUE TITLE
Mistakes in french translation

### ISSUE THREAD

**Issue by fredtempez** [exelearning/iteexe#233]
Hi, 
There are la lot of mistake in french translation but I have no right to pull new po file. Are you interested about that new file ?
Thanks

**Comment by jrfern** [comment]
Ici le coordinateur des équipes de traduction. Je dirais que la solution la plus "diplomatique" serait de contacter en privé le traducteur - c'est facile de trouver son courriel, c'est dans le header du PO français. C'est ça possible pour vous?

De toute façon je vais le contacter, en l'informant de cet "issue".

Comme traducteur moi-même je rémercie toute révision des traductions. Merci beacoup

**Comment by cybertaf** [comment]
Bonjour,

Ok je procède de cette manière.

Cordialement

**Comment by jrfern** [comment]
Sorry for forgetting to document it: @fredtempez contacted the French translator and suggested improvements to the translation, which were committed on Sept. 28th.

Therefore I'm closing #233. Of course translations are never either perfect or finished, feel free to reopen the issue or contact the translators for suggestions and improvements.  Thank you all for your voluntary work.
