### ISSUE TITLE
SyntaxHighlighter

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#234]
Hello, this is not a bug just a question.

Is anyone using any syntaxhiglihter with tinymce or inside the html contents?

Thanks for all

**Comment by ignaciogros** [comment]
Yes. eXe includes one:
- Add a TinyMCE editor.
- Click on 'Insert HTML code as text'.
- Check the 'Highlight syntax' option.

It uses [Prism](http://prismjs.com/), by Lea Verou.

Please use [the forums](http://exelearning.net/forums/) for this kind of questions. **Thank you!**

**Comment by antton** [comment]
I was talking about a higlight syntax inside the content when you make it public.

something like this https://highlightjs.org/

**Comment by ignaciogros** [comment]
That's what it does. Please see [sh_example.zip](https://github.com/exelearning/iteexe/files/1320672/sh_example.zip) and http://descargas.pntic.mec.es/cedec/manualexe2.1.1/insertar_html_como_texto.html

**Comment by antton** [comment]
Ok!
I'm gonna try it and let you know!! Thanks ;)
