### ISSUE TITLE
Add support for new language(s) in syntax highlighter

### ISSUE THREAD

**Issue by alexzandros** [exelearning/iteexe#235]
I just want to know, if is there a way ta add support to Racket or Scheme and also Haskell syntax highlighting in the editor. I'm looking at the javascript file exe_highlighter.js and it's not totally clear how to do it. I think I'm capable of doing it myself but I want a few pointers on how to start.

**Comment by ignaciogros** [comment]
Hi, @alexzandros.

eXe uses Prism, by Lea Verou. You can find information on how to extend Prism here: http://prismjs.com/extending.html

Please share your code if you think that it can be useful for other eXeLearning users.

Thank you!
