### ISSUE TITLE
FR: Hide some iDevices

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#239]
I think that the Experimental and the FPD iDevices should be hidden by default.

**Comment by BorjaVarelaSdweb** [comment]
Hi. 
I think that the Experimental and the FPD iDevices already hidden by default. 
Do you want them to appear whenever the application is opened by default, or that when it's installed they remain hidden?

**Comment by ignaciogros** [comment]
It's OK then. They should be hidden. My mistake, sorry. I close.
