### ISSUE TITLE
Problema a la hora de abrir archivos provenientes del importador HTML

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#24]
Una usuaria reporta problemas a la hora de abrir archivos provenientes del importador HTML. 

http://exelearning.net/forums/topic/formato-invalido/

Creo que es un problema que se da cuando dos archivos idénticos están utilizándose en diferentes páginas con nombres diferentes. También ocurría en ciertos archivos hechos con versiones de exe de ULHI ya que en esa versión se desactivaba la deduplicación para respetar la nomenclatura de archivos.

Nota: en la nueva versión no sale el error de formato de archivo porque se captura la excepción y se reporta la falta de archivo en el .log

**Comment by ignaciogros** [comment]
Hay problemas con los archivos idénticos con distinto nombre incluso si no provienen de una importación.

**Ejemplo:**

- Tengo dos imágenes iguales: a.jpg y b.jpg.
- Añado, en un iDevice de Texto libre, las dos imágenes, una debajo de otra.
- Voy a "Visualización previa" y compruebo que en ambos casos se usa a.jpg.
- b.jpg no está por ninguna parte: ni en el HTML ni en la carpeta exportada.

He hecho las pruebas en Windows.

**Comment by jm-andonegi** [comment]
Ese comportamiento es el que ha tenido siempre eXeLearning para minimizar el tamaño del .elp pero en algunos casos genera problemas, sobre todo si se incorporan recursos que llaman a otros archivos (html, swf, ...)

En Moodle se sigue otra estrategia: se deduplica a la hora de guardar el archivo pero se le vuelve a poner el nombre original a la hora de crear el html. De ese modo se mantiene el nombre del archivo.

**Comment by ignaciogros** [comment]
@JuanCasanovaSdweb: 

Tal vez debamos marcar esto como FR y solucionarlo permitiendo carpetas en las exportaciones tal y como se propone en https://github.com/exelearning/iteexe/issues/118. Eso solucionaría bastantes problemas.

**Comment by ignaciogros** [comment]
Cierro la incidencia. La apuesta a futuro es la creación de una interfaz para la gestión de archivos y carpetas que permita estructuras a medida. De momento, se aplicará la solución descrita en #396
