### ISSUE TITLE
Properties tab: No "Save" option

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#240]
The "Save" option at the foot of the page has disappeared, only "Clear" and "Reset" are available. By the way, it's not a translation problem. It's indifferent if I make changes on the page.

I assign the bug to @ignaciogros temporarily, to confirm.

**Comment by jrfern** [comment]
Well, I myself mechanically clicked the second button, which now triggers a Reset of all personal changes in Properties, not nice. "Save" is a feature that's been there for about 10 versions of eXe, I understand it's never been necessary, but being a frequent user means not to have to read all the messages in all the windows, doesn't it? What's the point in creating difficulties to our users?

**Comment by ignaciogros** [comment]
Could we add that button again, even if you don't have to click it to save that information, @JuanCasanovaSdweb?

Thank you.
