### ISSUE TITLE
Untranslated string: Settings Saved

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#241]
'Settings Saved' is not translated (MainTab.js). The string was already translated, but it was not present when the translators did their work some weeks ago. It's been added again. **Is there an easy way to recover it?**

**Comment by jrfern** [comment]
I can explain the issue. What we really use is mki18n.sh, a script created by Pedro Peña @pedropena . As I am not a developer, I have been extremely cautious in the changes I have introduced. I don't know why, but Pedro used 'pybabel update' with the parameter '--ignore-obsolete', so no old string are preserved in the PO files. I don't know why he did that, but I didn't dare to remove this parameter. So translated strings that are not being used in the new version are lost.

I might try and remove the parameter (info here): http://babel.pocoo.org/en/latest/cmdline.html. But the reversions, if any, might appear not in this new version, but in the next one.  What would you suggest? Shall I remove it, hoping that during these years Babel has solved the problems that made Pedro use that conservative option?

**Comment by ignaciogros** [comment]
Removing unused strings is good to keep the code clean. 

I think that we should just be careful and try not to forget using the _ function. 

Will you translate that string again, Juan Rafael? I think it's the easiest solution. 

We can also use 'Done', but 'Settings Saved' is better...

Thanks.

**Comment by jrfern** [comment]
> Removing unused strings is good to keep the code clean.

I'm afraid we'll need this sort of strings to be able to cope with the dual Traditional/Online versions thing. Strings translated for Online that have no sense in Traditional but must be kept for the next time we translate Online.

I removed experimentally the '--ignore-obsolete' parameter, let's pay attention to possible problems arising.

> I think that we should just be careful and try not to forget using the _ function.

Of course. But that does not solve the specific problem we are talking about now.

> Will you translate that string again, Juan Rafael? I think it's the easiest solution.

Last night I translated the latest PO file. Please just check the translation.

**Comment by ignaciogros** [comment]
Hi @jrfern,

I see that "Settings Saved" has been translated again. Thank you.

We can talk about the solutions in Madrid (II Jornadas del Proyecto EDIA). Maybe there's a way to keep the unused strings together in the language files. That will make the cleanup process easier.
