### ISSUE TITLE
Style Designer: Cannot save Style with jpg image (Mac)

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#246]
Reported by a tester using Mac OS Sierra 10.12.6 and Firefox 56:

Create a new Style an try to add a jpg background image in the header. The user says that the Style can't be saved, and that you can save it using a png image instead.

**Comment by JuanCasanovaSdweb** [comment]
We are not able to replicate this. It seems that the user tried it on 2.1.3~beta1, so it could be specific to that version. Will it be possible to contact him?

**Comment by ignaciogros** [comment]
It was on 2.1.3~beta1. We close if it works for you. Thanks.
