### ISSUE TITLE
Add an option to save and export at the same time

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#247]
It would be great to add an automated export option to the save command, so that:

- We could define a default export format and location (e.g.: Website and an absolute/relative path)

- We could activate the automated export option so that every save would also export the content.

**Comment by ignaciogros** [comment]
I agree. We talked about that once: A 'Publish online' option. You save your connection and eXe works as a CMS for your site. That's interesting for the online version too, so the users of a platform with eXe can edit previously published contents.

Thanks, @jm-andonegi!

**Comment by jm-andonegi** [comment]
It's specially interesting if you are working with a system that synchronises automatically your files with an web service.

I think it can be developed with this other FR: https://github.com/exelearning/iteexe/issues/167

PD: I'm doing some test with NextCloud and I think it is a great Open Source tool that can give us the same services provided by Drive, Dropbox, etc. We can even configure the tool so that it copies HTML files to a public folder in the server.
