### ISSUE TITLE
Crear nuevo estilo

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#25]
Con OSX 10.10.5 bajo Chrome.
Dice el usuario:
"cuando accedo a "Editar estilo actual", no hace nada. Y cuando accedo a crear un estilo nuevo, me da error:
<img width="758" alt="skitch" src="https://cloud.githubusercontent.com/assets/3305838/13823523/2befcda8-ebaa-11e5-9a94-67f49fbc9fc7.png">
Asigno a Ignacio pero avisamos si hay que reasignar (creo que es un error circunscrito a MAC)

**Comment by ignaciogros** [comment]
¿Podéis comprobar si al instalar en OSX se crea esa carpeta ("tools" en la ruta de instalación de eXe)?

Si no existe, el fallo es ese. 

Gracias.
