### ISSUE TITLE
Language code split on JS

### ISSUE THREAD

**Issue by JuanCasanovaSdweb** [exelearning/iteexe#250]
There are a lot of places where language code is split and only the first half of it is used. This generates a problem with certains languages (like Traditional Chinese) as it selects the "default" one instead of the specific one the user has selected.

We have introduced a fix for this specific problem (#205), but it is really necessary to do this split?

You can see an example of this in: https://github.com/exelearning/iteexe/blob/defa8ad9acbd70881170a091573a6beb5a09d53c/exe/jsui/mainpage.py#L235

Seems that was @pedropena who introduced this change in 6e8a10320feb0a3923b13045081237c73b925fc8 (5 years ago), do you remember why?

**Comment by ignaciogros** [comment]
@pedropena? Thank you!

**Comment by ignaciogros** [comment]
I think that we should close this. It's been open for 2 years now, and the related issue was closed 6 years ago. We'll reopen if needed.
