### ISSUE TITLE
Wrong file format error: is it possible to fix this file?

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#252]
A user has sent me a file that has been generated merging two packages. The result is the attached file (I have added .zip to the file name because the .elp files are not allowed ????????)

[paquete gases.elp.zip](https://github.com/exelearning/iteexe/files/1444512/paquete.gases.elp.zip)
The log file says:
"2017-11-05 23:14:59,477 exe.jsui.mainpage ERROR Error loading package "...../paquete gases.elp": 'NoneType' object has no attribute 'get_language'"

**Comment by ignaciogros** [comment]
Recovered (just change the extension from zip to elp): [paquete_gases_recuperado.zip](https://github.com/exelearning/iteexe/files/1449397/paquete_gases_recuperado.zip)

I removed the .data file and edited contentv3.xml to change the values of `<string role="key" value="lom"></string>` and `<string role="key" value="lomEs"></string>`. I just copied the values of a new elp (in Spanish).

I hope it works, @jm-andonegi.

@JuanCasanovaSdweb: Could a package be open when some of those values are missing? That user created that package using eXe, but it couldn't be open.

**Comment by jm-andonegi** [comment]
Works fine. Thanks a lot!

I think we should do a deep analysis in merge function, because we can find more problems related to data added to schema in recent versions.

**Comment by ignaciogros** [comment]
Another case: http://exelearning.net/forums/topic/formato-incorrecto/

Thanks, Juan.

**Comment by jm-andonegi** [comment]
It would be great if we could find the origin of this problem and fix it but regardless the success of that action, I propose two actions:

1. Adding a catch when reading metadata, so that any error reading metadata (this error or any other error) would lead a specific error message and continue loading the package.
2. I think that merge functionality should be tested carefully, so that we can be sure that all new package data are created correctly. When I say new, I mean all data generated in recent versions of eXeLearning. This could be a separate ticket.

**Comment by JuanCasanovaSdweb** [comment]
Hi @ignaciogros,

The fix that we uploaded makes it so the missing metadata from the package is reinserted when loading the package (we even improved it in bdfaa651ed97af3afb7cd90258b50012c23ac595).

I have been testing with the packages that used to give an error (both the one in this issue and the one in the forum) and both seem to work fine.

I think this could be improved even further by customizing the functions that initialize the metadata, but this should be more than enough for now (basically leaving it like this would mean that some users could use the package metadata when editing a blank package).

**Comment by ignaciogros** [comment]
> both seem to work fine.

> I think this could be improved even further by customizing the functions that initialize the metadata, but this should be more than enough for now

OK. We close this issue then. Thanks, @JuanCasanovaSdweb!

**Comment by Lintang237** [comment]
A user has sent me a file that has been generated merging two packages. The result is the attached file (I have added .zip to the file name because the .elp files are not allowed ?
[MODUL-GERAK-MELINGKAR-BERATURAN.zip](https://github.com/exelearning/iteexe/files/7919711/MODUL-GERAK-MELINGKAR-BERATURAN.zip)
Can you help me, Sir?please

**Comment by ignaciogros** [comment]
> A user has sent me a file that has been generated merging two packages. The result is the attached file (I have added .zip to the file name because the .elp files are not allowed ? [MODUL-GERAK-MELINGKAR-BERATURAN.zip](https://github.com/exelearning/iteexe/files/7919711/MODUL-GERAK-MELINGKAR-BERATURAN.zip) Can you help me, Sir?please

Sorry, but the file is corrupted. An elp is a zip file with a different extension. You should be able to unzip it changing its extension from elp to zip and using a zip utility. If you can't do that (I couldn't with that file), you can try to fix it using a zip repair tool.
