### ISSUE TITLE
Donwload issue

### ISSUE THREAD

**Issue by fredtempez** [exelearning/iteexe#254]
Hi,

I know it's not bugs, maybe an issue on your web site in http://exelearning.net/downloads/

- Win Portable is not a zip but ready to go, not enable tu run on no admin session (not the good file ?)
- Linux tag.gz isn't right, uncompress file reveale only one dat file on linux Ubuntu and Win (error uploading ? )

Anyway, thanks for this great tool ! 
:)

**Comment by ignaciogros** [comment]
We'll check that. **Thank you, Fred!**

**Comment by JuanCasanovaSdweb** [comment]
Should be fixed now!
There was a problem with the uploaded portable files but @miguelpereiraite uploaded them again.
