### ISSUE TITLE
FR: TinyMCE 4 - Add subtitles to video

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#255]
Improve the media plugin so you can add subtitles to a video without editing the HTML code (you can use VTT subtitles with MediaElement too). See http://exelearning.net/forums/topic/srt-en-video/

**Comment by r1goo** [comment]
@ignaciogros did you overpass this issue?

**Comment by ignaciogros** [comment]
Hi @r1goo,

Not yet... We're currently working on a new eXe version that will be released soon, but I don't think It'll have this functionality. 

I'll update this issue as soon as it's done.

Until then, you can add the subtitles as described in http://exelearning.net/forums/topic/srt-en-video/#post-29151

**Comment by ignaciogros** [comment]
Hola Manuel:
Acabo de probar el plugin. 
¿Qué te parece eliminar srclang=""? De momento no admite más de un subtítulo. 
Lo ideal (al menos para más adelante) sería permitir más de un subtítulo y, de cada uno, poder especificar LABEL (para que no sea siempre "Subtítulos" y SRCLANG).
Lo que decidas sobre dejar el atributo vacío de momento me parece bien. ¿Cierras la incidencia después?
Muchas gracias.

**Comment by ignaciogros** [comment]
SRCLANG attribute removed in 12cd1fba6d99539c9e28ff19117e7ad80826c962. Closed for the moment. FR for the future: Multiple subtitles (different languages). You should be able to define language and title of each file.

**Comment by ignaciogros** [comment]
> Hi there! I think you might hit my name by error when you add me to this repository. Take a look again.

Hi @r1goo!

We didn't add you to the repository. You asked this and that's why you receive notifications: https://github.com/exelearning/iteexe/issues/255#issuecomment-363514087
