### ISSUE TITLE
Can't edit content

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#256]
This content can't be open: http://procomun.educalab.es/es/ode/view/1509540049922

@JuanCasanovaSdweb says that it may be because it uses a Style which is not installed.

All contents (elp or zip) should be open with eXe's default Style if the selected Style is not installed.

Reported via email ('Problema edición contenidos descargados desde procomún') by a user.

**Comment by JuanCasanovaSdweb** [comment]
The problem was actually related to eXe's inability to open ELPs with folders inside. With this last update, you should be able to open and export this package without any problems.
