### ISSUE TITLE
v2.1.3 branch: Can't save elp

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#259]
v2.1.3 branch (Windows 7 + Firefox).

I save a new elp. Then I keep writing, and when I try to save again it says: 

ERROR AL GUARDAR "X:\...\my_idevice.elp" ya existe. Por favor inténtelo de nuevo con un nombre de archivo diferente

Does it work for you?

**Comment by JuanCasanovaSdweb** [comment]
There was an error when checking if a template's name was already in use due to a misunderstanding of the previous code.
I have fixed it and added a couple comments to prevent this for happening again.
