### ISSUE TITLE
Traducción listas con numeración automática

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#26]
No está traducida la cadena "Automatic Numbering".

**Comment by jrfern** [comment]
The problem is not that tinymce_3.5.11_settings.js is not prepared for translation, it is, but that the directory exe/webui/scripts/ is not in the path where pybabel and mki18n.sh search for the files. 

The fix is trivial, just add the path to pybabel.conf, but these changes have always been done by @pedropena, and I would ask him to do it, lest some unexpected consequences arise.

**Comment by jrfern** [comment]
Una duda, @pedropena , tu commit borra exe/webui/tools/style-designer/langs/es.js - ¿esto es inofensivo? No he querido regenerar los PO a estas alturas pero... ¿no se pierden las traducciones de ese fichero? ¿ @ignaciogros , esto era parte del sistema anterior de traducción de esta parte? ¿aparecen ahora cadenas nuevas?

En caso de que sea una falsa alarma, perdonad y cierro otra vez el bug.

**Comment by pedropena** [comment]
Ese fichero no debe usarse para traducir ya que usa el mecanismo de traducción de tinymce. Todas las traducciones deben usar el mecanismo basado en gettext. El diseñador de estilos ya usa gettext.

Por otro lado, si ejecutas de nuevo el script de recopilación de cadenas, aparecerán nuevas cadenas a traducir, incluida la que motiva la apertura de este bug.

**Comment by jrfern** [comment]
Gracias, @pedropena . Lo que suponía/me temía. Aparte de que se han borrado las traducciones propuestas por @ignaciogros , ¿a estas alturas vamos a iniciar una nueva ronda de traducciones? @antoniomonjef , ¿qué opinas?

**Comment by antoniomonjef** [comment]
Si solo es el caso que se ha detectado, yo lo dejaría pendiente para la próxima vuelta (exelearning 2.1.1)

**Comment by jrfern** [comment]
Quizás olvidas, @antoniomonjef , que se ha empezado por borrar el fichero es.js y que el parche está aplicado. Creo que no hay vuelta atrás porque existía el bug #26.

Investigaré si sólo debo repetir las traducciones yo (sólo se ha borrado es.js) y si a los demás traductores les aparecen cadenas nuevas o no. En tal caso pediré tiempo.

**Comment by jrfern** [comment]
Español: 2469 mensajes traducidos, 12 traducciones difusas, 12 mensajes sin traducir (se han perdido las traducciones anteriores).

Euskera (por poner un ejemplo de un idioma que también estaba completo): 2469 mensajes traducidos, 12 traducciones difusas, 12 mensajes sin traducir.

Sin comentarios.

**Comment by antoniomonjef** [comment]
Vale @jrfern ... entonces qué quieres hacer?
¿Qué propones?

**Comment by pedropena** [comment]
Intento aclarar un poco el tema: antes del arreglo no se llegaban a ciertas cadenas (al parecer 12, según lo que aporta @jrfern ). Después del arreglo se llega a 12 cadenas nuevas, entre ellas la del bug ("Automatic Numbering"). Con "llegar" me refiero a cadenas que están disponibles para traducir.

El arreglo incluye el borrado de un archivo innecesario (es.js del diseñador de estilos), no se estaba usando para traducir y ya estaba incluido en los ficheros .po.

Tal vez a lo que se refiere @jrfern es a aplazar la solución de este ticket a 2.1 + 1, ya que la solución implica traducir nuevas cadenas a las que no se llegaba.

**Comment by jrfern** [comment]
Supongo que la única opción es traducir las 24 cadenas. Antes de repartir trabajo... ¿pensáis que durante la fase de pruebas van a aparecer más cambios que repercutan en las traducciones? ¿Espero un poquito?

**Comment by jrfern** [comment]
Ya he subido la traducción castellana completa.

**Comment by ignaciogros** [comment]
Confirmo que es.js no se usaba. Dejé ahí el archivo porque contenía todas las cadenas en castellano tal y como las escribí cuando hice el plugin. Creo que es importante tener en cuenta ese tipo de sugerencias porque afectan a la usabilidad de la herramienta y evitan problemas con las traducciones (traducir "Language" como "Idioma" cuando se trata de "Lenguaje (de programación)", por ejemplo). De todas formas hay otras formas de hacerlo. La próxima vez te paso las sugerencias de otra manera, @jrfern. Muchas gracias.

Por mi parte no habrá nuevas cadenas.

**Comment by antoniomonjef** [comment]
Vamos a la 2.1.1

**Comment by jrfern** [comment]
On 12 April 2016 at 09:07, Antonio Monje <notifications@github.com> wrote:
>
> Vamos a la 2.1.1

No sé si les va a gustar a Joxemi etc. ver que salimos después de
tanto tiempo con una traducción incompleta. Yo me esperaría.


-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by antoniomonjef** [comment]
La 2.1 va a ser corta, muy corta... por la experiencias anteriores
Llevamos un año de retraso

**Comment by jrfern** [comment]
On 12 April 2016 at 11:39, Antonio Monje <notifications@github.com> wrote:
>
> La 2.1 va a ser corta, muy corta... por la experiencias anteriores
> Llevamos un año de retraso

Por eso. Me sigue pareciendo poco considerado con los traductores, que
han cumplido siempre sus plazos y que, recordad, son voluntarios.

-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by antoniomonjef** [comment]
Cuando lo tengas avisa @jrfern 
Ha hecho un gran trabajo el equipo de traductores. Enhorabuena!

**Comment by jrfern** [comment]
Completado el miniciclo urgente. Salimos con traducciones 100% completas de ca, ca@Valencia, es, eu, fr, gl, it, nl, pt y ru.

Nuestros traductores son unos máquinas, aunque no hagan machine translation (perdón por el chiste malo).

Por nuestra parte se puede publicar la versión.
