### ISSUE TITLE
FR: Include Style when exporting

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#261]
Right now, if you use a custom Style and you export the content to share it, the users will have to download and install your Style if they want to have the same design as the original content. It would be good to include it in a different folder (when allowing those structures) and ask the user about installing the Style when opening the elp. Another export preference?

**Comment by jm-andonegi** [comment]
This issue could be easily solved just exporting to different folders contents and styles.

**Comment by jm-andonegi** [comment]
Apatently I have unasigned this FR to Juan. It has been an unintended action and I don't know how to revert it. Sorry.
