### ISSUE TITLE
Strange characters when exporting to ePub with DOCX

### ISSUE THREAD

**Issue by JuanCasanovaSdweb** [exelearning/iteexe#263]
When exporting to ePub a document that has a link to a binary file, Calibre show weird symbols at the end of the document.

The problem was introduced in this commit: b846049cdccac4ea3e3b3b80cdf99611cabe7297

It was done like that to follow the EPUB 3 standard, which states that:

> All Publication Resources that are hyperlinked to from Publication Resources in the spine must themselves be listed in the spine, where hyperlinking is defined to be any linking mechanism that requires the user to navigate away from the current resource.
http://www.idpf.org/epub/31/spec/epub-packages.html#sec-pkg-spine

It also states that some resources are exempt of this, but only those which are outside of the package (which basically means that if you link to an external web page you don't have to include it on the spine):

> As Remote Resources referenced from hyperlinks are not Publication Resources, they are not subject to the requirement to include in the spine (e.g., Web pages and resources).
http://www.idpf.org/epub/31/spec/epub-packages.html#sec-pkg-spine

In fact, using an online validator (http://validator.idpf.org/application/validate) I have confirmed that removing the file from the spine causes the validation to fail (there are another CSS related problems with absolute positioning).

For my tests I have used this ELP: https://www.dropbox.com/s/3k6y5kiwjzhgs9x/Test.elp?dl=0
ePub with the DOCX in the spine: https://www.dropbox.com/s/vgtjtmg3aq3lytr/Test.epub?dl=0
ePub without the DOCX in the spine: https://www.dropbox.com/s/1y22hpq0sxto0i9/Test_DOCX_Out_Of_Spine.epub?dl=0

We have 2 options that I can think of:

- Adding an export option for this
- Sticking to the standard and forgetting about Calibre

**Comment by ignaciogros** [comment]
Is it a Calibre bug? If you think so, I think that we shouldn't try to fix that, at least for the moment. @miguelpereiraite?

**Comment by ignaciogros** [comment]
Please close if you agree, @miguelpereiraite.

**Comment by JuanCasanovaSdweb** [comment]
I have created a bug report in their bug tracker: https://bugs.launchpad.net/calibre/+bug/1748250

I will keep you updated if they answer.

**Comment by JuanCasanovaSdweb** [comment]
They seem to have a rather strong opinion on this matter: https://bugs.launchpad.net/calibre/+bug/1748250/comments/1

Basically they are not going to fix it:

> calibre does not and will not support documents of types other than HTML
> in the spine.

And this is the solution they give us:
> And incidentally the EPUB spec is both awful and dead (the organization
> that publishes it has been disbanded and decided that the future of
> ebooks is as a webapp). Dont follow the spec and expect anything useful
> to come from the effort. Instead test your book on actual EPUB
> renderers. As far as I know, no renderer is going to do anything
> sensible with arbitrary binary data in the spine.

**Comment by ignaciogros** [comment]
I just read this [here](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-pkg-spine):

> **NOTE**

> As Remote Resources referenced from hyperlinks are not Publication Resources, they are not subject to the requirement to include in the spine (e.g., Web pages and resources).

> Embedded Publication Resources (e.g., via the [HTML] iframe element) do not have to be listed in the spine.

You say:

> In fact, using an online validator (http://validator.idpf.org/application/validate) I have confirmed that removing the file from the spine causes the validation to fail (there are another CSS related problems with absolute positioning).

Could you attach an ePub with those files out of the spine and describe the CSS related problems?

Thank you!

**Comment by JuanCasanovaSdweb** [comment]
You can download it from here: https://www.dropbox.com/s/1y22hpq0sxto0i9/Test_DOCX_Out_Of_Spine.epub?dl=0

In any case this is the result of the validation:

Type | File | Line | Position | Message
-- | -- | -- | -- | --
ERROR | ./tmp/uploads/1518166335144_0000003967/inputFile/Test_DOCX_Out_Of_Spine.epub/Test_DOCX_Out_Of_Spine.epub | - | - | Mimetype file entry is missing or is not the first file in the archive.
ERROR | EPUB/package.opf | 6 | 22 | Error while parsing file  'character content of element "dc:title" invalid; must be a string with  length at least 1 (actual length was 0)'.
ERROR | EPUB/content.css | 81 | 18 | An error occurred while parsing the CSS: Token '*' not allowed here, expecting a property name.
ERROR | EPUB/base.css | 7 | 5001 | An error occurred while parsing the CSS: Token '*' not allowed here, expecting a property name.
ERROR | EPUB/base.css | 7 | 5250 | An error occurred while parsing the CSS: Token '*' not allowed here, expecting a property name.
ERROR | EPUB/base.css | 7 | 5484 | An error occurred while parsing the CSS: Token '*' not allowed here, expecting a property name.
ERROR | EPUB/inicio.xhtml | 23 | 45 | Found a reference to a resource that is not a spine item.
WARNING | EPUB/content.css | 95 | 22 | CSS selector specifies absolute position.
WARNING | EPUB/base.css | 7 | 4531 | CSS selector specifies absolute position.
WARNING | EPUB/base.css | 7 | 5816 | CSS selector specifies absolute position.
WARNING | EPUB/base.css | 7 | 5900 | CSS selector specifies absolute position.
WARNING | EPUB/base.css | 7 | 7766 | CSS selector specifies absolute position.

The first error has something to do with uncompressing and compressing the ePub again (doesn't happen when you upload a file directly exported from eXe).
The second one is due to the fact that I didn't put a title on the ELP.
The one for _EPUB/inicio.xhtml_ happens when you remove the DOCX from the spine.

That was what we were trying to fix with this commit: 7a9f69906794bc65f81b62776879d18048786f9a and reverted with this one: 118d8cc924cc8d1fef81827bdc079c4040b7b52c, but I'm not sure it's the best way to deal with this.
