### ISSUE TITLE
exe_do problems since fixed #165 issue

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#265]
I'm trying to export an xliff from one of my elps but this is what I get.

Checking from whats going on I see this changes where introduced fixing the issue #165 

C:\Program Files (x86)\exe\library.zip\webassets\filter\__init__.py:722: UserWarning: Error while loading builtin filter module 'cssrewrite': No module named cssrewrite
C:\Program Files (x86)\exe\library.zip\webassets\filter\__init__.py:722: UserWarning: Error while loading builtin filter module 'jspacker': No module named jspacker
C:\Program Files (x86)\exe\library.zip\webassets\filter\__init__.py:722: UserWarning: Error while loading builtin filter module 'rjsmin': No module named rjsmin
C:\Program Files (x86)\exe\library.zip\requests\__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.1.1) doesn't match a supported version!
Traceback (most recent call last):
  File "exe\engine\package.pyc", line 1250, in load
AttributeError: 'NoneType' object has no attribute 'invalidPackageName'
exe_do: error - no se ha podido exportar desde 'c:\Users\ulhi\Desktop\es_APSD_AS01_Contenidos_oficial.elp'.
El error fue:
'NoneType' object has no attribute 'invalidPackageName'

**Comment by antton** [comment]
Hi again, 

I try install and uninstall every version until 2.1, and It only works properly until 2.1.1

So any change on from this versión would be guilty ;)

Thanks and I hope this help you to find out the problem!!

**Comment by JuanCasanovaSdweb** [comment]
This should be fixed now on the [v2.1.3](/exelearning/iteexe/tree/v2.1.3) branch, which contains all of the changes that will be pushed on the next eXe release.

Thanks @antton for the report!
