### ISSUE TITLE
adding <meta> to html export

### ISSUE THREAD

**Issue by fredtempez** [exelearning/iteexe#267]
Hi,
This is not really an issue, sory but I can't post on the forum.
The question is how to add custom meta in html export 
<meta http-equiv="pragma" content="no-cache" />
in exelearning GUI rather than editing the file ?
thanks

**Comment by ignaciogros** [comment]
Hi,

You can edit your Style's config.xml file. Add anything you want in 'extra-head'. That code will be included in the HEAD tag when exporting.

Apart from editing the HTML files, that's the only way to do it right now. I hope that there will be an easier way in the future (a way of editing each node's properties: Title, description and other information).

**Comment by fredtempez** [comment]
It works great, thanks
