### ISSUE TITLE
Wikipedia iDevice is not always working on Mac

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#268]
Description: http://exelearning.net/en/forums/topic/insertar-idevice-wiki-mac/

Please answer in the forums if you find a solution.

Thank you.

**Comment by JuanCasanovaSdweb** [comment]
More than a month without a response from the user.

We aren't able to replicate the issue anymore since we updated the libraries used to generate the Mac package, so this should be marked as fixed (will reopen if it happens again).
