### ISSUE TITLE
Content Templates: Properties translation 

### ISSUE THREAD

**Issue by JuanCasanovaSdweb** [exelearning/iteexe#269]
There is a problem with content templates and the way eXe stores the package properties.

Basically, there is no list that we can check to go through all the properties and translate them, so we have to translate them manually:
https://github.com/exelearning/iteexe/blob/f6ee789da4f050707278f5c946e5ddc1a3b49dd1/exe/engine/package.py#L512-L515

Even if we could go through all properties, not all of them should be translatable.

The best thing to do would be to rewrite how eXe handles this properties (have a list somewhere and generate the forms automatically), but this would take some time.

For now, we could just choose the properties that we think should be translatable and translate them "manually". I have gone ahead and added the following:

- Title
- Description
- Footer

Which more of them should be added?

**Comment by jrfern** [comment]
Is the License included in the Footer?

**Comment by JuanCasanovaSdweb** [comment]
@jrfern, the license is added automatically by eXe in the language of the package (it was already doing it).

It just uses the license selected in the package properties and adds the "Licensed under the..." part (the license name is also translated).

I think we can close this issue, as every property that matters for the current templates is already translated.

If you think there is any property missing feel free to reopen it!
