### ISSUE TITLE
Create or edit Style. Title with special characters.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#27]
You can't save a Style if its title has special characters. 

I think that some of those characters should be allowed (accents...).

A Style called 'Probando con "caracteres especiales" falló' should create a folder called "probando_con_caractacteres_especiales_fallo".

Quotes are escaped in the config.xml file (&quot;). Should they?

**Comment by pedropena** [comment]
Keeps failing in Windows
