### ISSUE TITLE
Failed to load content css

### ISSUE THREAD

**Issue by MarianaNovaes** [exelearning/iteexe#275]
Hi,

The ExeLearning sends the message "Failed to load content css" and just my style don't load.
This happened for no reason. What may be the problem?

And sorry my english

Thanks

**Comment by JuanCasanovaSdweb** [comment]
Hi @MarianaNovaes 

To be able to help you we will need a little bit more of information.

Could you tell us what version of eXe you are running and what are the steps to take to be able to reproduce the issue?

If you prefer to do it in Spanish that would be completely fine by us.

**Comment by MarianaNovaes** [comment]
Olá!

A versão do exelearning que estou usando é a 2.1.3.
E o problema que ocorre é que o estilo que usamos não quer carregar. Ele está na lista, mas ao selecionar ele, a formatação não aparece.
E quando abro a ferramenta de Texto Livre aparece a mensagem:
'Failed to load content css: http://localhost:51235/style/Unifamma/content.css'
Não fizemos qualquer modificação no arquivo de estilo. Mas o exelearning não o carrega mais, sem qualquer motivo aparente.
O que poderia ser esse problema?

Desculpe a mensagem anterior, pois ainda estou procurando compreender como funciona este fórum.
Também não sou muito adepta do espanhol, então, como sou brasileira, deixei a mensagem em português, tudo bem?

Obrigada.

**Comment by JuanCasanovaSdweb** [comment]
Bom dia,
Faz favor, para poder realizar comprovações precisamos que você nos faça chegar o estilo e que nos indique como geraram este estilo.
Muito obrigado

**Comment by MarianaNovaes** [comment]
[Unifamma.zip](https://github.com/exelearning/iteexe/files/1847722/Unifamma.zip)

Bom dia!

Segue o estilo em anexo. Não posso indicar como o estilo foi gerado, pois, ele já é usado há muito tempo nas diagramações e foi desenvolvido por um ex-funcionário. Portanto, não tenho informações sobre como foi gerado. Mas, acredito que tenha sido desenvolvido em html e css.
O que posso fazer é descrever como é o layout. Quando o estilo era selecionado, a página aparecia dividida em duas colunas e determinados códigos geravam imagens e bordas. Mas agora, nada disso aparece.

Obrigada!

**Comment by JuanCasanovaSdweb** [comment]
Bom dia,
	O problema é que os estilos estão tentando carregar desde uma URL externa que não responde (http://oa.ava.famma.br/content.css).
	Não podemos te ajudar aos recuperar já que ao estar armazenados num servidor externo não fica nenhum  vestígio do verdadeiro estilo nos ficheiros de eXe.
	
	Fecho a incidência já que não é um erro em eXe, mas não duvides em dizer-nos se precisar algo mais.

Sento não poder ser a mais ajuda!

**Comment by MarianaNovaes** [comment]
Entendi.
De qualquer modo, muito obrigada!
