### ISSUE TITLE
Remove Base.elt?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#289]
Is Base.elt necessary? If not, I think that we should remove it. Isn't it just an empty package? 

Thanks...

**Comment by JuanCasanovaSdweb** [comment]
If we delete it, eXe should create a new package the same way it used to do.

We kept it there so it could be easier to modify it if necessary.

If there is no reason to modify it (i certainly cannot think of one) we can remove it (we will test everything so nothing breaks).

**Comment by ignaciogros** [comment]
If changing that file we can change the way the new documents are created, **we can just hide it in the menu**. It's just that having a template which is just as an empty document is quite strange.
