### ISSUE TITLE
FR. Pegar imagen desde el portapapeles

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#29]
Pegar imagen desde el portapapeles y quede incorporada al paquete...

**Comment by ignaciogros** [comment]
Actualmente no se permite el pegado de imágenes para evitar que crezca el número de imágenes en Base64.

La función que se encarga de hacerlo es $exeAuthoring.compareBase64, que se ejecuta al cambiar el contenido de TinyMCE ("onChange"). 

Para permitir el pegado de imágenes (en Base64) no hay más que comentar esta línea del fichero de configuración de TinyMCE (actualmente tinymce_3.5.11_settings.js):

$exeAuthoring.compareBase64(ed);

Para completar la solución, en lugar de impedir el pegado, habría que generar una imagen (PNG, por ejemplo) partiendo del código Base64 (http://stackoverflow.com/questions/16214190/how-to-convert-base64-string-to-image).

Luego habría que incluir la imagen en el paquete. 

Asigno la petición a Pedro.

Si lo que se quiere es que se vuelvan a poder pegar imágenes en Base64, volved a asignármela, por favor.

**Comment by antoniomonjef** [comment]
Lo que quiere es que se genere un png o similares...
Esto es en realidad un FR y no un bug

**Comment by ignaciogros** [comment]
We should test this as much as possible, but I think that we can close it. Thanks.
