### ISSUE TITLE
can't "save" nor "save as"

### ISSUE THREAD

**Issue by iness00** [exelearning/iteexe#300]
It doesn't matter where I place the folder to save it. I always get the same unespecified route: 

ERROR AL GUARDAR [Error 3] El sistema no puede encontrar la ruta especificada: u'c:\\users\\inese\\appdata\\local\\temp\\tmprtv58t\\*.*'
--

**Comment by BorjaVarelaSdweb** [comment]
Hi @iness00,

To be able to help you with your issues, we will need some more info:

- eXe version that you are using.
- OS and browser (with versions).
- The exact procedure that you follow to reach that error.
- Does this happen with an empty package?

Any other info or resources will also be very helpful!

**Comment by JuanCasanovaSdweb** [comment]
There has been more than 30 days since this issue and no response from the user.

We haven't been able to replicate it and there haven't been any other reports of the same error, so I say we can safely close this (it can always be reopened later).
