### ISSUE TITLE
Image gallery: Could not shrink original image

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#301]
Error message in eXe 2.1.13 / macOS Sierra 10.12.6 / Safari: "No Thumbnail Available. Image gallery: Could not shrink original image".

See http://exelearning.net/en/forums/topic/problema-image-gallery-generando-thumbnails/

**Comment by JuanCasanovaSdweb** [comment]
This was actually a problem with installing Pillow without libjpeg installed.

We have tweaked our configuration in our package generation machine and updated package generation instructions for OsX.
