### ISSUE TITLE
Check edia_project_pbl.elt metadata

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#307]
Open the ABP template with eXe in Spanish.

* Go to Properties - Package - Language (its value is 'Español').
* Go to Metadata and check the language (its value is 'English').
* The content has an ID (67f9ce47-8ce5-48e1-aa28-4a7b5c709316 in my case).
* There are also values that belong to a previous project, like "simulación" in "Learning Resource Type", or the "Plataforma Agrega" catalog in the LOM-ES tab.

**Should some of those fields be empty?** Maybe we should distribute an elt with those values only for those who create contents for the EDIA Project.

The contentv3.xml has references to 'cedec' which I think that should not be there. We should fix the inconsistencies anyway.

Thanks.

**Comment by jrfern** [comment]
Reopening, as agreed on mail (@miguelpereiraite has decided that the name of the CEDEC agency in the EDIA templates must be translatable and translated). My proposal for the English version:

National Centre for the Development of the Educational Curriculum on Non-Proprietary Systems (CEDEC)

@JuanCasanovaSdweb, please fix the string in th ELT.
