### ISSUE TITLE
FR: More than one option by default in the Question iDevices

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#309]
When you add an iDevice (multi-choice, multi-select, etc.) you only have one question/answer by default, and you'll always need more than one. 

Luis M. Iglesias suggests having 3. See http://exelearning.net/forums/topic/no-de-preguntas-y-respuestas-en-idevices-tipo-cuestionario-y-pregunta/

Maybe 2 is enough in some cases, or we might have to many empty fields when adding the iDevice.

Would that be easy, @JuanCasanovaSdweb?

Luis M. also suggests a "duplicate question" option. Maybe a new iDevice with different options (something like Google Forms) would be better and even easier.

**Comment by Javiobcn** [comment]
It's solved for next version in c7f974f29041733de0cde066fcd6f64b1910f4fd
