### ISSUE TITLE
Problema con las imágenes de estilo propio

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#31]
Hola:
Cuando creo un estilo y añado una imagen una imagen, por ejemplo  en Fondo de página (sólo sitio web),  si tiene espacios en el nombre falla al importar en Agrega.

Además si cambiamos esta imagen se mantiene la antigua y aparece tanto en el exportado a html como en SCORM.

Saludos

**Comment by ignaciogros** [comment]
Hay que hacer un cambio en /tools/style-designer/js/app.js para codificar las URLs con caracteres especiales. El archivo adjunto (app.zip) incluye esos cambios.

Con eso se solucionarían los fallos de importación en Agrega, pero no es el único problema:

Al guardar las imágenes hay un problema de codificación de caracteres, y una imagen llamada José.jpg pasa, por ejemplo, a llamarse Jos+®.jpg, de manera que la imagen no se ve (error 404). 

Posibles soluciones:

- Solucionar ese problema y que las imágenes se incluyan en el paquete con el nombre original, incluidos espacios y caracteres especiales.
- Eliminar estos caracteres para evitar otros posibles fallos. En ese caso, habría que aplicar el mismo criterio en app.js.

Cambio asignación.

[app.zip](https://github.com/exelearning/iteexe/files/197203/app.zip)
