### ISSUE TITLE
SCORM export: Nodes level problem?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#320]
* Open the attached elp. Its nodes are nested.
* See the imsmanifest.xml file of the exported SCORM. They all have the same level? 

Is that right, @JuanCasanovaSdweb? If not, we should fix that before testing eXe 2.2 again.

[scorm-tests.zip](https://github.com/exelearning/iteexe/files/2021756/scorm-tests.zip)

**Comment by JuanCasanovaSdweb** [comment]
Actually, the imsmanifest.xml that you sent is perfectly fine. Nodes are nested as configured in eXe.

This is an example of a part of the file attached (with right indentation):
```xml
<title>Nombre del paquete</title>
<item identifier="ITEM-eXeruebascorm5ae997be2389731c1b3" isvisible="true">
  <title>Inicio</title>
  <item identifier="ITEM-eXeruebascorm5ae997be2389731c1b4" isvisible="true" identifierref="RES-eXeruebascorm5ae997be2389731c1b5">
    <title>&lt;-</title>
  </item>
</item>
```

If I misunderstood something, let me know. If not, you can close this issue.

**Comment by ignaciogros** [comment]
You're right. I just read the XML without indentation. I obviously did it too fast. Sorry about that, Juan.

Thanks!
