### ISSUE TITLE
Exe save file is crashed all data is gone

### ISSUE THREAD

**Issue by Martsp** [exelearning/iteexe#321]
save file name has .crashed  and it is like wiped out. There was my 2 day work

**Comment by JuanCasanovaSdweb** [comment]
Hi @Martsp,

Could you send us the package? That we can study it (and possibly recover it).

We also would need to know which version of eXe you are using.

**Comment by JuanCasanovaSdweb** [comment]
Closing this for now. Will open again if the user replies to our request.
