### ISSUE TITLE
LOM-ES metadata: Can't download sources

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#326]
Properties - Metadata - LOM-ES - Classification - Download classification sources. It can download them. 

The "Connecting to classification sources repository...", but nothing happens.

I don't know where that repository is, and this error is common, but you can download the sources sometimes. Could it be a connectivity issue?

I think it's a FR, but if it's a connectivity issue we could display this error if needed (no new translation required): Could not retrieve data (Core error)

@JuanCasanovaSdweb?

**Comment by JuanCasanovaSdweb** [comment]
The repository from which those "sources" are downloaded is actually this one: https://github.com/exelearning/classification_sources

The problem here is that there are no data for some categories:
   - idea
   - prerequisite
   - educational objective
   - skill level
   - security level

**Comment by ignaciogros** [comment]
Could we handle the error an display an informative message? Or maybe we could hide the download button when selecting any category without data. That would be easier (and I think that better).

Another thing to check: Should those categories have data too?

Thanks!

**Comment by Javiobcn** [comment]
This issue is fixed for next version in a64ef57702b62f537c4490dd65ab969669f83ff5 
We are checking if internet connection is available before to download sources.
