### ISSUE TITLE
Style Manager in IE. List not refreshed after deleting a Style.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#33]
Internet Explorer.
- Create a new Style.
- Go to the Style Manager and delete it.
- The Style remains in the list until you restart eXe.

**Comment by antoniomonjef** [comment]
Bueno, esto lo vamos a dejar para la siguiente a no ser que tengamos tiempo en esta...

**Comment by ignaciogros** [comment]
It's working.
