### ISSUE TITLE
TinyMCE 4: Tooltip plugin errors when there's more than one editor

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#335]
* Add an iDevice with more than one editor.
* Try to add a definition tooltip in the first one.
* The definition will be included in another one, and you can't change it using the plugin.

Reported by @miguelpereiraite.

See http://exelearning.net/en/forums/topic/mal-funcionaminto-de-bocadillo-tooltip/

**Comment by ignaciogros** [comment]
@miguelpereiraite:

Could you test this solution, please?

[plugin.min.js.zip](https://github.com/exelearning/iteexe/files/2267327/plugin.min.js.zip)

Path: scripts/tinymce_4/js/tinymce/plugins/tooltips/plugin.min.js

**Comment by cristinavaldera** [comment]
We have test the solution and it solves the problem. We have just tested in windows.
Good work
