### ISSUE TITLE
Dockerize application: create a Docker image with minimal depencences inside

### ISSUE THREAD

**Issue by lcostela** [exelearning/iteexe#340]
I try to create a image from current version but it need a instance of browser.
I uderstad that modifying mywebbrowser.py it is posible.
Here is the error when execute the container:
![image](https://user-images.githubusercontent.com/20224532/44482207-1ec11480-a61e-11e8-946b-836f2738c19b.png)
The base image is ubuntu or debian but apline would be much better

**Comment by JuanCasanovaSdweb** [comment]
Hi @lcostela,

I'm sorry but as it is now, eXe is not compatible with Docker at all.

Although it uses a web server to work, eXe is a desktop app and will not work in a real network environment. For example, when saving a package, the process itself is done by the server with the assumption that it is the same machine as the client.

Currently, we are working in an online version that will allow you to install eXe (using for example Docker) on any machine and connect to it through the network.

You can see this work in the [ws branch](https://github.com/exelearning/iteexe/tree/ws) (we even use Docker there) and if you want to make a contribution to the project you are more than welcome to do so :wink:
