### ISSUE TITLE
docx and odt preview. ¿Headers problem?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#343]
Windows 7 / Firefox (but it probably happens in other browsers and OS too). 

* Add a link to an odt and another one to a docx file.
* Preview the project and click on those links.

I think it's a headers problem. A like to a doc file works.

**Comment by JuanCasanovaSdweb** [comment]
Actually, it only happens with Windows (or I imagine very old versions - pre 2007 - of Linux). The MimeTypes for those file formats where missing (along with .odp, .ods, .pptx and .xlsx).
There are probably more missing mime types, but we should include them only if necessary (doesn't make sense to have a list of mimetypes when most OS include one).
