### ISSUE TITLE
Header image is not displayed

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#344]
Add a header image in the Properties tab.
If the image is in a folder with special characters, it won't be displayed.
See: http://exelearning.net/forums/topic/cargar-imagen-fondo-de-cabecera/

**Comment by ignaciogros** [comment]
@JuanCasanovaSdweb:

The image is not uploaded. See also `action.response.responseText` in MainTab.js

**Comment by Ivanaaaaaaa** [comment]
what is the step to solve the file?
