### ISSUE TITLE
Can't insert package with a zip file

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#347]
Try this with the attached elp: File - Merging - Insert package.

You'll get a "Sorry, wrong file format" or the "Inserting package: ..." message, but the insertion won't finish.

If you delete the attached zip file (see the File Attachments iDevice), it'll work.

I only tried that with a zip file. It might happen with other formats too.

[Download elp](https://github.com/exelearning/iteexe/files/2468877/para-insertar.zip)

**Comment by JuanCasanovaSdweb** [comment]
This seems to be the same as #352.

The weird thing in this case is that it was working without the File Attachments iDevices. I have tested it in both Ubuntu and Windows and seem fine, but we should include it in the tests for the next beta.
