### ISSUE TITLE
Move from BeautifulSoup3 to BeautifulSoup4

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#348]
As the end of life of python2 is approaching (what are we doing to avoid this, I wonder), packages will abandon the 2 versions. 

> [2018-10-13]  beautifulsoup REMOVED from testing (Debian testing watch) 

I read at https://www.crummy.com/software/BeautifulSoup/

> The current release is Beautiful Soup 4.6.3 (August 12, 2018).  In Debian and Ubuntu, Beautiful Soup is available as the python-bs4 package (for Python 2) or the python3-bs4 package (for Python 3). In Fedora it's available as the python-beautifulsoup4 package.
> Beautiful Soup 4 works on both Python 2 (2.7+) and Python 3.
> 
> Beautiful Soup 3
> Beautiful Soup 3 was the official release line of Beautiful Soup from May 2006 to March 2012. It is considered stable, and only critical security bugs will be fixed. 
> Beautiful Soup 3 works only under Python 2.x. The current release of Beautiful Soup 3 is 3.2.1 (February 16, 2012). 

2012...2018. Time to move from python-beautifulsoup to python-bs4? **Notice that when Debian Testing becomes Stable our package will be uninstallable.**

**Comment by SilviaPineiroSdweb** [comment]
Update at 30f08817d149b46de0af4c5b48a664bee3bd57a0

**Comment by jrfern** [comment]
The situation: Debian Testing. I install the beta package at https://cloud.sdweb.es and uninstall python-beautifulsoup (eXe now depends on python-bs4). But something goes wrong:

$ exe
Traceback (most recent call last):
  File "/usr/bin/exe", line 40, in <module>
    from exe.application import Application
  File "/usr/lib/python2.7/dist-packages/exe/application.py", line 37, in <module>
    from exe.webui.webserver     import WebServer
  File "/usr/lib/python2.7/dist-packages/exe/webui/webserver.py", line 37, in <module>
    from exe.webui.packageredirectpage import PackageRedirectPage
  File "/usr/lib/python2.7/dist-packages/exe/webui/packageredirectpage.py", line 29, in <module>
    from exe.jsui.mainpage import MainPage
  File "/usr/lib/python2.7/dist-packages/exe/jsui/mainpage.py", line 41, in <module>
    from exe.jsui.idevicepane        import IdevicePane
  File "/usr/lib/python2.7/dist-packages/exe/jsui/idevicepane.py", line 30, in <module>
    from exe.engine.jsidevice import JsIdevice;
  File "/usr/lib/python2.7/dist-packages/exe/engine/jsidevice.py", line 27, in <module>
    from exe.engine.field                               import Field, TextField, TextAreaField, FeedbackField
  File "/usr/lib/python2.7/dist-packages/exe/engine/field.py", line 36, in <module>
    from exe.webui                import common
  File "/usr/lib/python2.7/dist-packages/exe/webui/common.py", line 34, in <module>
    from BeautifulSoup             import BeautifulSoup
ImportError: No module named BeautifulSoup

It should be 'from bs4 import BeautifulSoup', shouldn't it?

**Comment by jrfern** [comment]
Applied the "patch" myself. Sorry if this a terrible mistake, I needed it to be able to compile the translations (the template part) and to test them.

Please close the issue if the problem has been solved.

**Comment by jrfern** [comment]
Closing. I expected someone else to check, but as I opened the issue, I'm closing it myself.
