### ISSUE TITLE
Remove the dependance on python-imaging

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#349]
python-imaging is no longer available in Debian Testing or Unstable. According to the description of the package:

> Python Imaging Library compatibility layer
> PIL used to provide a PIL.pth file which allowed you to 
> `import Image` but this is deprecated.  Use `from PIL import Image` now, or
> install this compatibility package to temporarily get the old behavior back.

But this compatibility package mentioned is which has been removed now. I guess a code check might be necessary before just deleting  the reference to python-imaging. 

Why is this important? **Because when Testing becomes Stable our package won't be installable.**

**Comment by ignaciogros** [comment]
This issue, like #348, should be fixed before the first online version is released. All dependencies and Python libraries will be checked so there are no installation problems. Thanks for reminding, @jrfern.

**Comment by JuanCasanovaSdweb** [comment]
Closed by 9a840853948e4fa742f1b36118932db9b8f8b9ea
