### ISSUE TITLE
Beta 2 exports to undefined folder

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#356]
- Open eXe.
- Try to export the new clean elp (click on "Export without changes").
- It'll export to undefined\newPackage. If that folder already exists, you'll get this error: "Folder name undefined\newPackage already exists."

If the elp has a name, the path is wrong too: undefined\packageName

**Comment by JuanCasanovaSdweb** [comment]
This is the same as #354, right?
If so, I think we can keep only one of them (it should be the same issue even if one is during development and the other one is on a generated package).

**Comment by ignaciogros** [comment]
You're right. Thanks, Juan. We keep this one. I close #354, which has less information.
