### ISSUE TITLE
Error reported by procomún in a PRE tag

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#360]
The error reported by Procomún is displayed in a PRE tag. Maybe be could just display the text of that tag. Do you agree? If not, just ignore this issue and close it, please.

**Comment by JuanCasanovaSdweb** [comment]
The goal was to differentiate the message received from Procomún from our own error text.
We can of course do that using other means if you think using a PRE tag is not right!

**Comment by ignaciogros** [comment]
Ups... Sorry about that. I thought that the PRE tag was part of the response. We keep PRE just in case Procomún starts returning messages with line breaks. Thanks, Juan.
