### ISSUE TITLE
The "Learning Resource Type" combos are not 100% dependant

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#361]
* New package.
* File - Publish - Procomún.
* Write a title, a description and the author's name.
* Choose "conceptual map" as "Learning Resource Type".
* Click on "Save and export".

Then go to the Properties tab:

* "conceptual map" is selected in the Package tab. That's right.
* It's also selected in the Metadata - LOM-ES tab. That's right too.
* No type is selected in the Metadata - LOM tab. I believe that "graphic" should be selected (see this document: [ANÁLISIS DE MAPEABILIDAD LOM/LOM-ES V1.0](http://educalab.es/documents/10180/40863/LOM-ESejemplo13.pdf/cfea1d09-0f28-4a4f-bf04-875f825a3f04)), so all the category combos are dependant. Is that right, @JuanCasanovaSdweb? Pleas mark it as accepted if so... Thanks.

**Comment by JuanCasanovaSdweb** [comment]
Actually, it was "diagram" (graphic doesn't really exist?).

The problem was actually only with "conceptual map" because the mapped LOM value didn't exist.

**Comment by ignaciogros** [comment]
- New elp.
- Properties - Resource Type: Select "conceptual map".
- Go to Metadata - LOM: Diagram is selected. That's right.
- Go to Metadata - LOM-ES: "conceptual map" is selected. That's right.

But if you change the values in any of the LOM tabs, the other 2 values won't be updated, so you can have 3 different selected categories.

If you go back to the Package Properties tab and choose another category, you'll see that it's added to the LOM tabs (there will be more than one value there). That might be right...

**Comment by ignaciogros** [comment]
Is this a FR or an issue to close before 2.3 is released? Thanks.

**Comment by JuanCasanovaSdweb** [comment]
This was always like this (and for every field, not only resource type). For example, for resource type:

When selecting one from package properties, this function is called, which will make sure those values are also in LOM and LOM-ES:
https://github.com/exelearning/iteexe/blob/2e35490141211fc533b069ea6e5a3011b9e480cd/exe/engine/package.py#L892-L923

However, when the value is changed directly in the LOM or LOM-ES tabs, only those exact values are updated:
https://github.com/exelearning/iteexe/blob/2e35490141211fc533b069ea6e5a3011b9e480cd/exe/jsui/propertiespage.py#L290-L302

I'm marking this as an FR as I think it's to big of a change to do it before releasing 2.3.

**Comment by ignaciogros** [comment]
I agree. FR then. Thanks.

**Comment by ignaciogros** [comment]
Not in eXe 2.6+.
