### ISSUE TITLE
Can't edit (in eXe 2.2) a package created with eXe 2.2.1

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#362]
Download [this package](http://exelearning.net/en/forums/topic/mostrarocultar-imagen-en-un-fx/#post-30164) (created with eXe 2.2.1) and try to edit it with eXe 2.2. You'll get a "Wrong file format" error. I'm using Windows 7/Installer/Firefox.

**Comment by JuanCasanovaSdweb** [comment]
Actually this seems like an intended feature:

This line asserts that the version of the loaded package is not higher than the one eXe currently has:
https://github.com/exelearning/iteexe/blob/f497bf35d8759d13185556b7cc9006dccf2ca676/twisted/persisted/styles.py#L541

Maybe we should improve the error message?

**Comment by ignaciogros** [comment]
But there should be no problems editing with X.X a package created wit X.X.X... 

You can't edit with 2.1 a package created with 2.2, but the third level number change shouldn't be a problem. We agreed that before ([source](http://gros.es/ponencias/2018/jornadas-edia/grupo_de_exelearning.html)): "Cambian los números de la versiones en el Calendario (consenso: si una versión incluye algo que limite la compatibilidad hacia atrás, se salta al menos un número de segundo nivel). La 2.1.4, que tiene los JavaScript iDevices, será la 2.2. Ya está hecho el cambio en la web de eXeLearning."

Is that possible?

**Comment by JuanCasanovaSdweb** [comment]
The other day we decided that (since backwards compatibility is not possible) the new version will be 2.3.
