### ISSUE TITLE
Blank "page"

### ISSUE THREAD

**Issue by morpheusbeing** [exelearning/iteexe#368]

**Comment by morpheusbeing** [comment]
Two computers, one running Debian Testing (#1), one Debian Stretch (#2), both with same version exe. When I upload scorm package from #1, has blank page under each Topic, whereas not from package from #2. Any ideas please, or what additional information is needed.

**Comment by morpheusbeing** [comment]
![lms_issue01](https://user-images.githubusercontent.com/5505132/48679294-6af20580-ebc9-11e8-8d5b-1ffaa4464a57.png)
![issue02](https://user-images.githubusercontent.com/5505132/48679296-6d545f80-ebc9-11e8-846c-7d90434118df.png)

Screenshots showing the issue I am having.

**Comment by morpheusbeing** [comment]
I have tried SCORM 1.2 and SCORM 2004 with same result. Moodle is version 3.5.2

**Comment by ignaciogros** [comment]
Hi, @JuanCasanovaSdweb:

See [this message](http://exelearning.net/en/forums/topic/como-subir-un-paquete-scorm-para-modificarlo/#post-30307) too (similar problem: the nodes are empty when editing the SCORM file). I can send you the zip file.

**Comment by ignaciogros** [comment]
eXeLearning 2.4 will fix this. It'll be released in a few days.
