### ISSUE TITLE
Can't edit a zip from Procomún

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#369]
I'm working with master.

- Create a new elp.
- Export as 2004 and upload it to Procomún.
- Download the SCORM from Procomún and try to edit it with eXe.

You'll get a this error: "Formato de archivo incorrecto: 'identifierref'".

This should be fixed before eXe 2.3 is tested.

**Comment by ignaciogros** [comment]
If I try to edit a SCORM I created with eXe 2.2, i just get this message: "Formato de archivo incorrecto".

**Is this an eXe issue, or is it Procomún's?**

**Comment by ignaciogros** [comment]
Same result with eXeLearning 2.1.2: "Formato de archivo incorrecto". It's strange, because [you can edit this content](http://procomun.educalab.es/es/ode/view/1519042221872) (both SCORM versions), but not the attached ones.

[SCORM_Edition_Tests.zip](https://github.com/exelearning/iteexe/files/2607599/SCORM_Edition_Tests.zip)

**Comment by JuanCasanovaSdweb** [comment]
This seems actually like two things:
1. The commit from before
2. A problem with Procomún

The second one is because they are modifying the imsmanifest.xml we are uploading.
Testing with one of the packages the one that eXe creates looks like this:
```
<organizations default="eXenewPackage5bfc349623ee8596962">  
    <organization identifier="eXenewPackage5bfc349623ee8596962" structure="hierarchical">
        <title>Probando</title>
        <item identifier="ITEM-eXenewPackage5bfc349623ee8596963" isvisible="true" identifierref="RES-eXenewPackage5bfc349623ee8596964">
            <title>Inicio</title>
            <item identifier="ITEM-eXenewPackage5bfc349623ee8596975" isvisible="true" identifierref="RES-eXenewPackage5bfc349623ee8596976">
                <title>Tema</title>
            </item>
        </item>
    </organization>
</organizations>
```

And the one downloaded from Procomún like this:

```
<organizations default="eXenewPackage5b28f14823ec49e7492">
    <organization identifier="eXenewPackage5b28f14823ec49e7492" structure="hierarchical">
        <title>Probando</title>
        <item identifier="ITEM-eXenewPackage5b28f14823ec49e7493" isvisible="true">
            <title>Inicio</title>
            <item identifier="ITEM-eXenewPackage5b28f14823ec49e7494" identifierref="RES-eXenewPackage5b28f14823ec49e7495" isvisible="true">
                <title>&lt;-</title>
            </item>
            <item identifier="ITEM-eXenewPackage5b28f14823ec49e74a6" identifierref="RES-eXenewPackage5b28f14823ec49e74a7" isvisible="true">
                <title>Tema</title>
            </item>
        </item>
    </organization>
</organizations>
```

The problem is that the first item from Procomún doesn't have a `identifierref` and eXe expects all items to have one.

We should look into the standard to see which way is correct.

**Comment by ignaciogros** [comment]
I upload this [this SCORM](https://github.com/exelearning/iteexe/files/2623785/scorm.zip) to Procomún. Then I download it (in 1.2 and 2004), but I can't edit it. It has 2 JavaScript iDevices and a "File Attachments" one. That didn't happen with other packages (I edited another one a few minutes before).

**Comment by ignaciogros** [comment]
It works for me now, at least with the elp files I just published, but It's sill not working with the attached elp.

@JuanCasanovaSdweb: 

Did you check the SCORM specification? Thanks.

**Comment by ignaciogros** [comment]
I just published two SCORM files: http://nube.gros.es/index.php/s/UFMsX1PAV6vNMjG (pass: GitHubIssue)

**I could edit 1.2, but not 2004.** This is important, because some SCORM files in Procomún might not be editable.

**Comment by ignaciogros** [comment]
@david-puente:

Is Procomún's or eXe's problem? Please close this issue if it's Procomún's. Thank you.

**Comment by JuanPerezSdweb** [comment]
Hi!!

We have downloaded a SCORM from Procomún and opened it without problem.

Can you try if so?

Thank you.

**Comment by ignaciogros** [comment]
- Go to http://nube.gros.es/index.php/s/UFMsX1PAV6vNMjG (pass: GitHubIssue) and download the 2004. 
- Publish it in Procomún.
- Download it as 2004 from Procomún (the result is the scorm-2004-descargado-de-procomun.zip that you'll find in that folder).
- Try to open the downloaded file with eXe.

I think it's a Procomún's problem. Please close the issue if you agree. If you know what difference is making that fail, please tell us so it can be fixed as soon as possible.

Thank you!

**Comment by JuanPerezSdweb** [comment]
It seems a Procomún's problem. In the downloaded SCORM are not the files necessaries to edit this SCORM in the eXe.
