### ISSUE TITLE
Uncaught error: No clientHandleId in request

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#373]
Ugly "No clientHandleId in request" message.

- Open eXe.
- Right click on the content area and click con "Reload frame".

I know it's a strange thing to do, but, could eXe handle that error?

This might be a FR. Please add the "FR" label if you think so.

**Comment by Javiobcn** [comment]
I have been looking at this issue. One possible solution is to disable the context menu using javascript. Although this does not correct the problem, it does prevent the frame from being reloaded and therefore the error does not occur.

I have done a test adding in the file
/exe/webui/authoringpage.py line 194

html += '<script>$("html").contextmenu(function(e) {e.preventDefault();});</script>' .

This doesn't seem to affect the functionality, everything still behaves the same but now when you right click on the authoring iframe, the context menu doesn't show making it impossible to reload it or open it in another window.

**Comment by ignaciogros** [comment]
It's quite a strange thing to do and We can't disable the right click menu.

Won't fix for the moment.
