### ISSUE TITLE
Instalación en windows no muestra imagen

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#38]
El instalador de windows no muestra la imagen installs>windows>win.bmp

**Comment by ignaciogros** [comment]
La única referencia a win.bmp está en el archivo exe.nsi.

El archivo make.py hace referencia a splashb.jpg, que no se encuentra en la aplicación (ni se encontraba en la versión de eXeLearning.org).

No sé si es suficiente con modificar el valor en make.py. En cualquier caso, hay que generar un instalador para hacer las pruebas.

Pedro:

Te asigno la incidencia, que tú sabes bien cómo funciona esa parte.

**Comment by antoniomonjef** [comment]
A ver
Es debido a que toqué yo la imagen y es algo así como la codificación del bmp que ha cambiado. Pasó lo mismo en otro momento

**Comment by ignaciogros** [comment]
Entendido.

Cambio la codificación del archivo:

https://github.com/exelearning/iteexe/commit/0c0f9299cbf4ee706b83aa0d795ae350113ec17e

Habrá que comprobar si se ve bien tras generar el instalador.

**Comment by antoniomonjef** [comment]
Todo bien.
Muchas gracias! Cerramos
