### ISSUE TITLE
Can't export elp

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#380]
We should fix this as soon as possible.

[Reported by "cybertaf" in the forums](http://exelearning.net/en/forums/topic/no-html-export-in-2-3/). Another user reports [a similar error](http://exelearning.net/en/forums/topic/no-exporta-paquete-ims/).

Try to export [this elp](https://drive.google.com/open?id=15BLgQ7dmeQOJb75ADjNGpLZQWyCJ2CMG) without changing its metadata. 

I get this message:

> 
> Exception: TypeError: field is null
> Caused by script:eXe.app.getController("Toolbar").packagePropertiesCompletion('webSite','C:\\ ... .elp','pp_license|empty');
> 

exe.log says:

> 
> ... exe.application ERROR Traceback (most recent call last):
> Failure: <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.

**Comment by jm-andonegi** [comment]
Apparently Licence is not correctly saved. [See forum thread](http://exelearning.net/eu/forums/topic/no-html-export-in-2-3/).

**Comment by ignaciogros** [comment]
Thanks, @jm-andonegi!

**Comment by ignaciogros** [comment]
Hi @jm-andonegi:

@david-puente found the problem. It's the "Create package compatible with old eXe versions?" option. New issue: #382. 

Shall we remove that option? Please give your opinion in #382.

**Comment by ignaciogros** [comment]
@david-puente: That doesn't seem to be the problem in [this case](http://exelearning.net/en/forums/topic/no-html-export-in-2-3/#post-30545). Could you check that too, please?

**Comment by ignaciogros** [comment]
I reopen the issue because of a user's comment: http://exelearning.net/en/forums/topic/un-clasico-error-3-fallo-al-guardar-proyecto/

He can't save. Check the path and the name of his elp... Is it the same case?

**Comment by ignaciogros** [comment]
I created an elp with that name and a similar path and exported. It worked. I'm working on Windows. I think it's fixed.
