### ISSUE TITLE
export elp to SCORM problems

### ISSUE THREAD

**Issue by jgutval** [exelearning/iteexe#381]
I have created a new course in elp format. Now I am trying to export to SCORM and I can not do it. I am working with ExELearning 2.3.1 and windows 10. Chrome

**Comment by JuanCasanovaSdweb** [comment]
Hi @jgutval 
In order to help you, we will need the following:

- A detailed explanation of your issue (if you can include a screenshot that would be super helpfull).

- If you can, attach the elp that is causing the problem.

**Comment by jgutval** [comment]
Thank for your help. I finally installed an old version and I have to create this lesson with the older version. But it doesn´t matter. I will go on working with this version. Perhaps it is a problem with my Windows10 or another situation.
Thank you again for your help.
Kind regards

**Comment by JuanCasanovaSdweb** [comment]
We are glad that you could find a solution to your problem.
