### ISSUE TITLE
Remove the compatibility with old versions?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#382]
If the "Create package compatible with old eXe versions?" is checked, the license won't be saved. See also #380 and [this forum thread](http://exelearning.net/forums/topic/no-html-export-in-2-3/#post-30512) for details.

[Test elp file](gros.es/tests/markdown.elp).

**Shall we remove that option?** I think so, because we decided that second level versions won't have to be compatible. Otherwise we'll need a lot of time to do that.

**Comment by jrfern** [comment]
I believe backwards compatibility never really worked, just sort of, in some very limited cases. But users are going to need some explanation: "This package was created with version X of eXe, you should update to be able to open it" or something similar. My humble opinion.

**Comment by jm-andonegi** [comment]
I agree with Juan Rafael.

Anyway, just a silly question. Is it really mandatory to reject a file of a newer version? I mean, if every single new feature/metadata will invalidate opening the file with previous versions many users will feel very disappointed. Of course, user should be warned and strongly encouraged to update the file (and ideally offer automatic update) but, isn't it possible to ignore data from new versions (assuming the risk of loosing some information).

May be catching exceptions with the appropriate warning is better for many users than feeling they can not open the file.

**Comment by ignaciogros** [comment]
Thanks for answering. We also received 3 opinions via email. All of them say that as it's not working, we should remove that option.

This is what we'll do:

1. Remove the option.
2. eXe should try to open all the packages (even those created with newer versions). If the elp is not compatible, it'll show this message: This package was created with a newer version of eXe, you should update to be able to open it.

OK? Thanks...

**Comment by ignaciogros** [comment]
eXe should not ask for confirmation (not even warn) when trying to open a package created with an older version. It should just open the elp.
