### ISSUE TITLE
Por qué aparece esto en las 2 versiones instaladas? Mac-Chrome

### ISSUE THREAD

**Issue by frasco2001** [exelearning/iteexe#384]
![image](https://user-images.githubusercontent.com/15019325/52539537-73e51400-2d7f-11e9-9504-441793ec143b.png)

**Comment by ignaciogros** [comment]
Parece un problema con los Estilos. Por favor, dinos qué versión de eXe usas, y si usas un Estilo propio, adjunta un zip si puedes.

Si no tienes Estilos o iDevices propios, puedes probar borrando la carpeta .exe. [Aquí se explica cómo hacerlo](http://exelearning.net/problemas-al-ejecutar-exelearning/).

Gracias por avisar.
