### ISSUE TITLE
Links in images not working

### ISSUE THREAD

**Issue by guerreroherrero** [exelearning/iteexe#386]
Dear friends,

Since I installed the 2.3.1 version I haven't been able to apply links to images. Text links work fine, but links in images simply don't work. Can you help me, please? Thank you.

**Comment by ignaciogros** [comment]
Could you tell us what browser (and version) are you using? Which is your Operating System?

What editor version are you using (Advanced user - Tools - Preferences - Advanced)?

I just added a link in an image in Windows with Chrome, Firefox and IE11 with TinyMCE 4 and it worked fine.

Thanks!

**Comment by guerreroherrero** [comment]
Thank you for your quick answer.

I just discovered that this happens in images in which I include a licence. If I upload the image and then add a link to the image, it works fine. However, as soon as I add a licence for the image, the link is removed and you cannot add it again. It looks as if licence and link cannot coexist for some reason.
I'm using W10, Chrome browser (latest version), Exe 2.3.1 with Advanced user on and with TinyMCE 4.

**Comment by ignaciogros** [comment]
Try replacing this JS file, please: /scripts/tinymce_4/js/tinymce/plugins/exeimage/plugin.min.js

[plugin.min.js.zip](https://github.com/exelearning/iteexe/files/3223467/plugin.min.js.zip)

I'd like to test that well before including it in eXe to avoid other problems.

Thanks!

**Comment by guerreroherrero** [comment]
Ignacio, I replaced the plugin.min.js file in that location, but unfortunately it didn't solve the problem. As soon as I added the copyright information and the link to the source page for the image, the original link of that image disappeared. 

Thank you!

**Comment by ignaciogros** [comment]
Thanks... My fault. You'll have to replace 2 files. I forgot to attach the second one (exelink/plugin.min.js)

[issue-386.zip](https://github.com/exelearning/iteexe/files/3235868/issue-386.zip)

**Comment by ignaciogros** [comment]
Thanks, @guerreroherrero.

I forgot to attach the second file. New zip:

[issue-386-b.zip](https://github.com/exelearning/iteexe/files/3236122/issue-386-b.zip)

A new version of eXe will be released very soon, but this might not be in it because we'd like to test it properly. We know that the Attribution tab behavior can improve, but there are more important issues now and we need to fix them before.

**Comment by guerreroherrero** [comment]
Thanks, Ignacio. I tried again adding the new file to the exelink folder, but it didn't solve the problem, either. 
The new version of eXe looks great -some excellent new features!!! Unfortunately it will still have this problem with the links and the Attribution data of images. 

Thanks for your help and congratulations for the good job!!!

**Comment by ignaciogros** [comment]
> I tried again adding the new file to the exelink folder [...]

Did you replace the other file too? I changed some things there too...

Thanks a lot for your comments :-)

**Comment by guerreroherrero** [comment]
Thank you, @ignaciogros !!! I thought there was no change in the first file. Now it works fine!!! I hope this gets on time for the 2.4 version. If it needs testing, I can do it. 

Thanks a lot!!!

**Comment by ignaciogros** [comment]
> I hope this gets on time for the 2.4 version.

It will :-) 

Thank you!
