### ISSUE TITLE
Cyrillic symbols in filenames

### ISSUE THREAD

**Issue by kvazimode** [exelearning/iteexe#387]
Exporting into web site (self-contained folder) makes all the cyrillic words and symbols of navigation tree converted into lower dash.
If there is one cyrillic word in the name of page, eXe makes html document with name '_.html'. If there is another page, wich name consists of one cyrillic word, eXe will add digit after dash - '_0.html'. If there are two pages, wich names consist of one cyrillic word and digit, eXe will add digit after digit - '_10.html'. And so on. 
That makes completely unreadable filenames.

**Comment by ignaciogros** [comment]
Hi @kvazimode,

We talked about that and we decided not to do it right now. There are too many things to improve and develop, that might cause other difficulties, and it's not a bug...

Please create a pull request if you make that work. If it's interesting for eXe it can be included.

**Thank you for your suggestion!**
