### ISSUE TITLE
Style Manager: Untranslated strings.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#389]
When eXe is in Spanish, some of the strings of the "Style Manager" are still in English: Styles repository, Import style, Show properties of style, Delete style...

**Comment by jrfern** [comment]
I can confirm the problem, even after updating the PO file and translating it. Somehow the string in the implied file or files are not extracted:

> $ grep -R "List of styles in your system" *
> exe/jsui/scripts/app/view/forms/StyleManagerPanel.js:            title: _("List of styles in your system"),
> Coincidencia en el fichero binario exe/locale_unsupported/tg/LC_MESSAGES/exe.mo
> exe/locale_unsupported/tg/LC_MESSAGES/exe.po:msgid "List of styles in your system"

I can't see what's wrong, because we have a line
> [javascript: exe/jsui/**.js]
in pybabel.conf.

Someone else please take a look.
