### ISSUE TITLE
Comprobar si están los metadatos necesarios para publicación en procomún

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#39]
Sería que saltase un mensaje de alerta si no están todos los metadatos necesarios para publicar en procomún

**Comment by ignaciogros** [comment]
¿Habéis detectado algún problema en la publicación? Si no, ¿podemos cerrar la incidencia? Si sabéis de algún problema describidlo y asignádselo a @JuanCasanovaSdweb, por favor.

**Comment by miguelpereiraite** [comment]
Los problemas están en la publicación desde Windows (creo que ya lo hemos comentado). 
Emergya (Desarrollo Procomún) ya tiene la información y se supone que lo están estudiando.

**Comment by ignaciogros** [comment]
Esto formará parte de eXeLearning 2.2.1 Data. Cambio a FR.

**Comment by ignaciogros** [comment]
Ya resuelto en versión anteriores. La publicación directa no funciona, pero por otros motivos (Procomún ya no permite el uso de IFRAME y eXe se va a adaptar al nuevo modelo). Pero la validación funciona.
