### ISSUE TITLE
No se puede exportar en formato IMS desde el idioma español

### ISSUE THREAD

**Issue by Bernardo-Parra** [exelearning/iteexe#390]
Buenos días, cuando quiero exportar a un archivo IMS no pasa absolutamente nada, necesito ayuda urgente por favor, este es el enlace de mi proyecto:
http://localhost:51236/Qumica_general

**Comment by ignaciogros** [comment]
El enlace que nos has pasado es local (de tu equipo). Por favor, adjunta el elp. De todas formas, **comprueba antes si tiene tildes u otros caracteres especiales en el nombre del archivo o la ruta**. Si es así, prueba quitándolos. Ese fallo estará resuelto en la próxima versión.

**Comment by david-puente** [comment]
Hemos visto al intentar realizar una exportación de un elp creado con una versión anterior del programa, se intentaba acceder a una propiedad que no existía. Hemos añadido una comprobación para solucionar esto. Si el error persiste, adjunta el fichero para poder probarlo.
