### ISSUE TITLE
apt-get update

### ISSUE THREAD

**Issue by arashsoftco** [exelearning/iteexe#395]
hi 
this problem when : ### apt-get update
:

`
arashsoft@arashsoft-X456UR:~$ sudo apt-get update
Hit:1 http://ir.archive.ubuntu.com/ubuntu disco InRelease
Hit:2 http://ir.archive.ubuntu.com/ubuntu disco-updates InRelease        
Hit:3 http://ir.archive.ubuntu.com/ubuntu disco-backports InRelease      
Hit:4 http://security.ubuntu.com/ubuntu disco-security InRelease
Hit:5 http://ppa.launchpad.net/morphis/anbox-support/ubuntu cosmic InRelease
Ign:6 http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco InRelease
Hit:7 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu disco InRelease
Ign:8 http://ppa.launchpad.net/slgobinath/uget-chrome-wrapper/ubuntu disco InRelease
Err:9 http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Err:10 http://ppa.launchpad.net/slgobinath/uget-chrome-wrapper/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/slgobinath/uget-chrome-wrapper/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by david-puente** [comment]
You have problems with the repositories in your system. In the log there are no problems related to eteexe. Try to disable de repositories that trigger these errors.
