### ISSUE TITLE
URL iDevice doesn't work properly

### ISSUE THREAD

**Issue by maxezek** [exelearning/iteexe#397]
eXe version intef-exe (3:2.3.1) 

When I use external web idevice some times works but it frequenly doesn't work. It is possible that a web load it in eXe but it doesn't load in a web exported.

This is an example:
[https://www.educa2.madrid.org/web/educamadrid/principal/files/1c0dec70-1009-470f-86c8-84cd4e1c2837/tarea34.01/index.html](https://www.educa2.madrid.org/web/educamadrid/principal/files/1c0dec70-1009-470f-86c8-84cd4e1c2837/tarea34.01/index.html)

This embebed web works [https://raices.madrid.org/raiz_app/jsp/portal/portalraices.html](https://raices.madrid.org/raiz_app/jsp/portal/portalraices.html)

but this one doesn't work [http://raices.educa.madrid.org/presentacion/](http://raices.educa.madrid.org/presentacion/)

This fail is very common with several URL

My source:

[tarea34.01.elp.zip](https://github.com/exelearning/iteexe/files/3113872/tarea34.01.elp.zip)

**Comment by ignaciogros** [comment]
It's a security issue. You can't insert HTTP content in an HTTPS page. 

Raíces tiene https. Si añades la ese en el segundo ejemplo se soluciona.

Saludos.

**Comment by maxezek** [comment]
Hola Ignacio.

Lo sé pero no está indicado. Se requiere que al insertar la URL advierta de esa situación.

Uno de los puntos fuertes de eXe es su sencillez. Un usuario estándar no sabrá eso y se desperará.

Yo lo pondría directamente cuando te solicita la URL un mensaje con esa situación.

**Comment by ignaciogros** [comment]
We add this message to the External Web Site iDevice: **Remember that HTTP pages cannot be included into HTTPS websites.**
You'll also have to confirm before adding an http URL using the media plugin for TinyMCE.
Thanks for your suggestion!
