### ISSUE TITLE
Nuevos campos en la pestaña propiedades

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#40]
Falta por definir pero corresponderían a área y nivel.
Lo apunto para que no se me olvide... es más un FR ¿Cómo solucionaremos esto de los FR?

**Comment by pedropena** [comment]
Creo que mejor que un milestone FR, sería una etiqueta FR.

**Comment by ignaciogros** [comment]
Cierro la petición de momento porque, en cualquier caso, serían mejoras a incorporar cuando se renueve el código de la aplicación. Está previsto hacerlo, pero todavía no hay fecha.
