### ISSUE TITLE
Error de formato en exeLearning al abrir

### ISSUE THREAD

**Issue by Ulazia** [exelearning/iteexe#403]
He descargado desde AGREGA "Zuzenak eta angeluak planoan" en formato SCORM 2004 y al intentar Abrirlo en eXeLearning me da "Formato de archivo incorrecto"  ?? Me podrías indicar que hago mal ? Gracias

http://agrega.educacion.es/buscador2/DescargarODECU/DescargarODECU.do?identificadorODE=es_2012061433_9034934&idioma=eu&tipoLayoutBuscador=BUSCADOR&mostrarVuelta=true&areaCurricularBusqueda=&tieneIdentidadFederada=false&nodoOrigen=&idLicencia=6.2.13

**Comment by ignaciogros** [comment]
Es que ese SCORM no está generado con eXeLearning. Con eXe se pueden editar los SCORM generados con la aplicación, siempre que la casilla "Crear un exportado editable" de la pestaña Propiedades - Exportar esté marcada (lo está por defecto en las últimas versiones).

**Comment by Ulazia** [comment]
Ostras, esto si q no me lo esperaba. O sea q depende de la aplicacion q la
generó ? Y donde queda el SCORM en cualquiera de sus modalidades como
'estandar' q garantiza la interoperabilidad ? Algo no encaja no ?

**Comment by ignaciogros** [comment]
Es un estándar de empaquetado para compartir los contenidos, pero el SCORM puede tener cualquier tipo de contenido y estructura. Sería difícil, si no imposible, crear una herramienta que permita editar cualquier cosa. eXe sirve para generar páginas/sitios web, que puedes exportar en formato SCORM y en otros formatos. No es una herramienta de edición de SCORM en general. Puedes probar la opción "Importar curso", pero vista la complejidad del contenido, no creo que te sirva.
