### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#404]
Starting eXe from the commandline, I get this

> $ Welcome to eXe: the EXtremely Easy to use eLearning authoring tool
> [edited]/iteexe/exe/webui/common.py:1280: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
> 
> The code that caused this warning is on line 1280 of the file [edited]/iteexe/exe/webui/common.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.
> 
>   soup = BeautifulSoup(html)

So please add the additional argument.

**Comment by david-puente** [comment]
Can you tell us what operating system you use? 
I tried it on Ubuntu 16.04 and macOS Mojave and I can't reproduce this behavior.

**Comment by ignaciogros** [comment]
I see a similar message in exe.log too (master + Windows). It's just a warning, but if it can be fixed... Thanks!
