### ISSUE TITLE
Create a canvas template for tinymce

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#417]
I see all EDIA's REAs use an external canvas (e.g. http://cedec.intef.es/proyecto-edia-ingles-secundaria-rea-festivities-around-the-world/), but this is just a tree-column text with fixed sections and some properties for the headings. It looks easy to create a template for creating this sort of cavases, so that they can be included in the REA.

Or a new "Project Canvas" iDevice might be created.

Obviously this is an idea, just a feature request.

**Comment by ignaciogros** [comment]
We'll include new templates for TinyMCE (ULHI's and maybe more). I note down your suggestion too. Thanks!
