### ISSUE TITLE
Eliminación de texto entre dos enlaces

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#42]
Al modificar la url de un enlace, desaparece el texto entre el enlace y el siguiente enlace...
Esto es bloqueante
Adjunto url de elp: https://www.dropbox.com/s/i41pvj554o55x6c/elementos_de_geometria_en_colaboracion_v10.elp?dl=0

y url del vídeo: https://www.youtube.com/watch?v=sE2IqXyaTQk&feature=youtu.be

**Comment by antoniomonjef** [comment]
En realidad parece que también elimina el texto existente entre el fin de la etiqueta `</a>` y el comienzo de la siguiente etiqueta...

**Comment by ignaciogros** [comment]
**No consigo reproducirlo.** Puede que el problema se deba a la URL que estás pegando (a la que sustituye a la anterior).

**Por favor, adjunta un zip con:**

1. Un txt con el código HTML original del iDevice.
2. Un txt con el enlace final (la dirección a la que quieres que dirija el enlace con el texto "Procomún").

Ubuntu/Chromium, ¿verdad?

Lo miraré mañana a primera hora.

Gracias.

**Comment by ignaciogros** [comment]
No necesito esos txt, Antonio. Ya puedo reproducir el fallo. Gracias.

**Comment by ignaciogros** [comment]
Fixed (1bb4f0fffd8e2cd4e54ecb835a2f00ff9095d69c).

Could you check it? Thanks...

**Comment by antoniomonjef** [comment]
ok, fixed
