### ISSUE TITLE
exe_do fails if sys.stdout.encoding is None

### ISSUE THREAD

**Issue by dragondave** [exelearning/iteexe#425]
If, for example, exe_do is invoked via `subprocess.run()`, sys.stdout.encoding may be None; this causes exe_do to crash:

```
Traceback (most recent call last):
  File "/usr/bin/exe_do", line 176, in <module>
    parser = prepareParser()
  File "/usr/bin/exe_do", line 70, in prepareParser
    help:\n%prog -h").encode(sys.stdout.encoding)
TypeError: encode() argument 1 must be string, not None
```

This can be worked around by setting the `PYTHONIOENCODING` environment variable to `utf-8`:

```
my_env = os.environ.copy()
my_env["PYTHONIOENCODING"] = "utf-8"
output = subprocess.run(["exe_do", "--export", "in.elp", "out.zip"],
    stdout = PIPE,
    stderr = PIPE,
    env = my_env)
```

I would recommend setting a variable and using that instead of sys.stdout.encoding directly:
e.g. 
```
ENCODING = sys.stdout.encoding or "utf-8"
...
usage = _("...").encode(ENCODING)
```

It probably also fails if output is redirected, etc: see http://www.macfreek.nl/memory/Encoding_of_Python_stdout

**Comment by ignaciogros** [comment]
We mark this as FR. Thank you, @dragondave.
