### ISSUE TITLE
The SCORM Quiz does not show the correct answers to the student

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#432]
This user reports a different behaviour in SCORM comparing to older versions.

Should SCORM test show somehow the correct answer? Right now it only shows the score.

**Comment by ignaciogros** [comment]
The user says in [the forums](http://exelearning.net/en/forums/topic/resultados-cuestionario-para-el-alumno/#post-31420) that the SCORM was not created with eXeLearning. Thanks for the revision, @jm-andonegi!
