### ISSUE TITLE
eXe 2.4.2 link to other node

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#437]
[This forum thread](http://exelearning.net/eu/forums/topic/exe-2-4-2-link-to-other-node/) relates problems with internal links. I have not been able to find the nodes in the Insert link window (See attached image).

![firefox_2019-09-29_14-43-45](https://user-images.githubusercontent.com/11529013/65832699-aa987c00-e2c7-11e9-8786-ab37875e032e.png)

**Comment by ignaciogros** [comment]
Duplicated. Already closed. See #431 Thanks, @jm-andonegi!
