### ISSUE TITLE
Modificado: el file picker sólo muestra los archivos que caben en la ventana.

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#44]
Los archivos .zip no se ven al navegar con el file picker. 

Prueba hecha con el la versión beta del 2.1

**Comment by antoniomonjef** [comment]
UBUNTU + chrome los veo
Windows 7 + chrome los veo
Desplegando la opción Todos los archivos ¿en dónde se da ese comportamiento?

**Comment by jm-andonegi** [comment]
Prueba hecha con Windows 10 y con el botón adjuntar archivo ([Ver vídeo](https://www.youtube.com/watch?v=4WhhpAJLtjo&feature=youtu.be)).

**Comment by jm-andonegi** [comment]
Corrijo: el problema no es que no se vean los .zip. El problema es que sólo se muestran los archivos que caben en la pantalla y no se puede acceder a los demás. En este caso, entre carpetas y archivos, en pantalla sólo caben los ocho primeros.

Prueba hecha en Firefox 45

**Comment by jm-andonegi** [comment]
Amplío información: haciendo zoom (Ctrl-) y agrandando el tamaño de la ventana del File Picker se puede acceder a todos los archivos. Pace como si calculara mal el tamaño de la ventana de archivos, de modo que el scroll no funciona correctamente.

En Chrome funciona bien.

**Comment by ignaciogros** [comment]
En Windows 7 con Firefox 45 funciona bien. No tengo posibilidad de probar ahora en Windows 10.

**Comment by pedropena** [comment]
Tras muchas pruebas con Windows 10 y Firefox 45.0.2, con diferentes resoluciones de pantalla, no he sido capaz de replicar. Ayer salió la versión 46 y tampoco me ocurre el problema.

¿Puedes probar a replicar en Firefox 46, José Miguel?

**Comment by ignaciogros** [comment]
He probado con FF 46 en Windows 7 y funciona bien.

**Comment by jm-andonegi** [comment]
He actualizado a Firefox 46 y el problema ha desaparecido.
