### ISSUE TITLE
Import XLIFF is not working

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#442]
I try to import an XLIFF file I just exported, and I get this error:

```
<type 'exceptions.TypeError'>: cannot concatenate 'str' and 'tuple' objects [...]
defer.py, line 107 in maybeDeferred
```

I don't know if I'm doing it properly. Does that work for you, @jmandonegi? Did it work before?

@david-puente: If we can't fix that now, could eXe handle the error to display a readable message?

Thank you.

**Comment by jm-andonegi** [comment]
Same for me...
[See video](https://exelearning.euskaldunak.eus/exelearning/pruebas_xliff/error_xliff.mp4)

**Comment by ignaciogros** [comment]
Thanks, @jm-andonegi.
I tried it in eXe 2.4 and it fails too. 
Then I tried eXe 2.3.1. It works there!
@david-puente? Thank you.
