### ISSUE TITLE
Error previewing project loaded from local

### ISSUE THREAD

**Issue by arpablos** [exelearning/iteexe#452]
When we load a project from local and try to preview it, it throws the error:
```
<type 'exceptions.UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xc1 in position 9: ordinal not in range(128)

/home/app/twisted/internet/defer.py, line 107 in maybeDeferred
...
```

**Comment by arpablos** [comment]
Same in Export

**Comment by JuanPerezSdweb** [comment]
Hello,

We have tested it and it works correctly.
Can you give us more information or send us the elp that gives you problems?

**Comment by arpablos** [comment]
The problem was related with spanish accent marks in the filename. It works if don't use them.
