### ISSUE TITLE
The default server configuration does not allow loading large ELPs

### ISSUE THREAD

**Issue by arpablos** [exelearning/iteexe#453]
When you try to load a relatively large project (more than 20MB), the server does not respond. It stays frozen in "Uploading file".

**Comment by JuanPerezSdweb** [comment]
We have tested uploading heavy files and we had no problems.
Can you send us a package that you cannot upload?

**Comment by arpablos** [comment]
Of course.

You can download here: [https://we.tl/t-yFp0YmPTWZ](https://we.tl/t-yFp0YmPTWZ)

**Comment by JuanPerezSdweb** [comment]
Hi, Pablo.

The problem is located in the file name. You must use ASCII standard characters.
We will make a patch to solve the problem replacing not standard characters on the file upload.

**Comment by arpablos** [comment]
I have changed the file name to _**BG.elp**_ and the problem persist on our installation.
