### ISSUE TITLE
FR: Minify JS files when exporting

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#46]
It'd de good to work with non-minified JavaScript files (common.js and other JavaScript files to export) and minify them when exporting. It'd be easier for developers and for those users who want to make changes.

**Comment by jrfern** [comment]
I think I agree: readable js in the source, and minified when used (esp. through internet). 
Just to remind there's a third "usage situation":  the version to include when packaging eXe. As all packagers compress the files,  my opinion is that the readable sources should be used. Which is what's being done at the moment.
Just in case someone forgets.

**Comment by ignaciogros** [comment]
It's OK to have all those files unminified when installing eXe, but it'd be better to minify them (even to combine some SCRIPTS in a single file) to improve performance if eXe's to work online.

This task is about compressing some files while exporting, but we should consider all that too for the online version.

Thanks for the reminder!

**Comment by ignaciogros** [comment]
Done: 3da6320446c0597fff1b860680d0821b5e23f93d
