### ISSUE TITLE
i18n: Wrong HTML symbol

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#461]
The % sign HTML symbol is &**percnt**;

It's been changed to &**percent**; in some translations (see es.js).

Thank you!

**Comment by jrfern** [comment]
Accepted. Anyway I won't modify the sources with this and another bug discovered by Alexey Loginov until the present translation cycle is over.

**Comment by jrfern** [comment]
Fixed the PO files. @ignaciogros, please check and close if convenient.
