### ISSUE TITLE
JavaScript iDevice files. 404 errors y HTML.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#462]
I created an elp in eXe 2.3.1 with an ABP Task iDevice.
I exported it with a later version (2.4+).
These files are still in the HTML,: pbl-tools.js, pbl-tools.css
But they're not part of the iDevice any more, so you get 404 errors.
Should the iDevice files be in contentv3.xml and content.data?

**Comment by JuanPerezSdweb** [comment]
JsIdevices resources could be removed from contentv3.xml and content.data causing them to be dynamically loaded from the export and edit directory.
This is something that can be implemented in this version but removing references in old elps doesn't seem like a good idea.
