### ISSUE TITLE
SCORM 2004 does not register activity.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#465]
Test files (both created with master): [SCORM 1.2](http://gros.es/tests/cuatro-nodos-1.2.zip), [SCORM 2004](http://gros.es/tests/cuatro-nodos-2004.zip).

Publish 2004 in Moodle. Read the pages and complete the SCORM activities. You'll see that the activity is not registered. Only the first score is. It's been like that for a long time (I tried with SCORM packages created with eXe 2.3.1 with the same results).

SCORM 1.2 works. 

Both zip files have their elp inside.

**Comment by ignaciogros** [comment]
Related topic in the forums: https://exelearning.net/en/forums/topic/notas-de-quiz-scorm-hacia-moodle/

**Comment by ManuelMayoSdweb** [comment]
There are some errors in the SCORM 2004 functions of eXeLearning, but they do not seem to be the cause of this problem. Apparently Moodle does not fully support SCORM 2004 natively (https://danmarsden.com/blog/2013/05/06/stopping-work-on-scorm-2004).

The SCORM Cloud platform (https://cloud.scorm.com) is compatible with SCORM 2004 and seems to record the activity correctly.

**Comment by ignaciogros** [comment]
Thanks, @ManuelMayoSdweb!

I close because I assume that the SCORM 2004 generated with eXe are valid. Please reopen if I'm wrong.
