### ISSUE TITLE
Error when opening a template

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#467]
* Open the attached elp.
* Save it as a template.
* Try to open the template (File - New - Template).

I get this error (2.5 - Windows 7): 

```
<type 'exceptions.KeyError'>: '0'
twisted\internet\defer.pyc, line 107 in maybeDeferred
exe\jsui\mainpage.pyc, line 151 in renderHTTP
<type 'exceptions.KeyError'>: '0'
```

No additional information in exe.log

[test.zip](https://github.com/exelearning/iteexe/files/4121524/test.zip)

**Comment by ManuelMayoSdweb** [comment]
I cannot replicate the error. Neither in Ubuntu 16.04 nor in Windows 7. Neither with the installable versions nor with the current Github code.

Can there be anything else that we have not taken into account?
