### ISSUE TITLE
eXe in MacOS 10.14.2 (Mojave) does not open elp files

### ISSUE THREAD

**Issue by crisurdiales** [exelearning/iteexe#469]
I've tried to open elp files created last year under High Sierra, but eXe in Mojave gives an error stating that it does not recognize the format. Is it because of the new OS? Can it be fixed somehow?

**Comment by ignaciogros** [comment]
Maybe you created it with a later version. eXe 2.5 should open an elp created with a previous version, but an old version won't open an elp created with a new one. Could it be that? If not, please attach the elp and tell us the eXe version you're trying to open it with. Thank you.
