### ISSUE TITLE
Mac + Wikipedia iDevice

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#470]
Not for eXe 2.5. 
You can't insert and article. You get a "Check the connection" warning.
See https://exelearning.net/en/forums/topic/insertar-idevice-wiki-mac/#post-32925
There are also some CSS problems, as Wikipedia's HTML code has probably changed in these years. That would be a different issue.
Maybe it's time to hide this iDevice...

**Comment by Javiobcn** [comment]
it's resolved for next version in 3fa765ea531df28792dac65e4a09e21afaad0d96
