### ISSUE TITLE
Cannot edit a SCORM from Procomún

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#473]
When you upload an editable SCORM 2004 to Procomún, and then you download it, at least these files are missing: content.data, content.xsd, contentv3.xml, imslrm.xml

This is what the [SCORM specification](https://scorm.com/scorm-explained/technical-scorm/content-packaging/) says:

> Resources should also contain a comprehensive list of all the files required for proper functionality of the resource so that they can be ported to new environments and still continue to function.

I think that those files should be listed in the SCORM (any version) manifest file so the content can still be editable.

**Comment by ManuelMayoSdweb** [comment]
Can you try uploading a SCORM 2004 to Procomún and see if it keeps the files before closing the issue, please?

**Comment by ignaciogros** [comment]
It keeps them and you can edit after downloading. Thank you!

Maybe we should include the exported files in Common Cartridge and IMS too, but notice that not all of them will be included (imslrm.xml). The most important issue is fixed anyway. Thanks.

**Comment by ManuelMayoSdweb** [comment]
I have performed a test and it seems that the **content.data** and **content.xsd** files are deleted by Procomún anyway. The only one that remains is **contentv3.xml** (Enough to be opened and edited by eXe) for being the one that has a format (.xml) allowed.

![Captura de pantalla de 2020-02-07 12-48-18](https://user-images.githubusercontent.com/59160656/74027589-c95efb80-49a8-11ea-914c-885866e0d3d9.png)

![Captura de pantalla de 2020-02-07 12-51-26](https://user-images.githubusercontent.com/59160656/74027615-cd8b1900-49a8-11ea-90ae-81b4e7d3181c.png)
