### ISSUE TITLE
Improvement proposals related to Geogebra

### ISSUE THREAD

**Issue by arpablos** [exelearning/iteexe#474]
Improvement proposals by Javier Cayetano [GSEEx] for Geogebra:

- It would be great to be able to include HTML text after the applet, as part of GeoGebra iDevice itself.
- The possibility of incorporating GeoGebra activities from the tinyMCE editor could be studied (similar to how an FX can be added). 
- Fortunately, the warning "The activity included in the button must be the last GeoGebra activity on the page, or it will not work." It is no longer necessary. The restriction of a single evaluable activity per node is necessary, of course (regardless of whether it is GeoGebra, QuExt or questionnaire).

**Comment by ignaciogros** [comment]
I closed the issue because the 2 requests are done. The TinyMCE plugin will be a different one. We can't do it right now, but we take note of it. Thanks for the idea!
