### ISSUE TITLE
Audio recorder and JS Player: Can't get the audio length

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#476]
Insert an audio with the new "Audio recorder" plugin for TinyMCE with the "JavaScript player" option checked.

You'll see that the player can't get the audio length until you play it up to the end, but it gets the length of other webm files. Could the problem be in the webm file itself? Could that information be in the file header? If the problem's not there, please just assign me the issue. Thanks.

Screenshot (only the first one's been recorded with the plugin):

![audio_NaN_error](https://user-images.githubusercontent.com/2928868/75090102-eaeee400-555f-11ea-97cc-72d016911091.png)

**Comment by ManuelMayoSdweb** [comment]
This issue appears to be related to:  https://bugs.chromium.org/p/chromium/issues/detail?id=642012.

**navigator.mediaDevices.getUserMedia** and **MediaRecorder** create WEBM files without duration metadata.

**Comment by ignaciogros** [comment]
Thanks. Could eXe get the duration and add it to the metadata after uploading the file? Maybe with ffprobe?

**Comment by ManuelMayoSdweb** [comment]
I think the easiest thing is to use the following module https://github.com/yusitnikov/fix-webm-duration to correct the duration directly in javascript after recording the audio.
