### ISSUE TITLE
Problem running exelearning on ubuntu 19.10

### ISSUE THREAD

**Issue by kadkarol** [exelearning/iteexe#477]
After installing exelearning in the ubuntu 19.10 system (kubuntu 19.10), the program will not start. This applies to deb, portable and self-installation from sources. There is always the same problem.
When I try to run exelearning, I can see the libreoffice start screen for a moment, then I get the message: 500 Internal Server Error.

**Comment by ignaciogros** [comment]
Try `sudo apt -f install` to solve dependencies problems. Related issue: #95. [Related topic in the forums](https://exelearning.net/forums/topic/problemas-exe-en-ubuntu-19-10/) (in Spanish only). I hope it helps.
