### ISSUE TITLE
Actualizar las versiones portables de eXe a la 2.1

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#48]
En la zona de descargas, las versiones portables siguen siendo la 2.0.4

Supongo que en breve tendremos la 2.1 portable, pero por si acaso lo apunto aqui

**Comment by jrfern** [comment]
On 3 May 2016 at 10:25, jm-andonegi <notifications@github.com> wrote:
>
> En la zona de descargas, las versiones portables siguen siendo la 2.0.4
>
> Supongo que en breve tendremos la 2.1 portable, pero por si acaso lo apunto aqui

Y el ppa. Please

-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by antoniomonjef** [comment]
Portables listas
PPA pendiente

**Comment by antoniomonjef** [comment]
Listas. Cierro
