### ISSUE TITLE
Can't change default browser

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#488]
See https://exelearning.net/gl/forums/topic/cambio-de-navegador/

It's not important now, but, could we handle the error? eXe could display a message when the user has not enough permissions. It'd be good to have a way to check that, so we can hide/show options, display information or instructions...

**Comment by Javiobcn** [comment]
I have tested on Windows 10 with version 2.6 and it works fine, I can browse all folders on the hard drive without any permissions error. I have been able to switch from the system default to the chrome executable located in "Program Files / google / chrome / chrome.exe", I have tried it again and it boots fine.

It could be an error in the user's installation, for example that a user with more permissions (Administrator) had installed the browser but not for all users.

We close this issue although it can be reopened later if necessary.
