### ISSUE TITLE
¿Bug en exe_do?

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#49]
Hola:
No se si esto es un bug, si exporto a scorm12 o scorm2004 el resultado es distinto si se pone o no nombre de archivo de salida.
Por ejemplo
exe_do  -x scorm12 test.elp  genera un archivo test.elp.zip válido para Agrega
exe_do -x scorm12 test.elp  test_salida genera un archivo test_salida.zip no válido para Agrega, los imsmanifest son distintos

¿Es algo buscado a propósito?

Gracias

**Comment by jm-andonegi** [comment]
Que yo recuerde, no se hizo a propósito. ¿Puedes aportar más datos? Estaría bien tener un .elp de ejemplo con las dos exportaciones y el error de validación que da Agrega (si es que da alguna pista)

**Comment by Rafav** [comment]
Hola:
Acabo de encontrar el "fallo" 
Cuando exporto y le paso un nombre de salida exe_do -x scorm12 test.elp test_salida 
el archivo no tiene .zip en el nombre
Y resulta que Agrega no trata igual cuando subo un archivo scorm con extensión .zip que sin extensión.zip

Muchas gracias
