### ISSUE TITLE
Menu de ayuda

### ISSUE THREAD

**Issue by hrauvc** [exelearning/iteexe#490]
En el modo avanzado, en el menú de ayuda, el tutorial de exeLearning muestra la versión 2.1

**Comment by ignaciogros** [comment]
Muchas gracias. Estará corregido en la próxima versión.

**Comment by ignaciogros** [comment]
Cerrado en 616b87e6ab794c8036bdff4b11def4ea32da11e1 De ahora en adelante, el enlace llevará a la página de Ayuda de la web de eXeLearning, donde se muestra, destacado, un enlace al manual.
