### ISSUE TITLE
Wikipedia iDevice. "String is too long" error.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#496]
- New elp.
- Add a Wikipedia iDevice (article in English).
- Search "Reino Unido".
- Try to save the elp.

You'll get this error: ¡ERROR AL GUARDAR! string is too long to send (1195398)

**Comment by ManuelMayoSdweb** [comment]
It is not a problem of the Wikipedia iDevice, it is a problem of all iDevices in general, we have replicated the error on several different iDevices just by entering very long texts.
In the file **twisted/spread/banana.py** the constant **SIZE_LIMIT** is set to **640 * 1024**, this is the maximum size that a variable can have when exporting the project.
A simple solution would be to increase the size of **SIZE_LIMIT**, but I'm not sure if it would be a good idea.

**Comment by Javiobcn** [comment]
It's fixed in cb17d8fb70504de95a25a56959a7b2afe296bec8
