### ISSUE TITLE
SCORM package issue

### ISSUE THREAD

**Issue by jaysuryavanshi** [exelearning/iteexe#499]
Hi,

I am using eXeLearning for e-learning content creation and it worked very well. I am facing navgiation and bookmark related issue with exported SCORM package.
I have exported SCORM with both types for e.g. SCORM1.2 and SCORM2004 and for both navigation and bookmark feature is not enabled in my production LMS 'Opigno'.
However I found that navigation works properly with out any issue in 'Moodle' instance.
Kindly let me know if I have to enable any additional setting to enable navigation and bookmark in SCORM package to work with any other LMS than 'Moodle'.

Thanks a lot.

**Comment by ignaciogros** [comment]
eXe generates valid SCORM packages, and they work with different LMS, not only with Moodle. Could you provide a link to see the errors so we can check if there's something to improve in eXe? Thank you!

**Comment by ignaciogros** [comment]
Opigno displays no navigation options. It probably accepts only single page SCORM packages. I saw no configuration options for that in the LMS. Please reopen if I'm wrong.
