### ISSUE TITLE
Problema a la hora de abrir archivos ¿puede ser debido al nombre?

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#50]
El tema está descrito en esta entrada del foro
http://exelearning.net/forums/topic/recuperar-un-archivo-elp/#post-25448

**Comment by ignaciogros** [comment]
Parece que el problema no está relacionado con eXeLearning: http://exelearning.net/forums/topic/recuperar-un-archivo-elp/#post-25537
