### ISSUE TITLE
 ePub export fails when there is a A-Z Quiz Game iDevice

### ISSUE THREAD

**Issue by ManuelMayoSdweb** [exelearning/iteexe#500]
Because of how the export to ePub works, it fails when using the iDevice _A-Z Quiz Game_ because of how it uses the **`<a>`** tag without value for **`href`**.

**Comment by ignaciogros** [comment]
Thanks @ManuelMayoSdweb!

Could you check that, @mnarvaezm? There should be no links with an empty HREF. That might be happening in other iDevices too. Thank you.

**Comment by ignaciogros** [comment]
I close this issue. See #510
