### ISSUE TITLE
Exelearning on Dockerfile

### ISSUE THREAD

**Issue by stalinbritto** [exelearning/iteexe#501]
```
Hi Team,

Anyone has Dockerfile for EXE-learning application. We want to run this app on Kubernetes.
```

**Comment by ManuelMayoSdweb** [comment]
You can find a **docker-compose.yml** file in the [ws ](https://github.com/exelearning/iteexe/tree/ws) branch (eXeOnline). 
But there is no Dockerfile in the master branch.
I hope it can help you.

**Comment by stalinbritto** [comment]
Thanks for help.
