### ISSUE TITLE
Installing EXE-Learning in Linux Server

### ISSUE THREAD

**Issue by shubhindia** [exelearning/iteexe#502]
Hi,
As I have read and from what I have found from surfing over internet this package can be installed in linux and runs on localhost. Can we access if rom other servers. Like for example I have installed it in my server so I will be accessing it via 127.0.0.1:51235 which is my localhost. But what if I want to share my app instance with someone else. I can't share it like <my_ip>:51235 because it is bind to 127.0.0.1 and not 0.0.0.0. I did change the webdriver interface to 0.0.0.0 and built the binary but not usable, still page does not load. My use case it I want to run it on server which does not have any UI.

**Comment by ignaciogros** [comment]
We're working on a multi-user version of eXe to be installed on a remote server. You can't use eXe as it is right now for that. You'll have to change some important things before: The way the users, the files and the temporary files and folders are handled, the authentication method...
We hope that the 100% online version will be available this year, but there's no date yet.
