### ISSUE TITLE
Moodle + SCORM navigation problems

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#505]
See https://exelearning.net/en/forums/topic/navigation-and-bookmark-not-working-with-scorm/#post-34272 and https://exelearning.net/en/forums/topic/no-registra-el-progreso-con-chrome-83/

Navigation problems in SCORM + Moodle.

In my tests, it works if you use the left navigation menu, but it fails when using the pagination buttons at the bottom. You get a "node is undefined" error. I got the same behavior in FF and Chrome, but in the forums they say it only fails in the last one. Is it Moodle's or eXe's problem? We should try to fix that or try to handle that error anyway.

**Comment by ignaciogros** [comment]
Important: Read [this message](https://exelearning.net/en/forums/topic/no-registra-el-progreso-con-chrome-83/#post-34350) before trying to fix this. Is it Moodle?

**Comment by ignaciogros** [comment]
**Important:** Read [this message](https://exelearning.net/en/forums/topic/navigation-and-bookmark-not-working-with-scorm/#post-34374) too. He says that **he had no problems with previous eXe versions**.

**Comment by ManuelMayoSdweb** [comment]
**About navigation problems:**
In the tests that I have done in Moodle and Scorm Cloud, both the left navigation menu and the pagination buttons at the bottom work.

**About the progress of the pages:**
It seems that the progress of the nodes is not recorded in Google Chrome.

For testing I have exported 2 different elps as SCORM 1.2 using Windows version of eXe 2.5.

**Comment by ManuelMayoSdweb** [comment]
If we enable the flag **allow-sync-xhr-in-page-dismiss** in Google Chrome, the progress is recorded correctly. In new versions of Google Chrome it is disabled by default.

More information: [chromestatus.com/feature/4664843055398912](https://www.chromestatus.com/feature/4664843055398912)

**Comment by ignaciogros** [comment]
Could we remove the beforeunload or unload from the export so everything works again? We'll have to find another way to do that. According to that link, that could be a solution. We can try them not to disable that by default, but... 
Thank you!

**Comment by ManuelMayoSdweb** [comment]
Regarding the elimination of the `beforeunload` and `onload` functions, we would have to study it, because at the moment I don't know what that change would entail.

Keep in mind that for now, the browsers that have decided to follow the path of **Disable XHR sync in page dismissal** are **Google Chrome** and **Edge** (based on the information I have been able to find).

It would also be necessary to check and limit which SCORM related issues have to do with new versions of Google Chrome and which have other causes.

The truth is that I do not know very well how to face this issue at this time. Any recommendation?

**Comment by kfern** [comment]
Hi!

Is there an estimate of when the problem can be solved?

**Comment by ignaciogros** [comment]
> Hi! Do you have an estimate of when the problem can be solved?

Not yet. Sorry.

@ManuelMayoSdweb: No good news in Moodle 3.9 or the last Chrome version. It's still failing. See https://exelearning.net/en/forums/topic/no-registra-el-progreso-con-chrome-83/#post-35569

**Comment by ignaciogros** [comment]
Check this message: https://exelearning.net/en/forums/topic/no-registra-el-progreso-con-chrome-83/#post-35580
He says that this problem is treated here: https://tracker.moodle.org/browse/MDL-68896

**Comment by ManuelMayoSdweb** [comment]
Additionally, a coworker sent me this: https://developers.google.com/web/updates/2018/07/page-lifecycle-api#the-unload-event.
Maybe this can help us if the decision is to modify the eXe code and eliminate the **unload** event.

**Comment by ignaciogros** [comment]
First we should test Moodle's solution, but I think that **we'll have to replace that event**, at least for some browsers. We'll have to provide a solution compatible with old browsers too.

**Comment by ManuelMayoSdweb** [comment]
After thinking about it and trying various solutions, so far the best solution we have found is to add `window.mod_scorm_is_window_closing = true;` in [exe/webui/scripts/SCOFunction.js](https://github.com/exelearning/iteexe/blob/master/exe/webui/scripts/SCOFunctions.js#L220), at the beginning of the **unloadPage** function.

_In case of the scorm is using unload event to request Moodle displayed in a iframe, the "global" variable "window.mod_scorm_is_window_closing" is not initializated. We got the error: "LMSInitialize failed with error code 101"_
https://tracker.moodle.org/browse/MDL-67175?focusedCommentId=802874&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-802874

**Comment by ignaciogros** [comment]
I think that this is fixed, but we still have to check how it works in the Moodle app, and try to improve Moodle's SCORM viewer so the pagination buttons don't fail, etc. See #552
