### ISSUE TITLE
The translation tools no longer work

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#508]
Since python2 is obsolete, the distributions only use python3 libraries. Therefore pybabel is a python3 only tool now. But our scripts at tools/ are python2 applications. We need to update them.

This update should be a fast one, and totally independent of the solutions for eXe, because these tools are only used when extracting and updating the translation strings, during development time.

But it's a serious and urgent issue, I can no longer update the strings.

Fragments of the error log:

> Traceback (most recent call last):
>   File "exe/put_template_strings.py", line 24, in <module>
>     from babel._compat         import StringIO
> ImportError: No module named babel._compat

>  Creating exe/jsui/scripts/i18n/tl.js
> Traceback (most recent call last):
>   File "tools/po2json.py", line 281, in <module>
>     po2json_command()
>   File "tools/po2json.py", line 277, in po2json_command
>     use_fuzzy=d.use_fuzzy, include_lib=d.include_lib)
>   File "tools/po2json.py", line 232, in compile_dir
>     use_fuzzy=use_fuzzy)
>   File "tools/po2json.py", line 199, in po2json
>     d = po2dict(file, locale, use_fuzzy=use_fuzzy)
>   File "tools/po2json.py", line 174, in po2dict
>     from babel.messages.pofile import read_po
> ImportError: No module named babel.messages.pofile

**Comment by jrfern** [comment]
Maybe we only have to update transecma (po2json)
https://github.com/nandoflorestan/bag/tree/master/bag/web

Could a developer check this?

**Comment by ignaciogros** [comment]
I change the assignment. Thank you, @jrfern. Any ideas, @ManuelMayoSdweb?

**Comment by ManuelMayoSdweb** [comment]
Temporarily you can install the babel package for python2 by following these steps:

- `curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py`
- `sudo python get-pip.py`
- `python -m pip install babel`

*Tested on Ubuntu 20.04

**Comment by jrfern** [comment]
Sorry but IMHO this hack (parche) complicates the situation and postpones the solution instead of fixing the problem. If the scripts have been updated upstream as I showed, the way to go is update our copy and test if everything works. Let's move to python3 as far as we can, and here we can. MHO.

**Comment by ManuelMayoSdweb** [comment]
I have uploaded (768ffa5087a1f027b52141f347bf1cc212b74335) a new version of the translation scripts using python 3 wherever it is currently possible. 
Can you test them and check that they work correctly?

**Comment by jrfern** [comment]
Thank you very much, @ManuelMayoSdweb .

Just one error when I launch tools/mki18n-compile_python3.sh, which it seems you have already noticed

> *** Adding template strings to generated *.po files ***
> 
> Traceback (most recent call last):
>   File "exe/put_template_strings.py", line 24, in <module>
>     from babel._compat         import StringIO
> ImportError: No module named babel._compat
> 

The line that creates the error is (the comment is yours, isn't it?)

> # Not possible at the moment using Python 3
> python exe/put_template_strings.py --standalone $tmp/locale

In exe/put_template_strings.py I can read

> from babel._compat         import StringIO
> from babel.messages.pofile import read_po, write_po

_compat.py y pofile.py existen en /usr/lib/python3/dist-packages/babel/

Hope this helps.

**Comment by ManuelMayoSdweb** [comment]
Yes, that comment in **exe/put_templat_strings.py** is mine.

The problem is that both that script and **exe/get_template_strings.py** load the Application, Package, Path and Template **eXe** modules. And that is not possible using Python 3 (as long as eXe is an application developed in Python 2)

Therefore in these cases I try to run both scripts using Python 2 ('python' command) instead of Python 3 ('python3' command)

The problem I see is that since the Babel module for Python 2 cannot be easily installed on the latest Linux distributions, extracting and compiling template text strings will be more complicated.

Maybe we could find an alternative method to do it using Python 3. But I don't know if it's worth it because I don't really know the importance of this type of text strings in translations.

**Comment by jrfern** [comment]
Oh I see. I think mixing the treatment of the templates (plantillas para EDIA) as developed in 2018, which depends on the whole of eXe (like exedo, by the way), with the independent process of extracting and compiling code strings was a mistake. Maybe they should be separated.

Anyway thank you for your efforts.

**Comment by ignaciogros** [comment]
As the plan's to renew everything, there will be no fixes in order to make the current versions Python3 compatible. Thank you!
