### ISSUE TITLE
SCORM iDevice. Invalid properties in SCORM 1.2?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#509]
A user gets this error when publishing a SCORM 1.2 package including a SCORM Quiz iDevice:

![invalid_properties](https://user-images.githubusercontent.com/2928868/83867260-6fd5c600-a729-11ea-8557-fd12afce70d5.png)

The LMS administrators say that **mi.scored.scaled** is not part of that standard (It's part of SCORM 2004).

Could you check that, please?

**Comment by ignaciogros** [comment]
If you export as 2004 (including a Quiz Test iDevice), you'll still see this line in the HTML code:

scorm.SetInteractionValue("cmi.score.scaled", "0");

It that right? I think it might provoke the same error. We have to be sure about that. SCORM 1.2 is the default SCORM export now.

**Comment by ManuelMayoSdweb** [comment]
In my tests the behavior seems to be correct: the `cmi.score.scaled` statement is registered in scorm 2004 but not in scorm 1.2.

**SCORM 1.2**

![scorm_quiz_1_2](https://user-images.githubusercontent.com/59160656/97590334-c7d5d780-19fe-11eb-9783-ba7674770792.PNG)

**SCORM 2004**

![scorm_quiz_2004](https://user-images.githubusercontent.com/59160656/97590373-d1f7d600-19fe-11eb-8968-b31fc740c5e2.PNG)

**Comment by ignaciogros** [comment]
OK. Thank you!
