### ISSUE TITLE
enlace https vídeos you tube

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#51]
Se describe en la entrada http://exelearning.net/forums/topic/problema-videos-https/

**Comment by ignaciogros** [comment]
Acabo de publicar un sitio web creado con eXe que tiene el siguiente código y no ha habido ningún problema para reproducir el vídeo:

`<p><iframe width="425" height="350" src="//www.youtube.com/embed/EW72hU1Rp7g" style="border:0"></iframe></p>`

**Comment by jm-andonegi** [comment]
Lo que es curioso es que Youtube, en el código que ofrece para embeber, antes ponía sin https y ahora pone https

**Comment by ignaciogros** [comment]
Es verdad: han incluido el protocolo. TinyMCE 4 no lo incluye, al menos de momento, pero hacer que lo haga es fácil. En el caso de TinyMCE 3 (versión que incluye eXe 2.1) fuimos nosotros quienes eliminamos el protocolo. Por defecto (demo en http://archive.tinymce.com/tryit/3_x/full.php), aunque introduzcas una dirección con https, te la cambia a http. Eliminamos el protocolo para evitar problemas de bloqueo de los contenidos. 

**¿Queréis que incluya el https por defecto para Youtube de cara a la 2.1.1 o se queda como está?** Hay millones de vídeos con //, así que si no falla, como se decía en los foros, creo que lo podemos dejar así.

**Comment by ignaciogros** [comment]
**¿Queréis que incluya el https por defecto para Youtube de cara a la 2.1.1 o se queda como está?** Hay millones de vídeos con //, así que si no falla, como se decía en los foros, creo que lo podemos dejar así.

**Comment by jm-andonegi** [comment]
Mi opinión: mientras no se pueda reproducir el problema no existe el problema. Yo por ahora lo dejaría cómo está.

**Comment by antoniomonjef** [comment]
Pues ya está...
se queda como está

**Comment by jvprofe** [comment]
Perdonad que reabra este hilo. He intentado registrarme en la página de exelearning, pero el registro está cerrado. Soy Juan V. Carrillo, profesor y usuario de la plataforma Moodle de formación a distancia de la Región de Murcia, que utiliza como base SCORMs generados con eXe.

Comentaros que nosotros seguimos teniendo el problema. Según he podido comprobar, el idevice, en modo edición, establece el vídeo con el prefijo `// ` de forma correcta. Sin embargo al guardar los cambios el vídeo aparece con  `http:// `. De igual manera, al exportarlo se establece con `http:// ` lo cual hace que sea contenido mixto y no se pueda mostrar correctamente.

Si editamos a mano el código html se puede establecer por defecto a `https:// `. No obstante, resulta engorroso.

**Comment by ignaciogros** [comment]
Hola Juan.

Adjunto una exportación hecha con la próxima versión, que estará disponible muy pronto (ya hemos empezado las pruebas). 

[prueba_youtube.zip](https://github.com/exelearning/iteexe/files/721099/prueba_youtube.zip)

Por favor, confirma si sirve. El vídeo se ha añadido pegando la dirección de la página de Youtube, sin más.

Si necesitáis solucionarlo rápido en vuestro eXe podéis hacerlo modificando el archivo scripts/tinymce_3.5.11/jscripts/tiny_mce/plugins/media/js/media.js para que elimine el protocolo:

[media.zip](https://github.com/exelearning/iteexe/files/721103/media.zip)

Espero que os sirva. Si no es así, reabro la incidencia. Gracias por el aviso.

**Comment by jvprofe** [comment]
Muchas gracias Ignacio. Sí funciona. Esperamos ansiosos esa próxima versión 👏
