### ISSUE TITLE
ePub export fail when including a game

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#510]
* Create a new elp.
* Insert an A-Z Quiz Game (Rosco in Spanish).
* Try to export as ePub. You'll get a this error: EXPORT FAILED! string index out of range

I know that a game like that was not designed for ePub, but will it be easy to fix? Why does it throw _that_ error @ManuelMayoSdweb? Thank you!

@ManuelMayoSdweb: Es el mismo error comentado en el correo "Error en la exportación a ePub". Hacemos el seguimiento por aquí. Aquel correo se puede eliminar, y su adjunto también. Sucede siempre que hay un Rosco y/o un VídeoQExt. Gracias.

**Comment by ManuelMayoSdweb** [comment]
Yes, in fact it seems the same case. The problem seems to be due to empty `href` tags.

There is also an open issue on this topic (#500), perhaps the best thing would be to close it and continue here.

I think we could solve the problem by doing one of the following steps:
- Remove empty href tags from iDevices causing the problem. 
- Make exception with certain iDevices when exporting to ePub. 
- Ignore empty href tags when exporting to ePub.

**Comment by ignaciogros** [comment]
There should be no empty href tags. Thank you, @ManuelMayoSdweb!

**Comment by mnarvaezm** [comment]
El problema  está solucionado en la nueva versión del idevice Rosco que formará parte de la versión 2.6 de eXe.

**Comment by ignaciogros** [comment]
2.6 (master) still throws that error (EXPORT FAILED! string index out of range) when trying to export [this file](https://github.com/exelearning/iteexe/files/6653914/epub_export_tests.zip) as epub.

As those games won't work in that format anyway, **we don't have to fix this before releasing eXe 2.6**.

**Comment by mnarvaezm** [comment]
Muy buenas. 

Ese  error se produce porque el elp contiene un juego creado con la version experimental del idevice Rosco sin editarlo con la nueva versión de dicho idevice por lo que dicho juego sigue conteniendo en su html  el campo vacío que  eXe interpreta como incorrecto  al exportar el elp a epub

Basta con abrir y cerrar el juego para que se genere un html válido y dicha exportación se produzca correctamente. En este vídeo se ilustra el proceso

https://youtu.be/y-73U_1BQ58

**Comment by ignaciogros** [comment]
¡Gracias, @mnarvaezm!
