### ISSUE TITLE
Is mki18n-extract working properly?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#512]
Hi @jrfern,
I found some strings in tinymce_4_settings.js that are not translated, like "Table with column and row headers". I just need to know if you can see them as not translated strings when executing mki18n-extract. If not, we have to fix that as soon as possible.
Please close the issue if you see those strings as strings to translate.
Thank you!

**Comment by jrfern** [comment]
Don't worry, they appear as non-translated strings in the newly generated PO files. They will be translated when you call the new string-freeze.
