### ISSUE TITLE
eXe, Mac and Git

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#515]
Does eXe use the git command by default. I mean: Will the user get a warning if executing eXe without Xcode installed? If so, can we avoid that? If not, just close this issue. Thank you.

Related thread: https://exelearning.net/en/forums/topic/utilizacion-de-exelearning-en-mac/#post-34743

**Comment by ManuelMayoSdweb** [comment]
It seems that eXe just uses the **git module** to get the hexsha from the last commit uploaded to git:

> exe/engine/version.py

```
import git
repo = git.Repo()
revision = repo.head.commit.hexsha
```
When someone uses the **git module** on **Mac**, they get the message: "_The git command requires the installation of the **command line development tools**_" if:
-  The user has the Python **git module** installed.
-  The user does not have the **command line development tools** installed. 

I think we could stop using the **git module** on eXe without problem, or at least stop using it on Mac.

**Comment by ignaciogros** [comment]
> I think we could stop using the git module on eXe without problem, or at least stop using it on Mac.

I agree. Please remove it if possible. Could we just remove the try + catch and use this: `revision = pkg_version[-40:] if pkg_version else ''`?
