### ISSUE TITLE
fedora package cannot be installed

### ISSUE THREAD

**Issue by ilippert** [exelearning/iteexe#516]
on Fedora 32, trying to install the rpm, I get this error

```
  - nothing provides python-cssmin needed by intef-exe-1:2.5-1.el7.i686
  - nothing provides /bin/python needed by intef-exe-1:2.5-1.el7.i686
```

I have python as well as the package `python3-cssmin`. I guess the solution would be to update the rpm required packages list.

**Comment by ignaciogros** [comment]
Hi,

Please follow these instructions: https://exelearning.net/en/forums/topic/exelearning-en-fedora-30/#post-32115

I hope it works.
