### ISSUE TITLE
FR: poder incorporar contenidos en formato zip

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#52]
Sería un idevice similar al Java, de modo que se pueda:
- Elegir el tamaño del iframe.
- Elegir .zip donde esté un contenido a incorporar (animaciones, ...)
- Elegir el archivo principal.

En el .elp se guardaría (e indexaría) el archivo zip
En edición, eXe se encargaría de descomprimir el zip en una subcarpeta dentro de resources (p.e. con el mismo nombre del archivo)
En los exportados, haría lo mismo, para después comprimir toda la carpeta resources manteniendo la estructura.
En los exportados SCORM se debería añadir al manifiesto todos lo archivos del zip.

**Comment by ignaciogros** [comment]
A hacer cuando se puedan subir contenidos estructurados en carpetas (ya previsto en la hoja de ruta de este año). Tal vez sea suficiente con poder subir contenidos de un zip, porque luego se puede añadir un IFRAME y seleccionar el fichero HTML. Lo comentamos más adelante.

**Comment by ignaciogros** [comment]
Cierro la petición, porque está previsto poder incorporar contenidos estructurados en carpetas pronto, y eso resolverá el problema. Gracias por las sugerencias, @jm-andonegi
