### ISSUE TITLE
Time to get rid of flash for good?

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#523]
«As previously announced in July 2017, Adobe will stop distributing and updating Flash Player after December 31, 2020 (“EOL Date”).» https://www.adobe.com/products/flashplayer/end-of-life.html

Besides, Procomún does not accept flash players, it seems

https://drive.google.com/file/d/19Vy1sZogRTDJQdUH1kElNXyd2vCPJMcI/view?usp=sharing

Nevertheless our packages still include flash players for video and audio. Are they necessary? Isn't it high time to remove such obsolete historical artifacts? They create problems when importing in Procomún.

**Comment by ignaciogros** [comment]
I think that the future version of eXeLearning should handle that in a different way. Maybe only with HTML5 tags. Thanks for reminding it. 
We'll ask Procomun to allow those files for the moment, as they will do with the web fonts.

**Comment by ignaciogros** [comment]
We'll check that in the new eXeLearning, not in eXe 2.6+
