### ISSUE TITLE
i18n. String extraction. Missing strings?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#524]
We might have a problem with the string extraction script. That will explain some missing translations.

@jrfern (Python 2.7 in Linux Mint Mate 19) updated (git pull) the 2.5.1 branch, then he executed tools/mki18n-extract.sh, and he got a 100% translated PO file.

I did the same (Python 2.7 in Windows 7), but I got a PO file with 9 untranslated strings ("Insert HTML code as text", for example, which is not in his PO file). 

Both files should return the same results (some untranslated strings). Could you check that, please? 

[mki18n-extract tests](https://github.com/exelearning/iteexe/files/5116635/i18n_missing_strings.zip)

**Comment by ManuelMayoSdweb** [comment]
I tested on Ubuntu 16.04 and my case is the same as yours: **9 untranslated strings** among which is the text string "Insert HTML code as text".

I keep checking to see what may be failing in @jrfern's case.

**Comment by ignaciogros** [comment]
It seems to be a Babel problem. You get all the strings with Babel 2.3.4-Windows, but not with Babel 2.4.0-Ubuntu. We still don't know how to reproduce it with a simple case. If we find how to, we'll open an issue in the Babel project.
