### ISSUE TITLE
Problema de permiso para acceder a carpeta de mis documentos

### ISSUE THREAD

**Issue by BPJJ** [exelearning/iteexe#528]
En primer lugar felicitar a todo el equipo por esta magnifica aplicación.
Mi problema es que no puedo acceder desde la aplicación a la carpeta de mis documentos y no se como concederle permiso, he reinstalado la aplicación en varias ocasiones y el problema persiste.
Adjunto captura de pantalla
Gracias por vuestra atención
Un saludo
<img width="1280" alt="Captura de pantalla 2020-09-25 a las 3 01 50" src="https://user-images.githubusercontent.com/71858804/94216533-e87eaf00-fedf-11ea-86b2-acc7bc31349f.png">
<img width="1280" alt="Captura de pantalla 2020-09-25 a las 3 05 33" src="https://user-images.githubusercontent.com/71858804/94216710-5925cb80-fee0-11ea-9258-31c16a45f985.png">

**Comment by ignaciogros** [comment]
Hola @BPJJ:
Como ves, seguimos con la incidencia abierta. Supongo que a estas alturas ya habrás visto que puedes colocar los ficheros en otros directorios (en C, por ejemplo) para evitar los problemas de permisos. En cualquier caso, seguimos mirándolo para intentar mostrar un mensaje informativo en caso de encontrar problemas. Gracias por el aviso.

**Comment by BPJJ** [comment]
Hola @ignaciogros:
Os pido disculpas por no haber comunicado la resolución del problema. Mediante la utilización del terminal del Mac, pude darle los permisos correspondientes, lo que no recuerdo es si fue tras desinstalar y volver a instalar ExeLearning.
Agradeceros vuestro tiempo y de nuevo disculparme por mi descuido.
Un saludo

**Comment by Javiobcn** [comment]
En la captura de pantalla se ve que es un Mac donde está teniendo el problema, en windows y linux no he conseguido reproducir el error, probablemente sea un problema del usuario ya que posteriormente a la apertura del asunto comenta: "Os pido disculpas por no haber comunicado la resolución del problema. Mediante la utilización del terminal del Mac, pude darle los permisos correspondientes, lo que no recuerdo es si fue tras desinstalar y volver a instalar ExeLearning.
Agradeceros vuestro tiempo y de nuevo disculparme por mi descuido."

También Ignacio comentaba que "seguimos mirándolo para intentar mostrar un mensaje informativo en caso de encontrar problemas", yo he probado y no consigo que salga un error "feo" del servidor web todos salen con javascript bien "bonitos".

Cerramos este asunto, aunque puede reabrirse si alguien quiere aportar mas info.

Necesito mas información para reproducirlo.
