### ISSUE TITLE
scorming with exe online

### ISSUE THREAD

**Issue by beppefra** [exelearning/iteexe#529]
Hi there, exporting in scorm 1.2 or 2004 my exe  jobs and uploading scorms in moodle, it perfectly works, but all packages (slides, films, etc) are simply downloadable! when I scorming with Ispring the same scorm packages aren't. How can  I create undownloadable scorm packages with exelearning? Thank you so much for your precious contribution!
Beppe

**Comment by ignaciogros** [comment]
The problem doesn't seem to be in eXe. Could you provide a link so we can check it? Thank you!
