### ISSUE TITLE
Dependencia de python-requests-oauthlib

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#53]
Durante el periodo en que se estuvo desarrollando la publicación en google drive se introdujo la dependencia de python-requests-oauthlib. Cuando ese desarrollo se eliminó, se ha sustituido por la publicación en Procomún. ¿Sigue usándose esa biblioteca? ¿Sigue siendo necesaria esa dependencia?

**Comment by jrjimenezr** [comment]
Me imagino que ahora mismo no, pero seguramente para exe web sí sea
necesaria, pero eso Pedro seguro que lo puede explicar con mayor claridad
que yo.
Un saludo.

**Comment by pedropena** [comment]
La publicación en Procomún también lo necesita.

**Comment by jrfern** [comment]
Ah pues duda resuelta. Cierro el issue.

Muchas gracias
