### ISSUE TITLE
Portable version for Ubuntu can't export

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#531]
Export as web site fails (Ubuntu based distribution: EducaAndOS). See https://exelearning.net/forums/topic/problema-con-la-portable/

This is important. Is it easy to fix? Could it be in eXe 2.5.1 (only if we're completely sure that it won't cause other problems).

Thank you.

**Comment by ManuelMayoSdweb** [comment]
I understand that the problem is that the lxml library is missing. In the absence of more testing, it would be best if you try to install it: `python -m pip install lxml`

**Comment by ignaciogros** [comment]
Just in case it helps:

If you download the Linux portable version and you open the exelib directory you'll see that the bs4, for example, is there, but lxml is missing. Maybe because it was not installed in the machine before generating the package? I hope it helps...

**Comment by ignaciogros** [comment]
Fran:

Te asigno la incidencia para intentar resolverla cuando lancemos la 2.5.1 (esperamos hacerlo hoy). Creo que puede ser porque no tengas instalado lxml en el equipo que usas para generar la versión portable. Ojalá sea solo eso. Muchas gracias.

**Comment by ignaciogros** [comment]
Thanks, @franmacias!
