### ISSUE TITLE
problems saving

### ISSUE THREAD

**Issue by gloriabrea** [exelearning/iteexe#533]
I've lost the work done during 6 hours, even if I saved periodically and cheked with the preview option. Is there any possibility to recover that work from somewhere? 
Thank you

**Comment by ignaciogros** [comment]
Hi Gloria,
Sorry about answering so late. I guess that you probably solved that.
In case you didn't, please attach the elp file so we can try to open it.
Thank you.

**Comment by ignaciogros** [comment]
Not enough information.
