### ISSUE TITLE
Release with Greek

### ISSUE THREAD

**Issue by kiolalis** [exelearning/iteexe#538]
There is a lot of time that I have translated exelearning in Greek but I can't see/test the translations. The final release doesn't include the complete greek .po file. Could you please create a beta version for windows 64bit in order to test and finalize the translation?
Yannis

**Comment by ignaciogros** [comment]
Hi Yannis,
Sorry about answering so late. We're starting to organize everything for a new release (hopefully available in a couple of months). We'll revise the PO files too, of course.
Thank you very much for your work.

**Comment by ignaciogros** [comment]
@kiolalis, @jrfern: Thank you!
