### ISSUE TITLE
FR (math branch): Generate PNG image based on MathML input

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#54]
See handleTinyMCEmathML in mainpage.py

It should generate a PNG file based on mathml_source (MathML input). mathml_source is currently overwritten. It's value is "To do!".

**Comment by jrfern** [comment]
On 26 May 2016 at 10:14, Ignacio Gros <notifications@github.com> wrote:

> See handleTinyMCEmathML>
> It should generate a PNG file based on mathml_source (MathML input).


Maybe something escapes me. When I studied  the topic of maths in web
pages, I found two solutions had been used: either creating images
using some tool (a LaTeX to image converter?) or creating xml markup
for the maths, to be interpreted by the browser. Obviously the second
solution is better, open, editable, etc.  Are we using MathML to
create images? It makes no sense.

Saludos
-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by ignaciogros** [comment]
Hi, Juan Rafael.

I'm working on a new plugin in which you can paste LaTeX or MathML code. Screenshot: 

![pastemath](https://cloud.githubusercontent.com/assets/2928868/15600058/de6f8ca0-23e7-11e6-99cf-4c4aae5b1e2c.png)

It has these options:

- Use code (recommended option), with or without an alternative image.
- Use an image.

The goal is, as you say, to ease the insertion of mathematical markup instead of allowing only images. Those will be just an alternative content (for users with no JavaScript, etc.), unless the user wants only images. You can also enable MathJax to display the mathematical formulas properly in all browsers.

Regards.

**Comment by jrfern** [comment]
On 27 May 2016 at 08:50, Ignacio Gros <notifications@github.com> wrote:
>
> Hi, Juan Rafael.
>
> I'm working on a new plugin in which you can paste LaTeX or MathML code.
> It has these options:
> Use code (recommended option), with or without an alternative image.
> Use an image.

It's going to be the best solution I've seen so far. Thanks
-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/
