### ISSUE TITLE
Exception in eXeOnline

### ISSUE THREAD

**Issue by arpablos** [exelearning/iteexe#542]
Hello!

Sometimes our installation throws some exceptions as the file I attach below:

[ws_exception.zip](https://github.com/exelearning/iteexe/files/5819866/ws_exception.zip)

**Comment by ignaciogros** [comment]
Is this fixed? Thanks!

**Comment by arpablos** [comment]
Not yet. We can "solve partially" rebooting the server, but it appears randomly, and we don't know why. Maybe @xavipuigc could clarify it checking the attached file in the first comment.

**Comment by ignaciogros** [comment]
Important: I change the priority to A then. I thought it was only when installing.

**Comment by ignaciogros** [comment]
There's no need to restart the server now. You just have to close the browser when this happens.
