### ISSUE TITLE
From exelearning to Moodle

### ISSUE THREAD

**Issue by ericbdu17** [exelearning/iteexe#543]
Hi everybody and..first of all.. the very best for '21 ! Take care ! I do lots of my lessons with exelearning (including videos, images, iframe for quiziniere, pdf..) Now that flash player doesn't exist anymore, is it possible to make exelearning read a "swiffplayer" (emulator that read flash). To include that in lessons (via iframe or something else). I export lessons in Scorm for Moodle and also in website (.zip). The thing is that the menu of my lessons do not appear anymore when they are installed. Works fine previluased, and not after :-(
Any help ?
Hope i'm clear enough and well understood. I'm French. Beg your pardon
Eric

**Comment by ignaciogros** [comment]
Hi Eric,

**> Now that flash player doesn't exist anymore, is it possible to make exelearning read a "swiffplayer" (emulator that read flash).** 

Thanks for the suggestion. We'll have to find one compatible with eXe's license (GNU-GPL). Please let us know if you find a good solution. New ticket for that: #553 

**> The thing is that the menu of my lessons do not appear anymore when they are installed.**

There's only a menu when you export as website. When you choose SCORM and publish it in Moodle, it's the LMS (Moodle) the one that displays the menu (it reads an XML file include in the zip file and creates the required menu). I hope it helps.
