### ISSUE TITLE
Firefox no puede abrir esta página

### ISSUE THREAD

**Issue by GustavRa** [exelearning/iteexe#544]
Hola. Venía trabajando normal pero al crear iDevice SItio web esxterno, no muestra la página en el área de trabajo. ¿Qué podría ser? Gracias

**Comment by ignaciogros** [comment]
Algunas páginas no permiten que se muestren dentro de un IFRAME. Si intentas incluir Google ahí, no podrás, porque Google no deja. Si intentas poner la web de eXe, sí podrás. No es un fallo de la aplicación, sino una decisión de sus propietarios. No se puede hacer nada... Gracias por avisar.
