### ISSUE TITLE
Problema de permisos al exportar

### ISSUE THREAD

**Issue by fabiolanaranjo** [exelearning/iteexe#548]
Hola

Al intentar exportar  un scorm, me aparece este mensaje

ERROR EN LA EXPORTACIÓN [Errno 13] Permission denied: Path(u'C:\\Users\\fabiola\\Documents\\TRABAJO\\carpeta\\c.zip')

Previamente me aparece un mensaje alertando sobre los metadatos

Este paquete contiene metadatos. Podría exportar información incorrecta incluida en su momento por el autor original. Vaya a Propiedades para editarla.

¿Desea exportar el paquete con los metadatos actuales?

 No volver a mostrar este aviso

Llevo años utilizando este programa, y es la primera vez que me ocurre, he probado a desinstalarlo y volverlo a instalar y nada (tambien he probado con varias versiones)

saludos y gracias

**Comment by ignaciogros** [comment]
Por favor, prueba guardando el elp en otra carpeta (no una de sistema como Documentos o el Escritorio). ¿Funciona? En cualquier caso, ¿puedes adjuntar el elp? Si prefieres, envíalo a la dirección que aparece a pie de página en https://exelearning.net/

**Comment by fabiolanaranjo** [comment]
Hola Ignacio, el problema es que cualquier elp que cree desde mi equipo da el mismo problema, te adjunto una prueba de elp vacio

Saludos y muchas gracias

Fabiola

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Ignacio Gros<mailto:notifications@github.com>
Enviado: martes, 2 de febrero de 2021 13:57
Para: exelearning/iteexe<mailto:iteexe@noreply.github.com>
CC: fabiolanaranjo<mailto:fabiolanaranjo@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [exelearning/iteexe] Problema al exportar un scorm (#548)


Por favor, prueba guardando el elp en otra carpeta (no una de sistema como Documentos o el Escritorio). ¿Funciona? En cualquier caso, ¿puedes adjuntar el elp? Si prefieres, envíalo a la dirección que aparece a pie de página en https://exelearning.net/

**Comment by fabiolanaranjo** [comment]
Ignacio, ha funcionado lo de exportarlo a otra carpeta. Gracias!!



Enviado desde mi Galaxy



-------- Mensaje original --------
De: Ignacio Gros <notifications@github.com>
Fecha: 2/2/21 13:57 (GMT+01:00)
Para: exelearning/iteexe <iteexe@noreply.github.com>
Cc: fabiolanaranjo <fabiolanaranjo@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [exelearning/iteexe] Problema al exportar un scorm (#548)


Por favor, prueba guardando el elp en otra carpeta (no una de sistema como Documentos o el Escritorio). ¿Funciona? En cualquier caso, ¿puedes adjuntar el elp? Si prefieres, envíalo a la dirección que aparece a pie de página en https://exelearning.net/

**Comment by ignaciogros** [comment]
@xavipuigc: 
Parece que hay problemas de permisos. Hay otros usuarios que han avisado de un error al intentar exportar: eXe dice que no puede copiar el fichero popup_bg.gif.
Si buscas esa cadena (popup_bg.gif) en los ficheros *.py de eXe (carpeta "export"), verás que es el primer fichero que se intenta copiar al hacer una exportación. Por eso falla en ese fichero: simplemente porque es el primero y no puede copiarlo al directorio (generalmente carpetas de usuario: Escritorio, etc.). A partir de ahí, no sigue.

**Comment by Javiobcn** [comment]
Al igual que la incidencia #548 debe ser un problema relacionado con la máquina del usuario. 

No consigo reproducir el error en windows, funciona bien, tanto la versión portable como la instalable. Si que aparece la advertencia de "Este paquete contiene metadatos. Podría exportar información incorrecta incluida en su momento por el autor original. Vaya a Propiedades para editarla." pero la exportación me ha funcionado bien.
