### ISSUE TITLE
Moodle ignores "Hide the menu" setting at import when using custom style

### ISSUE THREAD

**Issue by instancefour** [exelearning/iteexe#549]
Hey,
great Tool!

I enountered a poblem, which I could not solve:

1) Created a custom style. It works, changed colors for checking.

2) Exported to IMS content package and SCORM

3)  import to moodle 3.10. Navigation menu is active.

4)  tried in browser: menu is hidden.

Is this a known issue/behavior or a user error? Maybe I missed something, could not find a hint here or in forums.

Best
Bernhard

**Comment by ignaciogros** [comment]
Hi Bernhard,
Thanks for reporting.
It's not an error. That setting is only for the website export. When you create an IMS or a SCORM package, there's no menu. The navigation menu is created by the LMS (Moodle in that case).
I hope it helps.
