### ISSUE TITLE
Scorm test en exportaciones epub3

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#56]
Viene la incidencia de un cruce de correos.
Resumo:
Holà,
estoy trabajando con C-H y mi experencia con el quizz no es la misma. He descargado el epub que ha hecho C-H y que contiene eXelearning quizz con GitdenReader sobre un Samsung Note 3 con lollipop 5.0. Cuando trae  su "SCORM test" el popup contiene esto :

La paginà situada en file:// dice :
Votre score est 100%

No tengo como en los ipads el nombre del archivo "index.html"
Tal vez esta observacion puede ayudarles a encontrar la fuente del error.

Cordialmente

Le 26/05/2016 10:39, C-H a écrit :
Syntesis de nuestras observaciones por la integracion en epub3
Cuestionarios Scorm 
functionnan con "Gitdenreader" pero no con "Books" en Iphone, Ipad
no functionan con Firefox plugin Lucifox on ordenadores
Pregunta de Selección Múltiple
Si no eliges repuestas, cuando se hace clic, las indicaciones "Correcta" o "no" son las correctas
Si eliges cualquier repuesta, cuando se hace clic, las indicaciones cambian de un clic al otro

**Comment by ignaciogros** [comment]
Creo que la primera parte está resuelta (no se mostraba la puntuación de la Actividad SCORM en algunos visores de ePub): feefc90baea00275781eb4a2055b636c76fa1e17

**A tener en cuenta para más adelante:**

Lo siguiente, dentro de la etiqueta SCRIPT, hacía que en algunos casos su contenido no se reconociera:

`<!-- //<![CDATA[ etc. //]]> -->`

Lo sustituimos por:

`/*<![CDATA[*/ etc. /*]]>*/`

He aprovechado para mejorar la presentación (se muestra el texto bajo el botón en lugar de un "alert" de JavaScript).

**Importante:** 

Creo que esa parte necesita una buena revisión. Se puede aprovechar cuando se aborden las tareas relacionadas con las calificaciones. @jmandonegi sabe bien cómo funciona esa parte.

Por favor, comprobad si la primera parte está solucionada. Sigo con la segunda (efectos extraños en Selección Múltiple).

**Comment by ignaciogros** [comment]
Segunda parte (error en los mensajes de respuesta correcta o incorrecta en Selección Múltiple) corregida: 7e452475738fdb3b8e8bc8b006e403bdbdb18e7c

No se hacían las comprobaciones adecuadas.

Por favor, cerrad la incidencia si todo funciona bien.

**Comment by ignaciogros** [comment]
Hola Antonio: 

Te asigno la incidencia. Solo falta hacer la comprobación. Yo lo veo bien, pero viene bien probar en diferentes entornos.

Gracias...

**Comment by g-vidal** [comment]
Hello,
I was one of the contributors of the initial mail. If you need us to provide some tests please get in touch with me or other senders of the initial mail.

A great thank you for this work that opens  great perspectives on epub3

**Comment by ignaciogros** [comment]
Hi, Gérard.

Thank you for your help.

I attach an ePub file that was created with eXe's development version. Could you check if everything works? 

We can close the ticket if so. If not:

Could you attach an elp file with the iDevices that are not working properly? 

Thanks a lot!

**Attachment:** [epub_tests.zip](https://github.com/exelearning/iteexe/files/297591/epub_tests.zip)

**Comment by cheyraud** [comment]
Hi Ignacio
it's works now for your Quizz Scorm and your MultisellecionQuizz works too on Books with Ipad, Iphone 

But mine attached does'nt works : the schown answers are not the registered even in eXelearning
Thanks a lot for your answers

[EstacionesMultiselecion.zip](https://github.com/exelearning/iteexe/files/298689/EstacionesMultiselecion.zip)

**Comment by ignaciogros** [comment]
Thanks for your tests, Gérard!

Does the attached ePub file work? I just exported your elp using eXe's next version (it'll be 2.1.1).

Regards.

[Estaciones_Multiselecion.zip](https://github.com/exelearning/iteexe/files/300971/Estaciones_Multiselecion.zip)

**Comment by cheyraud** [comment]
Hi Ignacio, Thanks it works fine. I didn't found eXe 2.1.1 but it's ok now

**Comment by ignaciogros** [comment]
eXe 2.1.1 will be available soon (we still don't know exactly when), and the problem you found will be solved in it.

Thanks for telling us!
