### ISSUE TITLE
Can't run eXe

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#565]
**This is a priority 1 issue.**

@jrfern created a test package (deb and appImage), but it doesn't run. It throws this error:

> Traceback (most recent call last):
>   File "/usr/bin/exe", line 58, in <module>
>     main()
>   File "/usr/bin/exe", line 55, in main
>     application.main()
>   File "/usr/lib/python2.7/dist-packages/exe/application.py", line 109, in main
>     self.loadConfiguration()
>   File "/usr/lib/python2.7/dist-packages/exe/application.py", line 237, in loadConfiguration
>     self.config = configKlass()
>   File "/usr/lib/python2.7/dist-packages/exe/engine/config.py", line 271, in _init_
>     self._writeDefaultConfigFile()
>   File "/usr/lib/python2.7/dist-packages/exe/engine/config.py", line 301, in _writeDefaultConfigFile
>     defaultVal = getattr(self, optionName)
> AttributeError: 'LinuxConfig' object has no attribute 'eXeUIversion'

**Comment by jrfern** [comment]
A bit of context: this happens when there is no exe.conf. It's an error creating it from scratch, I guess.
