### ISSUE TITLE
"Download Classification Sources" not working on Mac

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#569]
Not for eXe 2.6.

The "Download Classification Sources" button (Advanced mode - Properties tab - Metadata - LOM-ES - Classification) is not working on MacOS. It probably a certificate problem, like the one we had in the Wikipedia iDevice.

**Comment by Javiobcn** [comment]
it's resolved for next version in 3fa765ea531df28792dac65e4a09e21afaad0d96
