### ISSUE TITLE
Translation errors in 2.6 (master)

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#570]
1. ca.js translates abcde... as a,b,c,d,e...
2. es.js has "`&percent;` de respuestas correctas" instead of "`&percnt;` de...".

Thank you!

**Comment by ignaciogros** [comment]
3. fr.js: "You have got %1 hits and %2 misses" is translated as "Vous avez obtenu ". The second part ("%1 hits and %2 misses") is missing.

**Comment by ignaciogros** [comment]
I'll check this part, @jrfern:

Maybe we should use a separator between the letters, because some languages might have letter groups, such as l·l in Catalonian, and they can't be used right now.

**Comment by jrfern** [comment]
We have already fixed the two first problems. Working on the third one.

**Comment by ignaciogros** [comment]
4. fr.js has no " | " separator in "Right! | Excellent! | Great! | Very good! | Perfect!"
Right now it's "Bien ! Super ! Excellent ! Fantastique ! Parfait !".
It should be "Bien! | Super! | Excellent! | Fantastique! | Parfait!"

**Comment by jrfern** [comment]
Fixed. Please feel free to reopen if you find any new mistakes.

**Comment by ignaciogros** [comment]
Thank you, @jrfern.
I just adapted the hangman game so you can use l·l there too **if you want**.
The CA translation of "abcdefghijklmnopqrstuvwxyz" will be "abc\u00e7defghijkll\u00b7lmnopqrstuvwxyz" if you want to include that letter group.
If you do so, the hangman game will display these characters by default: abcçdefghijkl·mnopqrstuvwxyz
And the A-Z Quiz (Rosco in Spanish) fill display all these letters: abcçdefghijkll·lmnopqrstuvwxyz

**Comment by ignaciogros** [comment]
tl language, encoding errors in the Preferences dialog:

![encoding_tl](https://user-images.githubusercontent.com/2928868/119840476-519e4280-bf05-11eb-970b-cfa7c66f414f.png)

**Comment by jrfern** [comment]
On Thu, 27 May 2021 at 14:05, Ignacio Gros ***@***.***> wrote:
>
> tl language, encoding errors in the Preferences dialog:

No, you simply don't have a Baybayin Tagalog font, see screenshot.

A different point is that Baybayin is not commonly used nowadays, but
the Latin script. We would need a Filipino translator to fix this.

-- 
Juan Rafael Fernández
https://jrfern.ddns.net/

**Comment by jrfern** [comment]
> tl language, encoding errors in the Preferences dialog:

No, you simply don't have a Baybayin Tagalog font, see screenshot.

A different point is that Baybayin is not commonly used nowadays, but
the Latin script. We would need a Filipino translator to fix this.

![Captura de pantalla de 2021-05-28 19-26-06](https://user-images.githubusercontent.com/3305693/120023175-f5a6ed00-bfdc-11eb-8ba2-ef4b5075472f.png)
