### ISSUE TITLE
Problemas para abrir un archivo exe

### ISSUE THREAD

**Issue by elenibus** [exelearning/iteexe#573]
He estado trabajando en un archivo exelearning y dispongo de él en formato *.elp . Al abrirlo al dia siguiente y de repente y a pesar de que el tamaño es de 363 MG lo abro con cierta dificultad pero me aparece "vacio". No consigo recuperarlo. A que puede ser debido el error? No lo abro ni desde red, ni desde mi escritorio. Tengo la version de exelearning 2.5.1. Gracias . Puedo enviarles el archivo en elp por si pueden ayudarme

. Elena

**Comment by ignaciogros** [comment]
Enviamos respuesta por correo electrónico.
