### ISSUE TITLE
Can't export into a Web Site

### ISSUE THREAD

**Issue by macarenarojo2** [exelearning/iteexe#579]
ERROR EN LA EXPORTACIÓN [Errno 13] Permission denied

But i have all the permissions

**Comment by ignaciogros** [comment]
Please try saving the elp in different folder (not the system ones, like Desktop or Downloads). Example: c:\my_docs\my_file.epl

We'll try to handle those exceptions properly in the next version.

Thanks for reporting that issue. Please reopen if it fails in other locations too.
