### ISSUE TITLE
activity rosco not works

### ISSUE THREAD

**Issue by Pablo-hub44** [exelearning/iteexe#580]
cuando creo la actividad rosco , funciona bien se ve y todo, pero al darle click en vista previa no aparece nada

**Comment by ignaciogros** [comment]
Por favor, adjunta un elp o exportado como sitio web comprimido en zip. Dinos también qué sistema operativo y navegador usas. Gracias.

**Comment by Pablo-hub44** [comment]
La actividad funciona pero solo cuando estás editanto el exe learning pero
al darle en vista previa , no aparece nada , tampoco cuando lo exportó , no
aparece
Uso Windows 10 , con chrome , también Edge
Un amigo lo probó en Linux e igual no no se ve

**Comment by mnarvaezm** [comment]
Hola, Pablo. 
¿Puedes adjuntar el elp que contiene el rosco que te da ese problema?

**Comment by Pablo-hub44** [comment]
Disculpa pero no puedo es una trabajo en desarrollo

Pero en general no funciona. , Hago un nuevo proyecto y de igual manera no
se ve la actividad

**Comment by mnarvaezm** [comment]
¿Te falla con cualquier rosco en chrome, edge...?  He estado probando en windows 10 con todos esos navegadores y he sido incapaz de replicar el problema que me comentas por lo que, para ir enfocando el mismo, necesitaré alguna informa adicional y que, cuando te sea posible, hagas un prueba algo avanzada:

¿Qué versión de eXe tienes instalada ? Lo puedes ver en el menú de Ayuda -> Acerca de eXe
¿Con qué versión de Chrome has probado? Botón "Personalizar y configurar Chrome", los tres puntos verticales, -> Ayuda-> Información de Google Chrome
¿Estás usando la versión del iDevice Rosco que viene con eXe o la has actualizado?. Si no entiendes esta pregunta, no te preocupes, no lo has actualizada

Cuando puedas, haz la siguiente prueba:  abre eXe con Chrome, crea un nuevo proyecto y añade un idevice tipo Rosco, introduce una o dos palabras en el mismo con alguna imagen, guarda el idevice y dale a previsualizar, 
Si el rosco no se ve, pulsa la tecla F12, para mostrar las Herramientas para desarrolladores de Chrome, marca la pestaña Consola y recarga la página. Por favor, indícame si la ventana de la consola emite algún error, aparecerá en rojo

Si ve bien el rosco anterior, prueba con tu proyecto: dale a previsualizar, ve  a la página en la que tienes  el Rosco, pulsa la t ecla F12 , abre la consola, refresca la paǵina y mira si aparece algún error

Un saludo y gracias por tu ayuda

**Comment by Pablo-hub44** [comment]
Empezar a trabajar el proyecto con la 2.5.0 y luego lo actualice a la 2.5.1
y prosegui con mi proyecto
La versión de Chrome es 90.0.4430.212 64 bits

**Comment by ignaciogros** [comment]
Cierro la incidencia por falta de información. Hemos hecho pruebas con muchos usuarios en los últimos días sin que se hayan encontrado problemas. 
@Pablo-hub44: 
Reabre si el problema persiste adjuntando el elp, por favor.
