### ISSUE TITLE
Image Gallery iDevice: broken thumbnails after re-editing

### ISSUE THREAD

**Issue by arpablos** [exelearning/iteexe#585]
Hi!

We have a image gallery iDevice with some pictures. It works fine when I create the iDevice. Then I publish the content into the repository.

After that, If I try to edit the content again, image gallery thumbnails are broken, but the pictures is still there.

![image](https://user-images.githubusercontent.com/13365564/121344525-2879ab00-c924-11eb-9a66-9d39dfa4ec6a.png)

**Comment by ignaciogros** [comment]
Fixed in ws and ws26.
