### ISSUE TITLE
Error importing .elp to eXeOnline - Wrong file format: list index out of range

### ISSUE THREAD

**Issue by arpablos** [exelearning/iteexe#586]
Hi!

We are trying to import and .elp file (atacched below) to eXeOnline and we get "Wrong file format: list index out of range".

It's possibly related with the iDevice gallery at the end of the project.

I have checked importing:
- ALL + Gallery= KO -> Wrong file format: list index out of range
- ALL without Gallery = OK
- Only the Gallery = OK

PS: Originally reported by @antoniomonjef 

[plantilla_idevices07.zip](https://github.com/exelearning/iteexe/files/6630562/plantilla_idevices07.zip)

**Comment by ignaciogros** [comment]
It displays a more comprehensive warning now, and you can open that elp in eXe 2.6.
