### ISSUE TITLE
FR: Easy system to create new (JavaScript) iDevices

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#59]
Create an easy to use system to create new iDevices.

Right now, iDevices require a lot of Python programming, and you'll have to edit eXe's core in order to export some required files, etc.

The idea is to create a simple mechanism to create new iDevices which will share their Python structure.

Full description of the task (in Spanish) in the attached elp file ("JavaScript iDevices" page): [tareas_python_20160527.zip](https://github.com/exelearning/iteexe/files/286017/tareas_python_20160527.zip)

**Comment by ignaciogros** [comment]
The front-end part is almost ready. 

Please check the [javascript-idevices branch](https://github.com/exelearning/iteexe/tree/javascript-idevices) and read the attachment (in Spanish) for further explanations.

[explicacion_para_su_desarrollo.zip](https://github.com/exelearning/iteexe/files/444548/explicacion_para_su_desarrollo.zip)

**Comment by ignaciogros** [comment]
How to develop a JavaScript iDevice (first version, in Spanish only). To review.

Cómo desarrollar un iDevice JavaScript (primer versión, en castellano). Para revisar.

[javascript-idevices_documentacion_es_20161024.zip](https://github.com/exelearning/iteexe/files/547294/javascript-idevices_documentacion_es_20161024.zip)

**Comment by OscarBanosGarcia** [comment]
Hola!
I have downloaded exe and your filer but unfortunately I cannot open them. It says "wrong file format".
Any hint? Thank you

**Comment by ignaciogros** [comment]
[Download the latest version](http://exelearning.net/descargas/) (2.1.1 right now). You should be able to open the file with it (not with 2.1). The [javascript-idevices branch](https://github.com/exelearning/iteexe/tree/javascript-idevices) has some working examples.

Please let us know if you have any suggestions.

Thanks...

**Comment by ignaciogros** [comment]
Done! Available soon (eXeLearning 2.2).

**Comment by F0h** [comment]
Nacho (si me permites llamarte así) qué maravilloso proyecto tienes.
Lo he estado usando desde el año pasado y me mola mucho.
Acabo de actualizarme con js y ver que puedo crear idevices con ello me pican los dedos para ver si hago algo con eso
Saludos desde Lima-Perú
