### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by LolaOM** [exelearning/iteexe#594]
Hi there. I have been creating a file in exe learning for several hours and when I wanted to export it, it gave me the error "string is too long to send". It does not export or save it. ´It has created 13 files with the name "crashed" and they are all empty. How can I get my job back? Thanks in advance
![erro en la exportación](https://user-images.githubusercontent.com/89660727/131174429-b04cb947-1180-4b18-b7f0-3038425bb228.JPG)
![crashed](https://user-images.githubusercontent.com/89660727/131174516-6e496676-f87a-4743-bc12-82185a1b5d42.JPG)

**Comment by ignaciogros** [comment]
Please attach the elp or send it to the address you'll find at the bottom of this page: https://exelearning.net/
