### ISSUE TITLE
eXeLearning Version: 2.3.1

### ISSUE THREAD

**Issue by jvf349** [exelearning/iteexe#597]
eXeLearning 
Version: 2.3.1
Revision: 062e426c3de75bb267375c5f52913ceeacc1ab72

The program does not allow export task in **Educational Standard: SCORM1.2**

**Comment by ignaciogros** [comment]
In eXeLearning 2.6, SCORM 1.2 is the default SCORM export. You can also use SCORM 2004 enabling the "Advanced mode" (right top corner).
