### ISSUE TITLE
SNAP package. MimeTeX not working.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#599]
See https://exelearning.net/forums/topic/se-puede-usar-mimetex-en-la-version-snap-para-crear-imagenes-de-matematicas/

eXe doesn't create images from LaTeX code in that version.

**Comment by Javiobcn** [comment]
Solved for the next version in 34edb0fbc03cd7122bf10d58592215724eecff1b

**Comment by ignaciogros** [comment]
I just installed the SNAP package (master) on Ubuntu and it doesn't generate images from LaTeX code like `\[ ax^2 + bx + c = 0 \]`.

It says that "Could not create image (LaTeX)".

It works on Windows (eXe 2.6).
