### ISSUE TITLE
No funciona contenido de Ayuda > notas de la versión

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#60]
En w7, chrome. Se obtiene el siguiente error

<type 'exceptions.ValueError'>: Invalid mode ('rtb')
twisted\internet\defer.pyc, line 107 in maybeDeferred
105
106
107
108
nevow\rend.pyc, line 427 in renderHTTP
425
426
427
428
nevow\rend.pyc, line 461 in _renderHTTP
459
460
461
462
nevow\rend.pyc, line 421 in <lambda>
419
420
421
422
nevow\flat\__init__.pyc, line 14 in flattenFactory
12
13
14
15
nevow\flat\twist.pyc, line 34 in deferflatten
32
33
34
35
nevow\flat\twist.pyc, line 18 in drive
16
17
18
19
nevow\flat\ten.pyc, line 104 in iterflatten
102
103
104
105
nevow\flat\flatstan.pyc, line 97 in TagSerializer
95
96
97
98
nevow\flat\ten.pyc, line 91 in serialize
89
90
91
92
nevow\flat\ten.pyc, line 82 in partialflatten
80
81
82
83
nevow\flat\flatstan.pyc, line 231 in DirectiveSerializer
229
230
231
232
nevow\flat\ten.pyc, line 91 in serialize
89
90
91
92
nevow\flat\ten.pyc, line 82 in partialflatten
80
81
82
83
nevow\flat\flatstan.pyc, line 215 in MethodSerializer
213
214
215
216
nevow\flat\flatstan.pyc, line 197 in FunctionSerializer
195
196
197
198
exe\webui\releasenotespage.pyc, line 65 in render_changelog
63
64
65
66
codecs.pyc, line 881 in open
879
880
881
882
<type 'exceptions.ValueError'>: Invalid mode ('rtb')

**Comment by jrfern** [comment]
Por si sirve, he vuelto a comprobar que con Chromium en Debian Testing funciona la carga del _changelog_. 

@antoniomonjef , sabes que sin assignee no hay responsabilidad.

Investigando lo del 'Invalid mode ('rtb')'
En las líneas 65 y 70 de releasenotespage.py tenemos
     changelog_contents = codecs.open(changelog_file, 'rt', 'utf-8').read()
Llevo un rato mirando, y perdonad mi ignorancia, pero... ¿cuál es el modo 't' de apertura de ficheros en python?

**Comment by antoniomonjef** [comment]
Ya lo se @jrfern ... pero me lo estoy pensando ;-)

**Comment by JuanCasanovaSdweb** [comment]
El problema era exactamente lo que mencionaba @jrfern 

El modo "t" es modo texto pero la librería "codecs" siempre abre los archivos en modo binario "b" (https://docs.python.org/2/library/codecs.html#codecs.open), por lo que intentaba abrirlo como texto y binario a la vez, cosa obviamente imposible.
