### ISSUE TITLE
FPD ejercicio resuelto

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#61]
Mensaje de error 
iDevice dañado: 'TextAreaField' object has no attribute 'buttonCaption'

**Comment by ignaciogros** [comment]
Fixed (ad8aa4aec8eaf98b4070dd6444cb8eb9534bc60c).

Could you check that solution and close if it's OK, Pedro?

Thanks...

**Comment by antoniomonjef** [comment]
La usuaria ha dicho que funciona...

**Comment by ignaciogros** [comment]
Cierro.
