### ISSUE TITLE
Allow navigating more fluently

### ISSUE THREAD

**Issue by guyikcgg** [exelearning/iteexe#610]
When clicking on an iDevice, eXe inserts it automatically in the current page. Then, when clicking on another iDevice or a page, the following message is shown:

> The changes you made will be lost if you navigate away from this page.
> [ OK ]

Ideally, the system should leave the iDevice editor without asking if no changes have been made. If changes were made, the system should ask whether the user wants to save the changes.

At a bare minimum, I would find it more intuitive if the message stated something like "Cannot leave the iDevice editor. The changes...".

Another enhancement would be to show the `exe-editButtons` on top and at the bottom of the editor (currently, they are only at the bottom).

**Comment by ignaciogros** [comment]
We're already working on a new version (100% new), so we won't change many things in eXe 2.6.x, but We'll use this sentence instead of the current one: "Cannot leave the iDevice editor. The changes you made will be lost if you navigate away from this page."
Thank you for your suggestion!
