### ISSUE TITLE
Having "Properties" as a tab next to "Content" is confusing

### ISSUE THREAD

**Issue by guyikcgg** [exelearning/iteexe#612]
When I see that "Content" change when I navigate the pages, I expect that "Properties" apply to individual pages. However, these are the project's properties, which I would expect under the "File" menu.

**Comment by ignaciogros** [comment]
Hi @guyikcgg,

**Thank you for this and other suggestions.** We close this one (and consider others), as this will require major changes, and we're already working on a new eXeLearning version that will handle those properties in a different way (package, node and iDevices will have their own properties). There's still no date for that version. Its development has just started.

**Comment by guyikcgg** [comment]
Hi @ignaciogros ,

Thank you for your answer! I've just discovered exeLearning and I'm excited about contributing to the project. Regarding this issue, I wonder if it would be more feasible to add a short disclaimer stating that the properties are project-wise. I don't know if that makes sense at all in the project's roadmap, just an idea to increase usability! :smiley: 

Cheers from Granada!
