### ISSUE TITLE
Error importing elp file "Wrong file format"

### ISSUE THREAD

**Issue by amfeli** [exelearning/iteexe#613]
Greetings to all. I've been working on a project for several days and today I couldn't open it: "Wrong file format", no more details. My version of eXeLearning is 2.6. Can anyone help me? I attach the elp file. Thanks in advance, I'm a bit desperate.
[ide_unex.zip](https://github.com/exelearning/iteexe/files/8187923/ide_unex.zip)

**Comment by ignaciogros** [comment]
Hi @amfeli,
Sorry, but the zip seems to be corrupted. Please read this topic in eXe's forums: https://exelearning.net/forums/topic/wrong-file-format/
I hope it helps.

**Comment by amfeli** [comment]
Thank you Ignacio, I had already tried everything recommended but without success. I am redoing the project with constant backups.

Ángel M. Felicísimo
https://scholar.google.com/citations?user=UbSXhpgAAAAJ&hl=es

________________________________________
De: Ignacio Gros ***@***.***>
Enviado: sábado, 2 de abril de 2022 12:18
Para: exelearning/iteexe
Cc: ÁNGEL MANUEL FELICÍSIMO PÉREZ; Mention
Asunto: Re: [exelearning/iteexe] Error importing elp file "Wrong file format" (Issue #613)

Closed #613<https://github.com/exelearning/iteexe/issues/613>.
