### ISSUE TITLE
FR: Editor estilos

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#64]
Comentario de usuario
"Echo en falta, en el editor de estilos, poder definir en % el tamaño de la letra tanto en el bloque central como en el menu de navegación de forma diferenciada. Incluso estaría bien poder delimitar el ancho de la columna del menu."
Lo valoramos y comentamos

**Comment by ignaciogros** [comment]
**Control del tamaño del texto:** 61b93e5752ab8e5b0d9e4d88f2b76641d9d7e377 y 9f861342e479540698665a07a15cfa5a8930f3bb.

**Control del tamaño del menú:** a2c72e7f672f353427962b9de798eb0e06a3e1ad.

Por cómo están organizados los campos, y por facilitar el control del tamaño del texto de todos los elementos desde un mismo punto, se permite:

- Definir el tamaño general.
- Definir el tamaño de la navegación (botón para ocultar/mostrar el menú, elementos del menú y enlaces de Anterior y Siguiente).
- Definir el tamaño del título de la cabecera (esto no es nuevo).
- Definir el tamaño del texto del pie de página.

De esta manera **se pueden controlar de forma independiente todos los bloques**.

¿Cierras si no encuentras fallos, Antonio?

Gracias...

**Comment by ignaciogros** [comment]
Comprobado.
