### ISSUE TITLE
Wikipedia iDevice. It doesn't work in some languages

### ISSUE THREAD

**Issue by pabloamayab** [exelearning/iteexe#662]
It throws an exception in Catalan and Galician (There could be more languages). English and Spanish works well.

**Comment by ignaciogros** [comment]
It still fails. Example:

- eXe in Spanish (it happens if it's in Catalan too).
- Add a Wikipedia iDevice **in Catalan**.
- Type something and click on "Cargar".

**Comment by ignaciogros** [comment]
If failed with a Spanish article too.

**Comment by ignaciogros** [comment]
It just failed in my IDE, but the new installer works.
