### ISSUE TITLE
Python2 in exe/engine/version.py

### ISSUE THREAD

**Issue by Eloitor** [exelearning/iteexe#663]
Hi, I'm trying to package iteexe for Void Linux. During the build I encounter this error because the file `exe/engine/version.py` still uses python2 code like `print` without parenthesis. Here is the error that I get:

```
Traceback (most recent call last):
  File "/builddir/iteexe-2.7/setup.py", line 9, in <module>
    from exe.engine import version
  File "/builddir/iteexe-2.7/exe/engine/version.py", line 83
    print project, version
    ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by ignaciogros** [comment]
eXe is still a Python 2 application. You'll have to run it using python2.
A new version is being developed, but it'll be PHP, not Python 3.
eXeLearning 2.8, which will be released very soon, will have an AppImage version that may work for you.
