### ISSUE TITLE
No aparece menú parte superior derecha

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#67]
Al hacer un exportado html del elp 
http://descargas.pntic.mec.es/cedec/proyectoedia/matematicas/contenidos/fuentes/essis.elp
 con el estilo cedec-oficial NO aparece el enlace MENU de la parte superior derecha que muestra u oculta el menú de navegación 
![captura de pantalla de 2016-06-24 10 54 21](https://cloud.githubusercontent.com/assets/3305838/16333178/2a216830-39fa-11e6-8aa6-b7d07ba39f59.png)

**Comment by ignaciogros** [comment]
No es un fallo de eXe. Es que en el campo "Pie de página" de la pestaña "Propiedades" hay una etiqueta SCRIPT sin cerrar. Basta con añadir esto al final del contenido del campo: 

`</script>`
