### ISSUE TITLE
intef-exe-appimage_2.8_all.deb: Source field in control file

### ISSUE THREAD

**Issue by algodelinux** [exelearning/iteexe#677]
Source field in control file identifies the source package name. if you use this field to specify the url of the project, an error occurs when trying to add the package to a repository.

**Comment by ignaciogros** [comment]
¿Tienes claro el cambio que habría que hacer? Si es así, ¿nos lo puedes decir o hacer una _pull request_ para que revisemos. Si no lo miraremos, por supuesto, pero eso nos ahorraría tiempo. ¡Muchas gracias!

**Comment by algodelinux** [comment]
Lo único que habría que hacer es modificar el fichero **debian/control** del paquete y eliminar la línea que dice: 
**Source: https://github.com/exelearning/iteexe**
O cambiarla por:
**Source: intef-exe-appimage**
El campo Source debe incluir el nombre del paquete fuente. No puede incluir una url.

**Comment by pabloamayab** [comment]
Solucionado. Gracias @algodelinux
