### ISSUE TITLE
Error tamaño vídeo mp4 con javascript activado

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#68]
Al introducir un vídeo mp4 en tiny 4, con javascript activado no respeta en la previsualización ni en el exportado el ancho del vídeo que se le indica en la caja, tomando siempre el ancho máximo.
No se replica este comportamiento si desactivamos JS.
Adjunto imágenes
![videomp4_3](https://cloud.githubusercontent.com/assets/3305838/16480962/26d4abac-3ea9-11e6-8522-46572ea3c5b5.png)
![videomp4_2](https://cloud.githubusercontent.com/assets/3305838/16480961/26d3b788-3ea9-11e6-80f4-60f8d589fce3.png)
![videomp4_1](https://cloud.githubusercontent.com/assets/3305838/16480963/26dbb58c-3ea9-11e6-8dfc-09beec830a89.png)

**Comment by ignaciogros** [comment]
Commit: 3c5339b6e81c03c9b9d6f11a6b2e100fa586d7b9 (to review).

MediaElement.js changed the dimensions. Please test this solution in different devices/resolutions.
