### ISSUE TITLE
editor matemático no funciona

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#69]
Funciona en edición.
No funciona en previsualización y exportados

**Comment by ignaciogros** [comment]
No puedo reproducirlo. De todas formas, el mecanismo es el mismo en los tres casos. Si te sigue fallando adjunta la exportación en zip, por favor.

**Comment by antoniomonjef** [comment]
![tres](https://cloud.githubusercontent.com/assets/3305838/16517258/d7171fb2-3f7c-11e6-888d-3e59a6fa16ce.png)
![dos](https://cloud.githubusercontent.com/assets/3305838/16517260/d7233ad6-3f7c-11e6-88ec-1e4100f29e30.png)
![uno](https://cloud.githubusercontent.com/assets/3305838/16517259/d71f088a-3f7c-11e6-888e-06d04ff061a1.png)

**Comment by ignaciogros** [comment]
Si lo escribes así sí funciona:

`\[ \frac{1}{3} \]`

He hecho que el código LaTeX se envuelva así cuando el usuario no lo ha hecho:

`\[ ... \]`

Es una solución que podría afectar a otras fórmulas. No sé si es mejor dejarlo como estaba y que el usuario escriba el código como MathJax lo necesita.

¿Qué te parece? Si la solución actual te parece correcta (el código se envuelve desde common.js sin avisar al usuario), se puede cerrar la incidencia.

Otra opción es que el plugin de TinyMCE te avise antes de insertar el código: "¿Envolver el código LaTeX entre \[ y \] antes de insertarlo (puede hacerlo más adelante si la fórmula no se ve bien)?"

Y una tercera opción: poner un aviso claro en el plugin ("Posibles motivos por los que la fórmula no se ve correctamente...").

**Comment by antoniomonjef** [comment]
No, creo que tiene que ser automático.
La fórmula en latex es \frac{1}{2} y por tanto tienen que dibujarla así

**Comment by ignaciogros** [comment]
Commit: 6c123fc6516f23b8d965525ca23e6f77a56d4ffd

- La fórmula ya no desaparece. Antes la eliminábamos y luego añadíamos la nueva. Ahora simplemente se modifica la anterior.
- Ya no es necesario marcar a mano la capa porque al estar en el párrafo de la fórmula se reconoce el contenido del bloque.
