### ISSUE TITLE
Problema ficheros adjuntos

### ISSUE THREAD

**Issue by bebuspe** [exelearning/iteexe#695]
En un exelearning ya creado con un idevice ficheros adjuntos no me deja adjuntar ficheros.
![image](https://github.com/exelearning/iteexe/assets/136918220/dd3e94d1-9801-4bfa-9a31-f79002338133)
Está en escritorio y el pdf no es grande. No me sube ningún pdf.

**Comment by ignaciogros** [comment]
¿Has probado colocando el PDF en otro sitio? Por si fuera un problema de permisos. ¿Puedes probar subiéndolo desde una carpeta que nos sea de usuario (ni Documentos, ni Escritorio...)? 
Es imprescindible pulsar en "Cargar". Supongo que lo habrás hecho, pero por si acaso...
Si sigues teniendo problemas, necesitaríamos más información para intentar solucionarlo: sistema operativo y versión de eXe, el fichero exe.log, que está en la carpeta de usuario y, a ser posible, el PDF. Si prefieres puedes enviar todo a la dirección que aparece a pie de página en https://exelearning.net/

Gracias por el aviso.

El fichero exe.log se encuentra en:
Linux: ~/.exe (Carpeta personal. Visualizamos las carpetas ocultas (Ctrl + H) y borramos la carpeta .exe)
Windows: C:\Users\xxxx\AppData\Roaming\exe (donde xxxx es el nombre de usuario)
MAC: /Users/xxxx/.exe

**Comment by DRGTEACHER** [comment]
Buenas tardes, me estoy encontrado con el mismo problema. Ya me ha pasado en dos actividades diferentes... ¿Cómo se puede solucionar esto? Me está suponiendo más problemas la plataforma que las actividades...


Un saludo

**Comment by ignaciogros** [comment]
Por favor, si crees que es un fallo de eXe, adjunta adicional y archivos. Ese iDevice (Ficheros adjuntos) es antiguo, y sabemos que tiene algunos problemas de ese tipo. Los problemas más habituales son: ruta o nombres de fichero demasiado largos o con caracteres especiales (espacios, tildes...), problemas de permisos para acceder a carpetas de usuario (Mis Documentos, Escritorio...). Modificando eso, no debería haber problema. En cualquier caso, con un iDevice de Texto se puede adjuntar cualquier archivo, simplemente enlazándolo.

**Comment by anaduro3** [comment]
Buenas tardes, 

En mi caso, eliminé un PDF que yo misma subí como evidencia por tener una errata y automáticamente se me borró el bloque de subir el PDF en la parte de Innovación Metodológica (Infografía). Intenté también descargar e importar de nuevo el estilo y me da error porque dice que ya existe a pesar de haberlo eliminado de todos los sitios del ordenador. ¿Qué puedo hacer? Porque estoy desesperada. ¿Me podéis mandar el bloque con el estilo de nuevo o restablecérmelo? porque no puedo acceder ni hacer nada. Gracias

**Comment by ignaciogros** [comment]
> Buenas tardes,
> 
> En mi caso, eliminé un PDF que yo misma subí como evidencia por tener una errata y automáticamente se me borró el bloque de subir el PDF en la parte de Innovación Metodológica (Infografía). Intenté también descargar e importar de nuevo el estilo y me da error porque dice que ya existe a pesar de haberlo eliminado de todos los sitios del ordenador. ¿Qué puedo hacer? Porque estoy desesperada. ¿Me podéis mandar el bloque con el estilo de nuevo o restablecérmelo? porque no puedo acceder ni hacer nada. Gracias

En https://exelearning.net/faq/#faq-032 se explica dónde está la carpeta de usuario. Si la borras y vuelves a abrir eXe, tendrás los estilos que venían instalados por defecto. Pero ten en cuenta que se borrarán los estilos e iDevices propios que tuvieras. 

Por favor, para cuestiones de soporte, escribid al grupo de Telegram de eXe (https://t.me/eXeLearning) o a la dirección que aparece a pie de página en la web de eXe. Este espacio es un únicamente para gestionar problemas detectados en la aplicación. Muchas gracias.

Cierro la incidencia por falta de información para reproducir el problema.
