### ISSUE TITLE
Geogebra Iframe

### ISSUE THREAD

**Issue by jlmunoz161** [exelearning/iteexe#696]
Hola.

Mi nombre es José Luis, soy ATD en el Ministerio de Educación y estoy elaborando situaciones de aprendizaje con exelearning. 

Creo que tengo un problema.

Al insertar un iframe con un applet de GeoGebra, observo que el marco que contiene el iframe no es responsive, es decir, el applet geogebra se adapta al tamaño de la ventana pero el marco blanco en el que está incluido no.

Adjunto una imagen.
![Iframe_GeoGebra](https://github.com/exelearning/iteexe/assets/65860967/8fa21e42-a809-455c-b0b3-a14cd85b1453)

Uso exelearning 2.8.1, y el estilo del Ministerio de Educación.

**Comment by jlmunoz161** [comment]
Hola.

Subo el ELP(renombrar la extensión a ELP). 

En el botón logotipo aparecen 3 "pestañas" en tarea está insertado el ggb como iframe. Al escalar la pantalla, deja un hueco en blanco debajo del ggb.

[Ejemplo_ELP.zip](https://github.com/exelearning/iteexe/files/11896546/Ejemplo_ELP.zip)

También adjunto el estilo que uso, aunque lo he comprobado en varios y no funcionan en ninguno.

[mefp-materiales-primaria.zip](https://github.com/exelearning/iteexe/files/11896548/mefp-materiales-primaria.zip)

Un saludo.

**Comment by ignaciogros** [comment]
Es el propio código de GeoGebra el que especifica la altura del IFRAME (600px). El problema es que no podemos poner un style="height:auto" en el IFRAME porque su contenido se mostraría muy pequeño. Lo ideal sería resolverlo con un código de inserción que tenga eso en cuenta. Desde eXe no podemos acceder a los contenidos del IFRAME para ver sus propiedades (su altura en este caso), porque están en un dominio externo. 

Sí se puede calcular el tamaño del IFRAME sobre la marcha. Ejemplo: si tiene 400 de ancho, en este caso tendría que medir 400x300, en lugar de 400x600. Pero sin estar completamente seguros de que en GeoGebra siempre es así, no podemos incluir el código en eXe. Adjunto ejemplo de elp con un código que hace eso. El código está en Propiedades - Pie de página.

[Ejemplo de elp](https://github.com/exelearning/iteexe/files/11905377/Ejemplo_ELP_con_cambios.zip)

**Comment by jlmunoz161** [comment]
Hola.

No veo nada en Propiedades - pie de página.
Además cuando voy a abrir el fichero me dice Formato de archivo incorrecto. 
Lo he probado en windows y mac.

Un saludo.

**Comment by ignaciogros** [comment]
> No veo nada en Propiedades - pie de página.
Activa primero el modo avanzado.
>  Además cuando voy a abrir el fichero me dice Formato de archivo incorrecto.
Es problema del elp. Posible solución: https://exelearning.net/faq/#faq-037
Si no funciona, puedes enviar el elp a la dirección que aparece a pie de página en la web de eXe.

**Comment by jlmunoz161** [comment]
Ya lo he podido ver. Era un problema con el zip.

Interesante la solución.

Yo había llegado a esta:

1. Colocar dentro de un div el iframe.
2. Ajustar el iframe dentro del div.

```
<div style="text-align: center; position: relative; overflow: hidden; padding-top: 75%; border-width: 0px; border-style: solid;">

   <iframe width="800px" height="600px" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 4px;" src="https://www.geogebra.org/material/iframe/id/ex75mfqb/width/800/height/600/border/888888/sfsb/true/smb/false/stb/true/stbh/false/ai/false/asb/true/sri/true/rc/true/ld/true/sdz/true/ctl/false">
        </iframe>
</div>

<figure class="exe-figure exe-media license-CC-BY-NC position-center" style="text-align: center;">
<figcaption class="figcaption"><a href="https://www.geogebra.org/u/jlmunoz" target="_blank" class="author" rel="noopener">José Luis Muñoz Casado</a>. <a href="https://www.geogebra.org/m/guhy7tf8" target="_blank" class="title" rel="noopener"><em>Diseña tu logo</em></a> <span class="license"><span class="sep">(</span><a href="http://creativecommons.org/licenses/?lang=es" rel="license nofollow noopener" target="_blank" title="Creative Commons BY-NC">CC BY-NC</a><span class="sep">)</span> </span></figcaption>
</figure>
```

¡Muchas gracias!
