### ISSUE TITLE
HELP! - Can you manually add navigation Buttons in eXeLearning?

### ISSUE THREAD

**Issue by whamadmin** [exelearning/iteexe#697]
Greetings, I hope someone can help.

I'm using eXeLearning to create some scorm files for staff training.
Unfortunately the learning platform we use do not add navigation buttons, so no one can move past the first page.
Is there any way for me to manually add navigation buttons with eXeLearning?

Thanks!

**Comment by ignaciogros** [comment]
Hi,
No, at least for the moment. eXe is multi-SCO and exports as many HTML pages as nodes you create in eXe, but there's no menu in them.
If you need a menu, you can use the Web Site export option, but you can't get scores using it because that's not a SCORM package.

**Comment by macariem** [comment]
Any updates on this?

**Comment by ignaciogros** [comment]
No. The Web Site export is the only one with navigation menu. If that changes (it's not planned for the moment), it won't be soon.
