### ISSUE TITLE
Error en la postinstalación del paquete para Debian/Ubuntu (v. 2.8.1)

### ISSUE THREAD

**Issue by sio2sio2** [exelearning/iteexe#698]
Acabo de instalar la versión 2.8.1 del paquete para Debian/Ubuntu y se produce un error de [post]instalación, porque mi sistema no tiene instalado gsettings. Revisando el código de ``/var/lib/dpkg/info/intef-exe-appimage.postinst`` he visto que se hace la comprobación con:

```
if [ -x  $(which gsettings) ]; then
   #  ...
fi
```

Así que sospecho que faltan unas comas para que la comprobación sea falsa en caso de que which no devuelva nada . O mejor, simplemente:

```
if which gsettings > /dev/null; then
  # ...
fi
```

Porque el propio which ya devuelve verdadero o falso según exista el ejecutable o no.

Y, aunque sea sólo un detalle, ¿por qué se usa como intérprete bash? Esas cuatro líneas funcionan perfectamente con [da]sh, que es el intérprete estándar para los script del sistema. De hecho, los script de instalación del resto de paquetes es lo que usan.

**Comment by ignaciogros** [comment]
Muchas gracias por el aviso. Tomamos nota del fallo para corregirlo en la próxima versión.

**Comment by pabloamayab** [comment]
@sio2sio2 Usamos bash porque sh no me ejecuta ${theme:1:-1}
El otro cambio ya está aceptado.
