### ISSUE TITLE
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by pbazua** [exelearning/iteexe#70]

**Comment by ignaciogros** [comment]
¿Puedes dar más detalles del problema, por favor? Gracias.

Could you give more details on the problem? Thank you.

**Comment by pbazua** [comment]
Buenos días, Sr. Gros:
Estaba trabajando  en un SCORM realizando un cuestionario,  la pregunta 11
marcó el error, terniné en la 10 y no hubo más mensajes,Gracias.
Good   Morning, Mr. Gros:
Working a SCORM questionary, at question 11 poppe up an error warning,
ended it with 10 questions, & didn´t get more warnings. Kindly regards.


*I.M.E. Luis Pedro Alcántar Bazúa*
*Ced. Profesional 3101248*
*Corresponsable DROEIE-100*
*Reg. Prot. Civil UM-AHO/007/2015*
*Tel 668 824 7010*
*Cel 668 856 8386*

2016-07-18 4:02 GMT-06:00 Ignacio Gros <notifications@github.com>:

**Comment by ignaciogros** [comment]
No consigo reproducir el fallo. ¿Puede adjuntar un zip con el elp, por favor?

Gracias.

**Comment by pbazua** [comment]
Disculpa que te haga trabajar, y no recuerdo si este es el archivo donde se
produjo el fallo. De todos modos te lo envío.
Gracias por tu atención.

*I.M.E. Luis Pedro Alcántar Bazúa*
*Ced. Profesional 3101248*
*Corresponsable DROEIE-100*
*Reg. Prot. Civil UM-AHO/007/2015*
*Tel 668 824 7010*
*Cel 668 856 8386*

2016-07-19 7:04 GMT-06:00 Ignacio Gros <notifications@github.com>:

**Comment by ignaciogros** [comment]
No veo el adjunto. ¿Puedes incluirlo de nuevo, por favor?

**Comment by ignaciogros** [comment]
We can't reproduce the problem. Closed until we have more information.
