### ISSUE TITLE
No funciona un enlace para colgar un PDF

### ISSUE THREAD

**Issue by ElenaCabezudo** [exelearning/iteexe#701]
Buenos días:
En un curso de la Comunidad de Madrid que estoy realizando que está hecho con una plantilla de contenido que nos facilitan hay un enlace para colgar un PDF que no funciona. Cuelgas el documento y al dar al tic de grabar no se queda grabado. ¿Qué puedo hacer?
Gracias de antemano.
Elena

**Comment by ignaciogros** [comment]
• Prueba a quitar tildes, espacios y otros caracteres especiales del nombre del documento o la ruta (nombres de carpetas).
• Prueba situando el documento en otra carpeta (en C://Ejemplo, por ejemplo), por si fuera un problema de permisos. A veces, según el perfil del usuario del sistema operativo, puede haber problemas para acceder Descargas, Escritorio u otras carpetas de sistema.

Para este tipo de consultas, puedes usar el [grupo de Telegram de eXeLearning](https://t.me/eXeLearning) o el correo que aparece a pie de página en https://exelearning.net/
