### ISSUE TITLE
adding custom fonts to style editor

### ISSUE THREAD

**Issue by lvermeyden** [exelearning/iteexe#702]
Is there a way for me to upload a more font options to the style manager? I have tried adding some overriding CSS code in the content.css box but that does not seem to be working

**Comment by ignaciogros** [comment]
No. Only those families are available there, but you can include them in your style using `@font-face`
See cedec's content.css file. That style uses the Quicksand font family, and the required woff2 files are parte of the style.
I hope it helps.
Please use the [Telegram group](https://t.me/eXeLearning) or the eXeLearning email for support. Thank you.
