### ISSUE TITLE
Error guardado en eXeOnline

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#71]
Archivo > Guardar se produce el siguiente mensaje y "no llega a guardarse" el elp (p1.elp). La barra de carga está siempre funcionando aunque al recargar la página y el elp con posterioridad, parece que ha conservado los cambios y el guardado.
Adjunto captura
![captura de pantalla 2016-07-18 11 27 04](https://cloud.githubusercontent.com/assets/3305838/16910893/86aeb38e-4cdb-11e6-84f3-eee714cd75b7.png)

**Comment by ignaciogros** [comment]
I think that it's already saving properly. @david-puente: Please close if it's been fixed.
