### ISSUE TITLE
Duplicated scripts when exporting cause JS errors

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#713]
Export a complex content as single page. Some scripts are duplicated (selecciona-activity.js, completa-activity...). That causes a JS error and some activities won't work. Scripts and CSS files should be in HEAD just once.

**Comment by ignaciogros** [comment]
Example elp: [single-page-error.zip](https://github.com/exelearning/iteexe/files/13543743/single-page-error.zip)

Export as single page to see the error.

See printJavaScriptIdevicesScripts in common.py and addListIdevicesFiles in helper.py

**Comment by pabloamayab** [comment]
Only need delete duplicates idevices lines in singlepage.py
