### ISSUE TITLE
He perdido un archivo muy importante de eXe learning y no puedo recuperarlo

### ISSUE THREAD

**Issue by Noe1997-art** [exelearning/iteexe#753]
Buenos días, 

Les escribo este mensaje porque necesito que me ayuden a recuperar un archivo de eXe Learning muy importante para mí que se ha perdido por culpa de una tormenta y ya no sé recuperar. Estaba trabajando tranquilamente en una nueva unidad didáctica cuando, por culpa de un rayo, he perdido la conexión a Internet temporalmente y antes de que me diera tiempo a guardar el documento. En cuanto he ido a abrirlo de nuevo, en el archivo ya no había nada del trabajo hecho previamente. Se ha perdido todo y ahora solo queda un archivo en blanco. ¿Saben si se guarda alguna copia de seguridad de estos documentos en alguna parte? ¿Saben si puedo recuperar el documento en el que estaba trabajando de alguna manera? O una versión anterior, como mínimo. Las únicas versiones que tengo a penas tienen nada trabajado y no puedo usarlas. Cualquier ayuda es válida, pero facilítenmela por favor. 
Muchas gracias

**Comment by ignaciogros** [comment]
Puede enviar el elp a la dirección que aparece a pie de página en la web de eXeLearning. El trabajo solo podrá recuperarlo de ahí o de una exportación previa (si la tiene y no consigue abrirla, envíela también a esa dirección). Si está trabajando con la versión online de eXeLearning, indíquelo en el correo. En ese caso, tal vez los técnicos que gestionan esa versión puedan recuperar parte de la información de los directorios temporales.

**Comment by Noe1997-art** [comment]
Buenos días,

He intentado enviar un correo a ***@***.*** porque es la dirección
de correo electrónico que aparece al final de la web de eXelearning, pero
parece ser que esa dirección de correo es fallida y no recibe mensajes.
¿Estás seguro de que es ahí donde tengo que notificar los errores? ¿Hay
otra dirección de correo o teléfono que no haya visto y donde puedan
ayudarme a solucionar este problema?

**Comment by ignaciogros** [comment]
Gracias por el aviso. Hemos avisado a los responsables del mantenimiento del correo. Si prefiere, puede adjuntar el elp aquí.

**Comment by Noe1997-art** [comment]
Entendido. Les adjunto el elp a continuación. Sigue pasandome lo mismo que
hace unas semanas, en cuanto intento abrirlo solo sale un archivo vacío
cuando antes había hasta diez sesiones de aprendizaje.
 Situación de aprendizaje nº1.elp
<https://drive.google.com/file/d/1DFG2t-6W8gp-NeBmep_0OviAzksnZTJK/view?usp=drive_web>

**Comment by ignaciogros** [comment]
No podemos acceder a ese enlace. No es público. Por favor, ¿puede revisarlo?

**Comment by Noe1997-art** [comment]
Situación de aprendizaje nº1.elp
<https://drive.google.com/file/d/11IU1v7inurdx7BH7fNuoOYjvnHMlIf4F/view?usp=drive_web>

**Comment by ignaciogros** [comment]
El enlace requiere invitación con cuenta de Google. No es un enlace abierto a todo aquel que lo tenga.

**Comment by ignaciogros** [comment]
Con cambiar la extensión de elp a zip debería ser suficiente. Lo importante es que se trate de un enlace abierto, para que cualquiera que lo tenga pueda acceder al contenido. Puede comprobar si funciona abriendo una ventana privada en el navegador y accediendo a ese enlace.

**Comment by Noe1997-art** [comment]
Creo que esta sí podrá abrirla, pero el tamaño del archivo es menor que el
de los archivos anteriores, así que seguramente la información que había se
habrá perdido.

**Comment by ignaciogros** [comment]
Creo que falta el enlace.

**Comment by Noe1997-art** [comment]
Le envío varias versiones en formato .zip a ver si puede recuperar alguna.
La primera es en principio la que más me importa porque es en la que estaba
trabajando cuando se cayó la red, pero si no es posible recuperarla y puedo
trabajar con una versión anterior, lo haré.

 Situación de aprendizaje nº1.zip
<https://drive.google.com/file/d/1hTi_51s2G10MnQmhXKvn2yXWYrTT-Ppn/view?usp=drive_web>

**Comment by ignaciogros** [comment]
Sigue pidiendo acceso con cuenta de Google. Tiene que permitir el acceso a cualquiera con el enlace. Puede comprobar si funciona abriendo una ventana privada en el navegador y accediendo a ese enlace. Ya está solucionado el problema del correo de eXeLearning. Por si prefiere enviarlo ahí.

**Comment by Noe1997-art** [comment]
Voy a intentarlo. De todas formas le he dado acceso a mi cuenta de Google y
supuestamente eso deberia ayudar

**Comment by ignaciogros** [comment]
Lo sentimos, pero no hemos podido recuperar el contenido del fichero porque el zip está dañado. Hemos conseguido descomprimirlo, pero probablemente no contiene todos los ficheros que debería contener. Faltan los ficheros necesarios para que eXeLearning pueda recuperar el contenido: contentv3.xml o content.data

Tal vez pueda intentar recuperarlo con alguna herramienta específica para la recuperación de zip dañados. Otra opción es recuperar parte del contenido con una exportación previa. Ojalá lo consiga.
