### ISSUE TITLE
transfer of points from exe quizzes to Moodle

### ISSUE THREAD

**Issue by jdziew** [exelearning/iteexe#759]
I have a problem with transfer of data (number of points obtained in quizzess) from Exe package (version 2.9) to Moodle ver 3.9+. Of course I use SCORM 1.2. as a transfer file available to be embedded in Moodle.
During solving the questions points are displayed but finally are not provided in results in Moodle. 
How this problem can be solved?   
Example questions with obtained points (3 out from 14) is included
![PrtScreen](https://github.com/user-attachments/assets/a05f2471-0895-4ad1-b860-734033df021e)

**Comment by ignaciogros** [comment]
Could you attach the SCORM file so we can test it with Moodle? If you prefer, just send a download link. You'll find the email address in exelearning.net al the bottom of each page.

**Comment by jdziew** [comment]
Thank you very much for an answer. Please find two attachments: packed (zipped) EXE file (v. 2.9) and SCORM 1.2 exported version that would be embedded in the Moodle course. As you can see I use for my quizzess practically one kind of EXE activities - Fill-in gaps. Due to size of the original files I included only part of the course.
scorm: [ANS-test.zip](https://github.com/user-attachments/files/16658002/ANS-test.zip)
exe: [ANS-test-exe-pack.zip](https://github.com/user-attachments/files/16658021/ANS-test-exe-pack.zip)

**Comment by ignaciogros** [comment]
Hi,
It's just that the Cloze Activity is not SCORM-compatible. The user can see the score, but it won't be saved.
Only these activities can save it: SCORM Quiz, Interactive Video, most of the games.
We hope that in the future all quizzes will be compatible, but most of the old ones are still not.
