### ISSUE TITLE
Configuración inicial HTML5

### ISSUE THREAD

**Issue by antoniomonjef** [exelearning/iteexe#76]
En w7 (supongo que en el resto de SO sucede igual, aunque no probado) la configuración inicial en una instalación en limpio es de preferencias > avanzado XHTML permisivo.
Creo que deberíamos salir ya con una configuración por defecto HTML 5

**Comment by ignaciogros** [comment]
Hecho: 87b81ac84250dd72d83738a25301c4055732274f

La rama tinymce-4 ya tenía ese tipo por defecto. Cuanto antes mejor, sí.

**Comment by jrfern** [comment]
On 20 July 2016 at 09:53, Ignacio Gros <notifications@github.com> wrote:
>
> Hecho: 87b81ac
>
> La rama tinymce-4 ya tenía ese tipo por defecto. Cuanto antes mejor, sí.

Yo me ofrecí a ayudar con las pruebas pero durante unas semanas voy a
estar desconectado. Insisto en que sería momento, cunaod lo veas
maduro, Ignacio, de pasar los cambios de la tinymce-4 a master, para
que más ojos busquen bugs. Quien usa master de desarrollo sabe que
está usando una versión inestable y que va a encontrar fallos.

Un saludo y buenas vacaciones
-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by antoniomonjef** [comment]
Vamos a Master entonces.
Yo la veo estable para pasarlo (aunque encontraremos cositas y algún detalle) pero la veo muy estable

**Comment by ignaciogros** [comment]
¡Hecho!
