### ISSUE TITLE
Custom User iDevices not showing in iDevicePane

### ISSUE THREAD

**Issue by rfrobenius** [exelearning/iteexe#766]
I have successfully written a custom python idevice using the examples and documentation that I could find. However, there is a problem with the custom iDevice not showing in iDevicePane despite successfully loading (according to DEBUG log). I have tracked the issue down to __loadExtended() starting in line 473 of iDeviceStore.py. On line 479 the user-created iDevices are successfully loaded. 
In exampleidevice.py line 53 the custom iDevice is appended to ideviceStore.extended when the register() function is called.
However, subsequently in lines 493 and 496 of idevicestore.py, ideviceStore.extended gets re-initialized with new data, wiping out any custom iDevices that were registered there. As a result the custom iDevices never show in the iDevicePane.
I discovered a workaround which is to have my custom iDevice append to the jsIdevices array instead of the extended array in the call to register. That array does not get re-initialized and my custom iDevice does show up in the pane with category "My iDevices".

**Comment by ignaciogros** [comment]
Did you remove the user folder before restarting eXe? That where the custom iDevices, preferences and styles are stored.

**Paths:**

Linux (deb, rpm, AppImage): /home/YOUR-USER-NAME/.exe/
Windows: %AppData%\Roaming\exe\
macOS: /Users/YOUR-USER-NAME/.exe/

**Comment by ignaciogros** [comment]
Please provide more information if you want to reopen this issue. Thank your.
