### ISSUE TITLE
TinyMCE 4 Settings not used

### ISSUE THREAD

**Issue by rfrobenius** [exelearning/iteexe#77]
Hello-
I'm developing a new iDevice in Python. I have two plain text fields (for code, not HTML) and one rich text field. However, when TinyMCE 4 is used as the editor, the editor appears for all fields, even when the "always" setting is changed to something else (ie "sometimes") in the TinyMCE_4_settings.js file. In fact, I tried editing the scripts in the file to prevent the editor from being called when the help link is not found, etc. and it still showed up for every field.
If I remove the rich text field from the Idevice, then the two remaining plain text fields show up without an editor.
It's as if the tinymce_4_settings.js file is not being used or something.
When I change the editor to version 3, the idevice works as I would like, with the plain text fields having no editor and the rich text field showing the editor.
Any suggestions?

**Comment by ignaciogros** [comment]
TinyMCE is enabled when the TEXTAREA has the "mceEditor" class: $("textarea.mceEditor")

See richTextArea and textArea in common.py too.

I hope this will help you.

**Comment by rfrobenius** [comment]
Hi Ignacio-

Thanks for your reply, the problem is the TinyMCE v4 is _ignoring_ whether the "mceEditor" class is present or not and always appears. TinyMCE v3 works as you describe, the editor only appears for fields with "mceEditor" class and does not appear on the other fields. 
For now I can just avoid using TinyMCE 4.

**Comment by ignaciogros** [comment]
You're right. Thanks a lot, @rfrobenius. I'll fix that.

**Comment by ignaciogros** [comment]
Fixed: 3ea12929357d50ec1891b9d5fe5351a5dd09c0dd

Thanks for reporting!
