### ISSUE TITLE
EXELEARNING - ERROR EXPORTATION

### ISSUE THREAD

**Issue by cuemad** [exelearning/iteexe#772]
Hello

I have no idea what's going on with this sequence. 
It's a long time I do not use exe learning, and it's the first time this happen with the program.

ERROR EN LA EXPORTACIÓN [Errno 2] No such file or directory: u'/Users/Eva/.exe/style/FPD-MEDU-1/../exe_powered_logo.png'

Thanks a lot in advance.

**Comment by ignaciogros** [comment]
Please attach the elp file (you'll have to change its extension to .zip) and the style you're using.

**Comment by ignaciogros** [comment]
Please attach an example elp file, as well as your style, if you want to reopen the issue. Thank you.
