### ISSUE TITLE
iDevice DUA problem with < and > symbols

### ISSUE THREAD

**Issue by pabloamayab** [exelearning/iteexe#778]
In source code editor HTML in DUA the next code fail when save and edit again.

`<p>(hay que aplicar la clase a la propia lista, no a los elementos. En el código <code>html</code> del iDevice debe quedar algo similar a: &lt;ul class="listaResaltada"&gt;. <br />Los efectos no se muestran en modo edición):</p>`

This doesn't happen in the text idevice.

**Comment by ignaciogros** [comment]
It's already solved. See #747
Just use the latest version of this file to fix it: exe/webui/scripts/idevices/udl-content/edition/udl-content.js
