### ISSUE TITLE
Exelearning, ¿ cómo habilitar modo pantalla completa para videos?

### ISSUE THREAD

**Issue by laugupe** [exelearning/iteexe#79]
He incrustado en Exelearning un video que en YouTube se ve sin problemas en pantalla completa, y no consigo que en el paquete scorm se vea en pantalla completa, ni al dentro de exelearning, ni cuando lo exporto a zip.
He probado a hacerlo tanto con el enlace como incrustando el código HTML.
Alguien sabe cómo podría habilitar esta posibilidad?
Muchas gracias.

**Comment by ignaciogros** [comment]
Supongo que el SCORM lo muestras en un LMS. Si es así, el documento HTML se está mostrando dentro de un IFRAME. Si no añades el atributo "allowfullscreen" a ese IFRAME, la opción de pantalla completa del reproductor no funcionará. Pero para eso tendrás que tener acceso al código fuente del LMS o ser su administrador (si es que ese LMS te permite hacer ese tipo de cambios desde su panel de control).

Alternativas: que el SCORM se abra en una ventana nueva (si el LMS lo permite) o dejarlo como está y usar el botón de "Ver en youtube.com", que sí funcionará.

Saludos.

**Comment by laugupe** [comment]
Ignacio muchas gracias por tus indicaciones,
conseguí hacerlo tal y como indicas, modificando el LMS,
un saludo.
