### ISSUE TITLE
Anchors are not working inside eXe

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#80]
Create a node. Then create a link to that node from another one. The link will work, even inside eXe, but if you try to link to a node which is in a lower level, the link to the anchor won't work.

**Comment by ignaciogros** [comment]
We can't use decodeURIComponent instead of unescape in all those cases. 

authoringpage.py, common.js and plugin.min.js were OK with unescape. If we use decodeURIComponent in common.js, some iDevices will fail (we'll get this error in the Dropdown activity, for example: 'URIError: malformed URI sequence').

I reverted the changes in authoringpage.py, common.js and plugin.min.js (9b3a4284a46bea23e5b12746c6fb08de87903cb7).

@JuanCasanovaSdweb: Could you check authoring.js so it uses decodeURIComponent just where needed?

Thanks.

**Comment by JuanCasanovaSdweb** [comment]
It should be good now. We will do more tests anyway.
