### ISSUE TITLE
FR: Easy system to import/export (JavaScript) iDevices

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#83]
Related task (to be closed before this one): https://github.com/exelearning/iteexe/issues/59

You can import/export Styles from Tools - Style Manager.

There should be something similar to import/export JavaScript iDevices (Tools - iDevice Manager?).

**Comment by ignaciogros** [comment]
**Tools - iDevice editor** already has an "Import iDevice" option. I think that we should use it. We have to think about the way those iDevices have to be treated (new fields shouldn't be added, etc.).

**Comment by JuanCasanovaSdweb** [comment]
We added a new **JsIdevice Manager** in **Tools** menu base on the styles' one.

It's possible to import, export and delete them.
