### ISSUE TITLE
Error when executing (Red Hat)

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#91]
The problem is described in the forums: http://exelearning.net/forums/topic/exelearning-2-1-error-when-executing-red-hat/

We should try to fix that as soon as possible.

**Comment by JuanCasanovaSdweb** [comment]
Te problem is that the RPM is copying the locales in the wrong directory. Is using /usr/share/exe/locale when it should be /usr/share/locale.

**Comment by ignaciogros** [comment]
Is it already fixed? Thanks...

**Comment by JuanCasanovaSdweb** [comment]
Not yet. Working on it.

**Comment by JuanCasanovaSdweb** [comment]
Closing as it is already fixed. Now the locales are copied to /usr/share/locale and a link is created inside /usr/share/exx/locale
