### ISSUE TITLE
FR: Easy system to add a TinyMCE plugin

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#93]
There should be an easier way to add TinyMCE plugins that require files to be exported. Example: 

If you use the Tooltip plugin and export your elp, some files will be exported (those in webui/scripts/exe_tooltips) and the required scripts will be included in HEAD. 

To do that, some Python files have to be edited (imsexport.py, websiteexport.py, etc.). 

It would be good to make that easier, so the plugins themselves could include the files to export. eXe would do the rest automatically if the plugin is used in the package.

**Comment by ignaciogros** [comment]
I think that this could be done now.

@JuanCasanovaSdweb:

See the attachment, please. I think it's not difficult, but tell me if I'm wrong. If it is, I'll add the ABC Music Notation plugin using the current system and we'll leave this for now.

Please let me know if you find a better solution.

Thanks.

[mecanismo_plugins_tinymce.zip](https://github.com/exelearning/iteexe/files/878870/mecanismo_plugins_tinymce.zip)

**Comment by JuanCasanovaSdweb** [comment]
Should be easy, but I can see two problems:

1. We should have a list of all the custom TinyMCE plugins the same way we have one for the JS IDevices. Even if we don't do it we will need it for phase 2, but I think it would make things easier to everyone if we do it from the beginning (It should also be updated on startup like the JS IDevices' one).

2. Your method is pretty good but I think we should take into account possible conflicts with _.
Maybe we could have a compatibility fallback (for example exeTinyMcePluginLocalication?) and let the user configure the use of one or the other on the config.xml file of the plugin.

Apart from that we need to decide if we will want the CSS and JS files of the plugin to be minimized on export or not. Any of the options will be easy to implement but if we allow them to be minimized we need to have a config option to prevent it.

**Comment by ignaciogros** [comment]
Good ideas, @JuanCasanovaSdweb. 

Thanks.
