### ISSUE TITLE
FR: eXe should be a python3 application

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#95]
Some day, near 2020, python3 will be the only python available (or the old python, and python4 the development version). We should be ready for that day. This has two aspects:
* Are the libraries we use ready for python3?
* Is our code ready?
I keep a page and I try to be uptodate
https://docs.google.com/document/d/1P-gru4tePvEvpVzTaDOzxYV9wIiwQqDPdtWSUsRXfFM/edit#

**Comment by jrfern** [comment]
What's the present situation of this issue?

**Comment by jrfern** [comment]
Well, I will answer my own question: eXe is no longer installable in the developing Debian derivatives (Testing, Unstable). It depends on libraries that are only present in the python3 version (today python-css, python-suds - the number goes up daily). Not that you can choose, the packages are no longer present, unless you are an expert and mix Stable and Testing, for example. This is no longer a FR, but a very serious bug. Therefore I change the label form FR to P1.

**Comment by jrfern** [comment]
@ignaciogros, should I pin this issue?

**Comment by ignaciogros** [comment]
OK. That's the number one priority. We're studying different possibilities. I won't treat this as a bug, but we have to do that. It's rewriting (some parts, even from scratch). I leave it unassigned for the moment.

**Comment by uliska** [comment]
I just came across this while investigating Free alternatives to the commercial closed-source elearning applications for my music university, and it's a pity that I can't install it to give it a try on my Debian testing machine.

**Comment by ignaciogros** [comment]
> I just came across this while investigating Free alternatives to the commercial closed-source elearning applications for my music university, and it's a pity that I can't install it to give it a try on my Debian testing machine.

I didn't try this, but we sent this instructions to another user and it worked for him. I know it's not the perfect solution. It's just something to do until we solve this issue. 

Debian testing has Python 2, so:

1.- Install PIP:
apt-get install python-pip

2.- Check dependencies:
dpkg-deb -I intef-exe_2.5_all.deb

3.- Install the unresolved dependencies with PIP:
python -m pip install beautifulsoup4 cssmin feedparser lxml requests-oauthlib rjsmin suds webassets zope-interface dateutils Pillow

4.- Install the package ignoring the dependencies:
dpkg -i --ignore-depends=python-zopeinterface,python-pil,python-chardet,python-lxml,python-bs4,python-suds,python-requests-oauthlib,python-dateutil,python-cssmin,python-webassets,python-feedparser,mimetex intef-exe_2.5_all.deb

5.- Launch eXe from the command line:
exe

**Comment by uliska** [comment]
Thank you. I tried it, and right now I could at least start the application, which launched in the browser (which I assume is correct). I'll definitely give the tool a closer look.

One comment (for the record, if someone else with the problem sees this): in 4. I had (of course) to use `sudo`.

I'm OK with using such a workaround as long as the availability of workarounds is not detrimental to working on the issue. I can relate to that because I know the problem from involvement in another Open Source program.

**Comment by uliska** [comment]
I must partially revoke my previous endorsement. It seems that this approach subsequently prevents the `apt` installation of *any* package that depends on any of the ignored Python packages, even if the package would actually use the Python3 versions. In order to install anything else I had to remove eXe through the invocation of `sudo apt --fix-broken install`, as suggested by `apt`.

**Comment by ignaciogros** [comment]
Thanks for sharing that information, Urs. I hope that we'll find a solution for this soon.

**Comment by glixx** [comment]
Python 2 is EOL and was dropped from Mageia Linux with eXe. Needs to release python 3 eXe as soon as possible.

**Comment by dmsoler** [comment]
Just added a [pull request #423](https://github.com/AppImage/pkg2appimage/pull/423) to [pkg2appimage](https://github.com/AppImage/pkg2appimage/). If it is accepted, generation of an AppImage of intef-exe will be an easy and straightforward task.

**Comment by ignaciogros** [comment]
> Just added a [pull request #423](https://github.com/AppImage/pkg2appimage/pull/423) to [pkg2appimage](https://github.com/AppImage/pkg2appimage/). If it is accepted, generation of an AppImage of intef-exe will be an easy and straightforward task.

Thank you, @dmsoler!

**Comment by dmsoler** [comment]
[Pull request #423](https://github.com/AppImage/pkg2appimage/pull/423) to [pkg2appimage](https://github.com/AppImage/pkg2appimage/) was merged.

You can generate an AppImage of intef-exe simply by downloading pkg2appimage last continuous build ( [pkg2appimage-continuous-x86_64.AppImage](https://github.com/AppImage/pkg2appimage/releases/download/continuous/pkg2appimage-continuous-x86_64.AppImage) ), making it executable ( `chmod` 0755 pkg2appimage-continuous-x86_64.AppImage` ) and running:
`./pkg2appimage-continuous-x86_64.AppImage intef-exe`

Note that the recipe included in pkg2appimage uses Debian oldstable packages to increase compatibility (see [this commit](https://github.com/AppImage/pkg2appimage/commit/7e3f70eb7b100a3fe800cedf9cb449bdb2f9c824) ).

**Comment by cyberorg** [comment]
kolibri uses some python2 in mostly python3 app, this is how they handle it by including them in the package dist folder:

	pip2 install -t kolibri/dist -r "requirements.txt"
	rm -rf kolibri/dist/*.dist-info  # pip installs from PyPI will complain if we have more than one dist-info directory.
	rm -rf kolibri/dist/*.egg-info
	rm -r kolibri/dist/man kolibri/dist/bin || true # remove the two folders introduced by pip 10
	python2 build_tools/py2only.py # move `future` and `futures` packages to `kolibri/dist/py2only`

https://github.com/learningequality/kolibri/blob/develop/build_tools/py2only.py

For Ubuntu 20.04 I've hacked together additional package with python2 deps as an experiment which works fine. 
https://launchpad.net/~jigish-gohil/+archive/ubuntu/education

**Comment by ignaciogros** [comment]
Thank you, @cyberorg!
We use [SNAP](https://snapcraft.io/exelearning) for the moment. I hope that we can upgrade or renew the code so there are no more compatibility problems.

**Comment by ignaciogros** [comment]
There will be a new eXe which will solve all this. There's no date yet. Thank you for your ideas and contributions!

**Comment by neurofreak-alt** [comment]
[https://github.com/exelearning/iteexe/issues/413#issuecomment-993102796](url)

**Comment by neurofreak-alt** [comment]
> Some day, near 2020, python3 will be the only python available (or the old python, and python4 the development version). We should be ready for that day. This has two aspects:
> 
>     * Are the libraries we use ready for python3?
> 
>     * Is our code ready?
>       I keep a page and I try to be uptodate
>       https://docs.google.com/document/d/1P-gru4tePvEvpVzTaDOzxYV9wIiwQqDPdtWSUsRXfFM/edit#


twisted now compatible with python3. Information should be updated.
