### ISSUE TITLE
Educational description field is larger than 1000 characters

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#96]
In SCORM 1.2, Educational description metadata field has a maximum of 1.000 characters. The package [in this ticket](http://exelearning.net/forums/topic/moodle-1-9-me-dice-que-el-scorm-subido-tiene-problemas/) has 1.800 characters and generates a warning when uploading to SCORM Cloud. The field is under LOM metadata. In SCORM 2004 this field can be longer.

It could generate an error when uploading to a platform but it has not been reported any error (SCORM Cloud truncates the text to 1.000 characters).

**Comment by ignaciogros** [comment]
The content of that field is also used in the META DESCRIPTION HTML tag. 

What moz.com says:
> 
Meta descriptions can be any length, but search engines generally truncate snippets longer than 160 characters. It is best to keep meta descriptions between 150 and 160 characters.

If the field can't have more than 1000 characters, **we should limit it now**.

We'll fix the HTML part in the future when adding the node preferences (language, title, description...), which is an old FR.

**Comment by jm-andonegi** [comment]
Hi Ignacio

This issue is related to SCORM metadata (LOM and LOM -es)

**Comment by ignaciogros** [comment]
¿Se resolvió esta incidencia, Juan?
