### ISSUE TITLE
FR: Multimedia Gallery instead of Image Gallery

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#97]
The "Image Gallery" iDevice could be a "Multimedia Gallery" iDevice allowing audios, videos, etc. instead of only images.

See http://exelearning.net/forums/topic/peticion-para-que-la-galeria-de-imagen-incorpore-sonido/#post-26341

**Comment by miguelpereiraite** [comment]
Esto yo creo que es muy interesante. ¿Está contemplado más adelante?

**Comment by ignaciogros** [comment]
A mí también me parece interesante. Estaría bien poder hacerlo el año que viene, combinándolo la subida múltiple de archivos.

**Comment by ignaciogros** [comment]
This FR has to parts:

1. **JavaScript** (and some Python): Show mp3, mp4, flv, ogg and ogv files in prettyPhoto. MediaElement (webui/scripts/mediaelement/*.*) should be exported when a link like that (`a[rel^='lightbox']` to any of those file types) exists.
2. **Python**: Allow mp3, mp4, flv, ogg and ogv files in the Image Gallery iDevice. eXe should generate a thumbnail for the gallery when uploading a video or an audio. It'd be good if the user could change that thumbnail later.

The first part is done (11f055c9b312a2cee684e53969611cd4bc432582). **No string translation required.**

@miguelpereiraite will confirm if the second part should be done now. If so, @JuanCasanovaSdweb, could do it. 

If we're not improving the Image Gallery iDevice right now, we can close this issue. 

**A related (and old) FR** (multiple file upload in the Image Gallery iDevice): https://github.com/exelearning/iteexe/issues/13

**Comment by ignaciogros** [comment]
The idea is to renew all the code (there's no date yet), and this should be part of that new version.
