### ISSUE TITLE
Exe no funciona e ubuntu 16.04 y Fedora 18

### ISSUE THREAD

**Issue by miguelpereiraite** [exelearning/iteexe#99]
Reporto incidencia llegada a través de uno de los componentes del grupo de probadores (Carles Ferrando) 
"La última versión de EXE no funciona en Ubuntu 16.04 y Fedora 18 , yo estoy utilizando la versión de windows instalable con wine y entonces funciona sin problemas"

**Comment by miguelpereiraite** [comment]
Nos comenta el usuario que el problema solo sigue en Fedora 24. Incluyo aquí la información que nos da

La salida de terminal para identificar a fedora es:
bash-4.3$ uname -a
Linux localhost.localdomain 4.5.5-300.fc24.x86_64 #1 SMP Thu May 19 13:05:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

La salida de terminal que muestra el error es:
bash-4.3$ exe
Traceback (most recent call last):
  File "/usr/bin/exe", line 58, in <module>
    main()
  File "/usr/bin/exe", line 55, in main
    application.main()
  File "/usr/lib/python2.7/site-packages/exe/application.py", line 97, in main
    self.loadConfiguration()
  File "/usr/lib/python2.7/site-packages/exe/application.py", line 189, in loadConfiguration
    self.config = configKlass()
  File "/usr/lib/python2.7/site-packages/exe/engine/config.py", line 223, in __init__
    self.loadLocales()
  File "/usr/lib/python2.7/site-packages/exe/engine/config.py", line 553, in loadLocales
    self.locales[self.locale].install(unicode=True)
KeyError: 'en'

He instalado wine y despues exe para windows utilizando la versión:
   Version: 2.1
    Revision: 947ab9aab1c0798e1d6007cc4dc3725ffa0c45ad

**Comment by jrfern** [comment]
2016-11-09 10:02 GMT+01:00 miguelpereiraite <notifications@github.com>:
>
> Reporto incidencia llegada a través de uno de los componentes del grupo de probadores (Carles Ferrando)
> "La última versión de EXE no funciona en Ubuntu 16.04

Haciendo de betatester sin tiempo (y esperando al aviso para lanzar
traducciones): no puede funcionar por falta de dependencias en
debian/control. Y n ocreo que pase sólo en 16.04.

Por lo pronto he tenido que instalar slimit y cssmin. Me sigue dando
error por falta de mx.Log, ¿a qué biblioteca pertenece?

Soy partidario de funcionar con dependencias del sistema, no tirar de
pip, que rompe el sistema de control de actualizaciones. Lo digo por
los consejos de installs/debian/ubuntu

Saludos
-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by jrfern** [comment]
On 10 November 2016 at 12:39, miguelpereiraite <notifications@github.com> wrote:
>
> Nos comenta el usuario que el problema solo sigue en Fedora 24.
> ...
> self.locales[self.locale].install(unicode=True)
> KeyError: 'en'

La causa está en la adaptación de las rutas de las carpetas al
estándar (locales en /usr/share/locales, no en
/usr/share/exe/locales). Lo hice para Debian, y creé enlaces a las
rutas antiguas de eXe (ver debian/intef-exe.links). No está hecho para
los rpm, supongo que habrá que tocar rpm-setup.py.

Esto no es nuevo, porque el cambio está en la versión anterior; es que
no se había detectado.

Saludos
-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by jrfern** [comment]
2016-11-11 9:49 GMT+01:00 Juan Rafael Fernández García <jrfern@gmail.com>:

> Por lo pronto he tenido que instalar slimit y cssmin.

Añadidas las dependencias a control y a lREADME.md de .../ubuntu y
subido el commit.

Supongo que hay que hacer lo mismo para rpm y resto de sistemas
operativos. Ahí no toco yo.
-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by ignaciogros** [comment]
Comentario relacionado en el foro (por si es necesario dar respuesta ahí una vez solucionado el problema): http://exelearning.net/forums/topic/exe-no-funciona-en-fedora-24/ 

¿Habéis podido mirar lo que comenta @jrfern del RPM, etc., @JuanCasanovaSdweb? Gracias...

**Comment by JuanCasanovaSdweb** [comment]
El problema está en que eXe se modificó hace un tiempo para cumplir la estructura de directorios de Linux. Es decir, los locales deberían copiarse en /usr/share/locale y no en /usr/share/exe/locale.

Hemos corregido el error, pero estamos revisando todo el proceso de generación del RPM para hacerlo igual que el de Debian/Ubuntu. Probablemente hoy mismo haremos un commit con la solución.
